{
  "hash": "265831946325f2a5d45a6f17ae4df1c9",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n# Logistische Regression {#sec-logistic-regression}\n\nWenn wir diskrete oder kategorielle Grössen modellieren\nwollen, ist das allgemeine lineare Modell nicht geeignet, da dieses\neine kontinuierliche abhängige Variable voraussetzt. Oft haben wir zum\nBeispiel eine zweiwertige kategorielle abhängige Variable (mit den\nWerten Event und kein Event). Gibt es eine Möglichkeit, diesen\nWertebereich auf ein Kontinuum abzubilden? Kann man das Allgemeine\nLineare Modell (LM) verallgemeinern und damit Modelle für diskrete und\nkontinuierliche abhängige Variable in einer einzigen statistischen Methodologie\nzusammenführen? \n\nDie Antwort darauf hat den Namen **Generalisierte Lineare Modelle\n  (GLM)** (also nicht zu verwechseln mit dem Allgemeinen Linearen\nModell (LM)). Dazu gehören zum Beispiel die **Poisson-Regression** (die wir später behandeln werden) sowie die **logistische Regression**, die wir hier studieren. Zu den GLM gehören als Spezialfall aber auch die bereits eingeführte multiple Regression und Varianzanalyse als Vertreter der Linearen Modelle.\n\nEin Beispiel für eine logistische Regression ist, wenn man z.B. mit Hilfe der Variablen Geschlecht, Krankheitsstadium, Tumorgrösse und Alter die Wahrscheinlichkeit bestimmen möchte, ob jemand seine Krebserkrankung überlebt, oder nicht.\n\n\n## Notation und `R`\n\n - $O$: Odds\n - $OR$: Odds Ratio\n - $\\pi$: Wahrscheinlichkeit, Risiko\n - $\\mathrm{logit}(\\pi)$: $\\log\\frac{\\pi}{1-\\pi}=\\log Odds$\n - $\\exp(x)$: $e^x$\n - $X \\sim \\mathcal{B}(n,\\pi)$: $X$ ist binomialverteilt mit Parameter $n$ und $\\pi$\n - $E(X)$: Erwartungswert einer Zufallsvariable  $X$ \n - $\\eta=\\beta_0+\\beta_1x_{1}+\\beta_2x_{2}+\\dots+\\beta_m x_{m}$: linearer Prädiktor\n\n - `R`: `packet::funktion()`: Alternative Syntax zu `library(packet)` gefolgt von `funktion()`\n - `R`: `glm()`: Funktion zum Anpassen von GLM's.\n\n\n## Lernziele\n\nBeachten Sie im Folgenden die überaus wichtigen Rechenregeln bezüglich der $\\log$ und $\\exp$-Funktion, die wir bereits kennengelernt haben. Sie werden uns auf Schritt und Tritt verfolgen:\n\n\n$$\n\\begin{aligned}\n\\log(ab) &= \\log(a) + \\log(b) \\\\\n\\log\\left(\\frac{a}{b}\\right) &= \\log(a) - \\log(b) \\\\\n\\exp(a + b) &= \\exp(a)\\exp(b) \\\\\n\\exp(a - b) &= \\frac{\\exp(a)}{\\exp(b)}\n\\end{aligned}\n$$\n\n\n::: callout-important\n\n# Lernziele\n\n\n\n1.  Wenden Sie eine logistische Regression an, wenn anhand einer oder mehrerer Prädiktorvariablen die Odds $O_i$ und die Wahrscheinlichkeit $\\pi_i$ für ein Ereignis (d.h. bei binärer abhängigen Variable) für die Einheit $i$ geschätzt werden sollen.\n\n2.  Beachten Sie, dass bei einer logistischen Regression die $\\mathrm{logit}(\\pi_i):=\\log Odds_i$ modelliert werden. Der lineare Prädiktor $\\eta_i$ ist dann der transformierte Erwartungswert,\n\n$$\n\\boxed{\\mathrm{logit}(\\pi_i) = \\eta_i=\\beta_0 + \\beta_1x_{i1}+\\dots+\\beta_m x_{im}.}\n$$\n\n3.  Berechnen Sie die geschätzten $\\mathrm{logit}(\\hat{\\pi}_i)$ durch Einsetzen der geschätzten Regressionskoeffizienten $\\hat{\\beta}_k (k=0,\\dots,m)$ sowie der Werte für die Prädiktoren der Einheit $i$ in die Regressionsgleichung.\n\n4.  Interpretieren Sie $\\beta_0$ (intercept) als $\\mathrm{logit}(\\pi_i)$ für das Ereignis, wenn alle unabhängigen quantitativen Variablen den Wert 0 annehmen und die Kategorie der unabhängigen kategoriellen Variablen die Referenzkategorie ist. \n\n5.  Interpretieren Sie die $\\beta_k$ ($k=1,\\dots,m$) als einen Unterschied auf der $\\mathrm{logit}$-Skala für zwei Subpopulationen, die sich auf $x_k$ um eine Einheit unterscheiden, während die anderen unabhängigen Variablen konstant gehalten werden. Die Nullhypothesen sind dann meistens $H_0: \\beta_k = 0$, $k=1,...,m$.\n\n6.  Eine Differenz auf der $\\mathrm{logit}$ Skala entspricht einem $\\log(OR)$.\n\n7.  Interpretiere die $\\exp(\\beta_k)$ ($k=1,\\dots,m$) als das $OR_k$ für das Ereignis für zwei Subpopulationen, die sich auf $x_k$ um eine Einheit unterscheiden, während die anderen unabhängigen Variablen konstant gehalten werden. Die Nullhypothesen sind dann meistens $H_0: OR_k = 1$, $k=1,...,m$.\n\n\n8.  Berechnen Sie die Wahrscheinlichkeiten $\\pi_i$ aus dem linearen Prädiktor mit der logitistischen Funktion,\n\n$$\n    \\boxed{\\pi_i = \\frac{O_i}{1+O_i}=\\frac{\\exp(\\eta_i)}{1+\\exp(\\eta_i)}.}\n$$\n\n9.  Führen Sie eine logistische Regression in `R` durch und interpretieren Sie die Regressionskoeffizienten sowie deren inferenzstatistischen Angaben.\n\n10.  Erklären Sie den zentralen Begriff der Likelihood: Die Likelihood eines Parameterwertes $L(\\theta)$ ist die Wahrscheinlichkeits(dichte) der beobachteten Daten $x$, gesehen als eine Funktion des Parameters $\\theta$,\n\n$$\nL(\\theta)=p(x;\\theta).\n$$\n\n11. Sie wissen, dass man im Falle der logistischen Regression Parameter mit der Maximum-Likelihood-Methode geschätzt und getestet werden.\n\n12. Sie können zwei verschachtelte logistische Regressionsmodelle mit einem Likelihood Ratio Test vergleichen mit $H_0$: Das reduzierte Modell stimmt.\n:::\n\n\n## Vorhersage von Diabetes {#sec-der-chi2-test}\n\nWir verwenden für dieses Kapitel einen Datensatz von Pima-Indianern. Dieser Datensatz stammt ursprünglich vom National Institute of Diabetes and Digestive and Kidney Diseases. Ziel ist es, auf Grundlage verschiedener Prädiktoren diagnostisch vorherzusagen, ob eine Patientin Diabetes hat oder nicht.\n\n-   Zu didaktischen Zwecken wurde der Datensatz vereinfacht (Entfernung aller Beobachtungseinheiten mit fehlenden Werten) bzw. werden nicht alle Variablen berücksichtigt.\n\n-   Die Variable `pregnant_bin` existiert im Originaldatensatz nicht, sie wurde zu didaktischen Zwecken aus der Variable `pregnant` erstellt (0 = Nein, \\>0 = Ja).\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n \n\nCode book zum Datensatz ($n$ = 392)\n\n|                |                                                      |\n|----------------|------------------------------------------------------|\n| **Variable**   | **Beschreibung**                                     |\n| `pregnant`     | Anzahl bisheriger Schwangerschaften                  |\n| `pregnant_bin` | Schon eine Schwangerschaft gehabt (0 = Nein, 1 = Ja) |\n| `glucose`      | Plasma-Glukose-Konzentration (mg/dl)                 |\n| `pressure`     | Diastolischer Blutdruck (mmHg)                       |\n| `triceps`      | Faltendicke beim Triceps (mm)                        |\n| `mass`         | Body Mass Index (kg/m\\^2)                            |\n| `pedigree`     | Diabetes Pedigree Funktion (PDF)                     |\n| `age`          | Alter (Jahre)                                        |\n| `diabetes`     | Diabetes (`neg`, `pos`)                  |\n \n \n\n\n-  Die abhängige Variable `diabetes` ist hier eine zweiwertige nominale Variable, $Y_i=\\{0,1\\}$. \n-  Bemerkung: Bei **gruppierten Daten** ist $Y_i$ manchmal die Anzahl Ereignisse in einer Gruppe $i$ mit $n_i$ Einheiten.\n\n\n\n\n## Warum keine lineare Regression? {#sec-warum-keine-lineare-regression}\n\nWenn die abhängige Variable binär ist (also nur die Werte 0 und 1 annehmen kann), ist es zwar möglich, eine lineare Regression durchzuführen – aber nicht empfehlenswert. Hier sind die Gründe:\n\n- Ungültige Vorhersagen: Die lineare Regression kann Werte ausserhalb des Bereichs [0, 1] vorhersagen, was bei Wahrscheinlichkeiten keinen Sinn ergibt.\n- Verletzung statistischer Annahmen: Die Fehlerterme sind bei binären Daten nicht normalverteilt und die Varianz ist nicht konstant (Heteroskedastizität).\n- Nicht optimale Schätzungen: Die lineare Regression liefert bei binären Daten oft verzerrte und ineffiziente Schätzwerte.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Lineares Modell für Diabetes](09_logistic_regression_files/figure-html/fig-plot-line-reg-bin-1.png){#fig-plot-line-reg-bin fig-align='center' width=480}\n:::\n:::\n\n\nIn @fig-plot-line-reg-bin sehen wir, dass Personen mit Diabetes (mit 1 kodiert) grundsätzlich höhere Blutzuckerwerte haben als Personen ohne Diabetes. Die Variable `glucose` scheint also hilfreich zu sein, um den Diabetesstatus, wenn auch nicht perfekt, vorherzusagen. Die graue Gerade ist das statistische Modell, der lineare Prädiktor. In der Grafik wird verdeutlicht, dass sich eine lineare Regression nicht eignet, um die Wahrscheinlichkeit für Diabetes vorherzusagen. Personen mit tiefer Blutzuckerkonzentration hätten eine negative Wahrscheinlichkeit, Diabetes zu haben. Personen mit einer Konzentration von $>220$ hätten eine Wahrscheinlichkeit $>1$ Diabetes zu haben. Eine Wahrscheinlichkeit muss aber per Definition im Intervall $[0; 1]$ liegen.\n\nDer Wertebereich der zu modellierenden abhängigen Variablen in einer linearen Regression ist in der Regel **nicht beschränkt** (theoretisch von $-\\infty$ bis $\\infty$), Wahrscheinlichkeiten aber sind durch 0 und 1 begrenzt. Wenn man statt der Wahrscheinlichkeit die Odds $O_i$ modelliert, dann erhält man Werte im Intervall $[0; \\infty)$. Wenn man zusätzlich noch den Logarithmus nimmt, also die $\\log Odds_i:=\\mathrm{logit}(\\pi_i)$ modelliert, dann erhält man Werte im Intervall $(-\\infty; \\infty)$, weil $\\log(0) = -\\infty$ und $\\log(\\infty) = \\infty$. $\\mathrm{logit}(\\pi)$ ist dann **nicht beschränkt**!\n\nDie folgende Grafik zeigt nun die lineare Regression für $\\mathrm{logit}(\\pi)$ auf Blutzucker:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Lineare Regression mit den log(Odds) für Diabetes als abhängige und Blutzucker als unabhängige Variable (n = 392).](09_logistic_regression_files/figure-html/fig-plot-line-reg-bin-log-1.png){#fig-plot-line-reg-bin-log fig-align='center' width=480}\n:::\n:::\n\n\nAuf den ersten Blick unterscheiden sich @fig-plot-line-reg-bin und @fig-plot-line-reg-bin-log kaum. Der einzige aber entscheidende Unterschied ist, dass die y-Achse dieses Mal die $\\mathrm{logit}(\\pi)$ für Diabetes repräsentiert. Wir erhalten durch Exponieren und Umrechnen die Wahrscheinlichkeit, dass bei einer gegebenen Blutzuckerkonzentration ein Diabetes vorliegt. Nehmen wir einen Blutzuckerwert von 170 (orange Linie). Für diesen Wert prognostiziert das Modell $\\mathrm{logit}(\\pi) = 1.116$. Somit sind die Odds für Diabetes bei einer Blutzuckerkonzentration von 170 $\\exp(1.116) = 3.0526$. Diese Odds können wir in eine Wahrscheinlichkeit umrechnen,\n\n$$\n\\hat{\\pi} = \\frac{\\hat{O}}{1+\\hat{O}} = \\frac{3.0526}{1+3.0526} = 0.7532.\n$$\n\nWiederholen Sie diese Rechnung für ein paar andere Blutzuckerwerte und Sie werden  merken, dass die Wahrscheinlichkeit immer zwischen 0 und 1 liegt (dazu muss man die $\\mathrm{logit}(\\pi_i)$ von Auge schätzen, weil wir ja die Regressionskoeffizienten noch nicht kennen).\n\nMit dem Computer kann man dies für alle beliebigen Blutzuckerwerte durchrechnen und eine neue Grafik mit den Blutzuckerwerten auf der x-Achse und der Wahrscheinlichkeit $\\pi$ für Diabetes auf der y-Achse erstellen:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Logistischer Zusammenhang zwischen Blutzucker und Wahrscheinlichkeit für Diabetes (n = 392).](09_logistic_regression_files/figure-html/fig-plot-log-reg-1.png){#fig-plot-log-reg fig-align='center' width=480}\n:::\n:::\n\n\nIn @fig-plot-log-reg sehen wir den logistischen (nicht linearen) Zusammenhang zwischen Blutzucker und der Wahrscheinlichkeit für Diabetes.  **Fazit:** Eine lineare Regression ist nicht optimal, um die Wahrscheinlichkeit für ein Ereignis zu modellieren.\n\n\n\n\n\n## Einfache logistische Regression\n\nDie **logistische Regression** ist ein Modell zur Analyse binärer abhängiger Variablen, bei denen die Zielgrösse typischerweise nur zwei Ausprägungen hat (z. B. Erfolg/Misserfolg). Anders als bei der linearen Regression wird hier nicht direkt der Erwartungswert der Zielvariable modelliert, sondern dessen **Transformation**.\n\n### Verteilung\n\nDie Verteilung der $Y_i$ ist binomial mit Parametern $\\pi_i$ und $n=1$ (Bernoulli-Verteilung). Wir notieren \n$$\nY_i\\sim \\mathcal{B}(n=1,\\pi_i)\n$$\n\nDie Binomialverteilung hat für den Spezialfall einer einzelnen Beobachtung (Bernoulli) die Wahrscheinlichkeitsmasse $p(y_i) = \\pi_i^{y_i} (1 - \\pi_i)^{1 - y_i}$, was äquivalent ist zur Aussage: $Y_i \\in \\{0,1\\}$ mit $\\pi_i = \\Pr(Y_i = 1)$ und $1-\\pi_i = \\Pr(Y_i = 0)$.\n\nAbbildung @fig-bernoulli zeigt Bernoulli-Verteilungen für verschiedene $\\pi$.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Bernoulli-Verteilung mit $\\pi=0.2,0.5,0.7$ und $\\pi=1$](09_logistic_regression_files/figure-html/fig-bernoulli-1.png){#fig-bernoulli fig-align='center' width=480}\n:::\n:::\n\n\n\n\n### Erwartungswert\n\nSei $X$ eine diskrete Zufallsvariable mit Werten $x_1,\n\\dots,x_k$ und Wahrscheinlichkeitsmasse $p(x)$. Der Erwartungswert von $X$ ist der Mittelwert der möglichen Werte, wobei jede Ausprägung entsprechend ihrer Wahrscheinlichkeit gewichtet wird.\n\n\\begin{equation}\n  \\label{eq:ExpDisc}\n  E(X) = \\sum_{i=1}^k x_i\\, p(x_i).\n\\end{equation}\n\nFür den Spezialfall $X \\sim \\mathcal{B}(1,\\pi)$ (Bernoulli-Verteilung mit Parameter $\\pi$) ergibt sich:\n$$\nE(X) = 0 \\cdot (1 - \\pi) + 1 \\cdot \\pi = \\pi\n$$\n\n\n### Link Funktion\n\n Der Erwartungswert einer binomialverteilten Variable $Y$ mit $n=1$ ist also $E(Y)=\\pi$.  \n \nDieser Erwartungswert (hier eine Wahrscheinlichkeit) soll nun so transformiert werden, dass er **nicht mehr beschränkt** ist, d.h. der lineare Prädiktor sollte dann alle Werte zwischen $-\\infty$ und $+\\infty$ annehmen können. Dazu müssen wir die **logit**- und die **logistische** Funktion einführen. Diese beiden Funktionen sind zentral für das Verständnis einer logistischen Regression.\n\n\n\n:::{.callout-note}\n## Logit und Logistische Funktion\n\n$$\\text{logit}(x):[0,1]\\rightarrow \\mathbb{R},\\quad x \\mapsto\n    \\log\\frac{x}{1-x}\n$$\n\n$$\\text{logistic}(x): \\mathbb{R} \\rightarrow [0,1],\\quad x \\mapsto\n    \\frac{\\exp(x)}{\\exp(x)+1}\n$$\n\nDie beiden wichtigen Funktionen sind in der Abbildung @fig-logitAndLogistic dargestellt.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Logit-Funktion und logistische Funktion](09_logistic_regression_files/figure-html/fig-logitAndLogistic-1.png){#fig-logitAndLogistic fig-align='center' width=768}\n:::\n:::\n\n\n:::\n\n\nDa der Erwartungswert $E(Y)=\\pi$ zwischen 0 und 1 liegt, wird dieser über die **logit-Funktion** transformiert:\n\n$$\n\\text{logit}(\\pi) = \\log\\left(\\frac{\\pi}{1 - \\pi}\\right) = \\eta\n$$\n\nSomit wird der **transformierte Erwartungswert** (der Logit von $\\pi$) als linearer Prädiktor $\\eta$ dargestellt. Man nennt diese Transformation **Link**-Funktion. Angewandt auf den Erwartungswert haben wir dann für den linearen Prädiktor\n\n\n$$\n\\mathrm{logit}\\, \\pi_i=\\log Odds_i=\\log\\frac{\\pi_i}{1-\\pi_i}=\\eta_i= \\beta_0 + \\beta_1x_i, \n$$\n\nund schreiben sehr oft kurz für eine einfache logistische Regression:\n\n:::{.callout-note}\n## Einfache logistische Regression\n\n$$\n\\boxed{\\mathrm{logit}(\\pi_i)=\\beta_0 + \\beta_1x_i}\n$$ {#eq-linPredLog}\n\n:::\n\n::: callout-note\n## Deterministischer und stochastischer Teil eines Modells\n(Lineare) Modelle beinhalten einen deterministischen Teil (der lineare Prädiktor) und einen stochastischen Teil (die Wahrscheinlichkeitsverteilung). In der logistischen Regression nehmen wir die Binomialverteilung (stochastischer Teil) in  @eq-linPredLog oft stillschweigend an und schreiben nur den linearen Prädiktor.\n:::\n\n\n\n\n###  Rückblick lineare Regression\n\nZum Vergleich noch einmal die einfache lineare Regression, das Modell war $$Y_i=\\beta_0 + \\beta_1x_i+\\epsilon_i$$ mit $\\epsilon_i\\sim \\mathcal{N}(\\mu,\\sigma^2)$. Dort war die Verteilung die Normalverteilung und die Link-Funktion  war die Identität (keine Transformation des Erwartungswerts nötig),\n\n$$\nY_i\\sim \\mathcal{N}(\\mu_i,\\sigma^2),\\quad  \\quad E(Y_i)=\\mu_i=\\beta_0 + \\beta_1x_i.\n$$ \n\n\n### Interpretation \n\nDer Parameter $\\beta_1$ in @eq-linPredLog ist zu interpretieren als der Unterschied in **Logits** für zwei Populationen, die sich auf $x$ um eine Einheit unterscheiden. Das ist analog zur linearen Regression, da die Logit-Skala ebenfalls ein Kontinuum darstellt. \nZusätzlich lässt sich $\\exp⁡(\\beta_1)$ als **Odds Ratio** interpretieren: Es gibt an, um welchen Faktor sich die Odds (also das Verhältnis von Erfolgs- zu Misserfolgswahrscheinlichkeit) verändern, wenn sich $x$ um eine Einheit erhöht. Ein Wert von $\\exp(\\beta_1)>1$ bedeutet, dass die Erfolgswahrscheinlichkeit mit steigendem $x$ zunimmt, während ein Wert kleiner als 1 auf eine abnehmende Erfolgswahrscheinlichkeit hinweist.\n\nFassen wir die Unterschiede zum linearen Modell nochmal zusammen:\n\n### Lineare vs. Logistische Regression\n\n\n| Model                                  | Lineare Regression                                    | Logistische Regression                                                                               |   |\n|----------------------------------------|-------------------------------------------------------|------------------------------------------------------------------------------------------------------|---|\n| **Verteilung der Zielvariable**        | Normalverteilung: $Y \\sim \\mathcal{N}(\\mu, \\sigma^2)$ | Bernoulli-Verteilung: $Y \\in \\{0,1\\},\\ \\pi = P(Y=1)$                                                 |   |\n| **Erwartungswert**                     | $E(Y) = \\mu$                                          | $E(Y) = \\pi$                                                                                         |   |\n| **Linearer Prädiktor**                 | $\\mu = \\beta_0 + \\beta_1 x$                           | $\\eta = \\beta_0 + \\beta_1 x$                                                                         |   |\n| **Transformation (Link-Funktion)**     | Identität: $\\mu = \\eta$                               | Logit: $\\text{logit}(\\pi) = \\log\\left(\\frac{\\pi}{1 - \\pi}\\right) = \\eta$                             |   |\n| **Interpretation von $\\beta_1$**       | Änderung des Erwartungswerts $E(Y)$ pro Einheit $x$   | Änderung der Log-Odds von $Y=1$ pro Einheit $x$                                                      |   |\n| **Interpretation von $\\exp(\\beta_1)$** | –                                                     | Multiplikativer Faktor für die Odds: $\\exp(\\beta_1)$ ist die Odds Ratio für eine Einheit mehr in $x$ |   |\n\n\n### Wahrscheinlichkeit\n\nDie Wahrscheinlichkeit für das Ereignis erhalten wir dann mit der Umkehrfunktion der $\\mathrm{logit}$-Funktion, der **logistischen** Funktion, die auf den linearen Prädiktor $\\eta_i=\\beta_0+\\beta_1x_i$ angewandt wird,\n\n$$\n\\boxed{\\pi_i=\\frac{O_i}{1+O_i}=\\frac{\\exp(\\mathrm{logit}(\\pi_i))}{1+\\exp(\\mathrm{logit}(\\pi_i))}=\\frac{\\exp(\\eta_i)}{1+\\exp(\\eta_i)}}.\n$${#eq-expit}\n\n\n\n\n\n\n\n### Dichotomer Prädiktor: Schwangerschaft und Diabetes\n\nWir verwenden weiterhin den Diabetes-Datensatz und untersuchen nun, ob es einen Zusammenhang gibt zwischen Diabetes und ob eine Frau bereits eine Schwangerschaft hatte oder nicht. Für dieses Beispiel lässt sich eine Vierfeldertabelle darstellen:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n        Diabetes\nPregnant neg pos\n     No   37  19\n     Yes 225 111\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nAnhand der Vierfeldertabelle kann man die Wahrscheinlichkeiten für das Ereignis und Nicht-Ereignis bei Kondition pregnant und not pregnant schätzen:\n\n\nDie geschätzten Wahrscheinlichkeiten sind\n\n$$\n\\hat{\\pi}_{pregnant} = \\frac{111}{111+225} = 0.3303571, \n$$\nund\n$$\n\\hat{\\pi}_{not.pregnant} = \\frac{19}{19+37} = 0.3392857\n$$\n\nDie geschätzten Odds sind\n$$\n\\hat{O}_{pregnant} = \\frac{111}{225} = 0.493,\n$$\n$$\n\\hat{O}_{not.pregnant} = \\frac{19}{37} = 0.514, \n$$\n\nund somit die geschätzte Odds Ratio\n$$\n\\widehat{OR} = \\frac{0.493}{0.514} = 0.96.\n$$\n\nWir schauen uns nun an, was die logistische Regression mit den gleichen Variablen für einen Output liefert. Für logistische Regressionen brauchen wir in `R` die Funktion `glm()`, was für **generalized linear models** steht. Weil diese Modelle eben **verallgemeinert** sind, muss man zusätzlich die **Verteilung** und die **Link-Funktion** angeben, welche gebraucht wird. Weil es in diesem Fall um eine binäre abhängige Variable geht, verwenden wir die Binomialverteilung. Wir tun das mit dem Argument `family = binomial(link=\"logit\")`. Der logit-link ist bei Binomialveteilung zwar defaultmässig eingestellt, `family = binomial()` würde auch genügen. Es ist aber immer besser, am Anfang beides explizit darzustellen. Die Syntax für die Erstellung der Modelle ist dann analog zur linearen Regression:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Einfache logistische Regression mit glm()\nm.glm1 <- glm(diabetes ~ pregnant_bin, data = diabetes, family = binomial(link=\"logit\")) \n```\n:::\n\n\nWir schauen das angepasste Modell an und konzentrieren uns auf die geschätzten Regressionskoeffizienten:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m.glm1)$coef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Estimate Std. Error    z value   Pr(>|z|)\n(Intercept)     -0.66647893  0.2822385 -2.3614032 0.01820593\npregnant_binYes -0.04009127  0.3051426 -0.1313853 0.89547049\n```\n\n\n:::\n:::\n\n\n$\\beta_0$ (das Intercept) steht für die $\\mathrm{logit}$ für Diabetes, wenn die unabhängige Variable den Wert 0 (oder die Referenzkategorie \"No\") annimmt. Wie bei der linearen Regression wird die Variable `pregnant_bin` mit 0 und 1 codiert (dummy coding). Also sind $\\hat{\\beta}_0$ die $\\mathrm{logit}$ für Diabetes, wenn eine Frau noch keine Schwangerschaft hatte. Wenn wir dies exponieren, dann erhalten wir 0.5135135. Wir können mit den Angaben aus der Vierfeldertabelle feststellen, dass dies korrekt ist. Mit der logistischen Funktion (@eq-expit) können wir die $\\pi_i$ für beide Gruppen abschätzen:\n\nWenn nun die Variable pregnant_bin den Wert \"No\" annimmt, haben wir:\n\n\n$$\n\\begin{aligned}\n\\mathrm{logit}(\\hat{\\pi})_{\\text{not pregnant}} &= \\hat{\\beta}_0 = -0.6664789 \\\\\n\\hat{O}_{\\text{not pregnant}} &= \\exp(\\hat{\\beta}_0) = 0.5135135 \\\\\n\\hat{\\pi}_{\\text{not pregnant}} &= \\frac{\\exp(\\hat{\\beta}_0)}{1 + \\exp(\\hat{\\beta}_0)} = 0.3392857\n\\end{aligned}\n$$\n\n\nWenn nun die Variable pregnant_bin den Wert \"Yes\" annimmt, haben wir:\n\n\n$$\n\\begin{aligned}\n\\mathrm{logit}(\\hat{\\pi})_{\\text{pregnant}} &= \\hat{\\beta}_0 + \\hat{\\beta}_1 = -0.7065702 \\\\\n\\hat{O}_{\\text{pregnant}} &= \\exp(\\hat{\\beta}_0 + \\hat{\\beta}_1) = 0.4933333 \\\\\n\\hat{\\pi}_{\\text{pregnant}} &= \\frac{\\exp(\\hat{\\beta}_0 + \\hat{\\beta}_1)}{1 + \\exp(\\hat{\\beta}_0 + \\hat{\\beta}_1)} = 0.3303571\n\\end{aligned}\n$$\n\n\n\nDies stimmt natürlich auch wieder überein mit den direkten Berechnungen in der Vierfeldertafel.\n\n\nMit der `predict()` Funktion können wir uns die geschätzten $\\mathrm{logit}$ und $\\pi$ direkt ausgeben lassen. Defaultmässig ist die Vorhersage auf dem linearen Prädiktor, mit Argument `type=\"response\"` bekommen wir  Wahrscheinlichkeits-Vorhersagen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredict(m.glm1,newdata=data.frame(pregnant_bin=c(\"No\",\"Yes\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         1          2 \n-0.6664789 -0.7065702 \n```\n\n\n:::\n\n```{.r .cell-code}\npredict(m.glm1,newdata=data.frame(pregnant_bin=c(\"No\",\"Yes\")),type=\"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2 \n0.3392857 0.3303571 \n```\n\n\n:::\n:::\n\n\nWas bedeutet nun $\\hat{\\beta}_1$? Im logistischen Modell ist die Steigung als $$\\beta_1=\\mathrm{logit}_{preg}-\\mathrm{logit}_{nonpreg}=\\log\\frac{O_{preg}}{O_{nonpreg}}=\\log(OR)$$ zu interpretieren. Somit ist $\\hat{\\beta}_1=-0.0400913$ der geschätzte Unterschied auf $\\mathrm{logit}$-Skala und $\\exp(\\hat{\\beta}_1)=\\exp(-0.0400913)=0.9607018$ die geschätzte Odds Ratio, was wiederum mit den Berechnungen auf Basis der Vierfeldertabelle übereinstimmt. \n\n\n\n\n### Intervallschätzung\n\nWie bei der linearen Regression können wir mit dem Befehl `confint()` die 95% Konfidenzintervalle der Regressionskoeffizienten abrufen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconfint(m.glm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     2.5 %     97.5 %\n(Intercept)     -1.2398480 -0.1261716\npregnant_binYes -0.6274561  0.5748354\n```\n\n\n:::\n:::\n\n\nDie Schranken sind hier auf $\\log(OR)$-Skala. Für eine inhaltlich sinnvolle Interpretation ist es daher oft empfehlenswert, die Grenzen des Intervalls zu exponieren, um Konfidenzintervalle für $OR$ zu erhalten.\n \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexp(confint(m.glm1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    2.5 %    97.5 %\n(Intercept)     0.2894282 0.8814635\npregnant_binYes 0.5339484 1.7768380\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\nWir sehen, dass das 95% Konfidenzintervall für das $OR$ von 0.5339484 bis 1.776838 geht. Wir können also zu 95% darauf vertrauen, dass das wahre $OR$ von diesem Intervall überdeckt wird. Da dieses Intervall stark mit dem Nullwert (welcher bei $OR=1$ oder $\\log(OR)=0$ liegt) überlappt, besteht keine Evidenz gegen $H_0$. Dies ist auch dem hohen P-Wert im Output zu entnehmen ($p=0.8954705$). Der diesbezügliche $z$-Test ist ein **Wald-Test**; diesen sowie die hier berechneten **Likelihood-Intervalle** führen wir in @sec-likelihood ein. \n\nEine Schwangerschaft scheint also die Odds für Diabetes nicht zu erhöhen. (Inhaltliche Anmerkung: Dies gilt nur für die Variable `pregnant_bin`, jedoch nicht für die Variable `pregnant`.)\n\n\nMit `parameters()` aus dem gleichnamigen Packet können wir uns direkt die exponierten Koeffizienten mit Intervallschätzung und Tests herausgeben lassen: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nparameters::parameters(m.glm1,exponentiate=TRUE,digits=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter          | Odds Ratio |    SE |         95% CI |      z |     p\n-------------------------------------------------------------------------\n(Intercept)        |      0.514 | 0.145 | [0.289, 0.881] | -2.361 | 0.018\npregnant bin [Yes] |      0.961 | 0.293 | [0.534, 1.777] | -0.131 | 0.895\n```\n\n\n:::\n:::\n\n\n\n### Exkurs: Risk Ratios versus Odds Ratios\n\nEine Einschränkung der logistischen Regression ist, dass die Effekte (log) Odds Ratios und nicht (log) Risk Ratios darstellen. Das ist dann problematisch, wenn ausdrücklich Risiko-Verhältnisse gewünscht werden, da sich Chancenverhältnisse von Risiko-Verhältnissen stark unterscheiden können, insbesondere wenn das Ereignis häufig ist. Bei seltenem Ereignis ist $OR$ eine gute Schätzung für das Risk Ratio. Eine Möglichkeit, Risk Ratios als Effekte zu erhalten, ist das **Log-Binomiale** Modell.\n\nIn diesem Modell wird jetzt der $\\log$ als Link-Funktion an Stelle von $\\mathrm{logit}$ gebraucht mit der Konsequenz, dass $\\beta_1$ ein $\\log$ Risk Ratio und $\\exp(\\beta_1)$ ein Risk Ratio darstellt.\n\nWie Sie aus @sec-inferenz-fuer-nominale-daten wissen, kann man obige 2x2 Tabelle mit Hilfe der `riskratio()` Funktion aus dem Paket `epitools` analysieren. Der Output sieht wie folgt aus (es wird nur ein Teil davon gezeigt):\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Diabetes\nPregnant neg pos\n     No   37  19\n     Yes 225 111\n```\n\n\n:::\n\n```{.r .cell-code}\nepitools::riskratio(tab,method=\"wald\")$measure\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        risk ratio with 95% C.I.\nPregnant  estimate     lower    upper\n     No  1.0000000        NA       NA\n     Yes 0.9736842 0.6553428 1.446664\n```\n\n\n:::\n:::\n\n\nDas Risk Ratio beträgt 0.974, mit einem 95% CI von \\[0.655; 1.447\\].\n\n`riskratio()` entspricht einem Log-Binomial Modell mit zweiwertigem Prädiktor:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.logBin<-glm(diabetes~pregnant_bin,family=binomial(link=\"log\"),data=diabetes)\nparameters::parameters(m.logBin,exponentiate=TRUE,ci_method=\"wald\",digits=3) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter          | Risk Ratio |    SE |         95% CI |      z |      p\n--------------------------------------------------------------------------\n(Intercept)        |      0.339 | 0.063 | [0.235, 0.489] | -5.796 | < .001\npregnant bin [Yes] |      0.974 | 0.197 | [0.655, 1.447] | -0.132 | 0.895 \n```\n\n\n:::\n:::\n\n\nDer $\\log$-Link hat aber den Nachteil, dass er Wahrscheinlichkeiten nur auf $\\mathcal{R^+}$ statt auf $\\mathcal{R}$ abbildet. Bei diesen Modellen gibt es oft Konvergenzprobleme, die sind bei Log-binomialen Modellen oft auf die Schwierigkeit zurückführen, die Wahrscheinlichkeiten im Bereich von [0, 1] zu halten, sowie auf die inhärente Komplexität der Likelihood-Oberfläche, insbesondere bei bestimmten Datenstrukturen. \n\nEin weitere Methode, um als Effektgrössen Risk Ratios zu bekommen, ist die **Robuste Poisson Regression**, auf die wir hier an dieses Stelle nicht eingehen. \n\n\n\n\n### Kontinuierlicher Prädiktor: Blutzucker und Diabetes\n\nWir greifen das Beispiel \"Blutzucker und Diabetes\" aus @sec-warum-keine-lineare-regression wieder auf. Anhand dieses neuen Beispiels wird gezeigt, wie eine einfache logistische Regression mit einer quantitativen Prädiktorvariable interpretiert wird. Das Modell kann nun geschrieben werden als\n\n$$\n\\mathrm{logit}(\\pi_i) = \\beta_0+\\beta_1 glucose_i.\n$$\n\n\nDa bei einer kontinuierlichen Eingangsgrösse eine Darstellung als Vierfeldertabelle nicht mehr möglich ist, passen wir direkt ein Modell an\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.glm2 <- glm(diabetes ~ glucose, data = diabetes, family = binomial())\n```\n:::\n\nund schauen uns die Punktschätzung, Standardfehler, Konfidenzintervall, $z$-Werte und $p$-Werte an. In die Theorie bezüglich Tests und Intervallschätzung in der logistischen Regression werden wir in @sec-likelihood eingehen.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m.glm2)$coef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate  Std. Error   z value     Pr(>|z|)\n(Intercept) -6.09552139 0.629787038 -9.678703 3.713993e-22\nglucose      0.04242099 0.004760623  8.910805 5.066328e-19\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(m.glm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %      97.5 %\n(Intercept) -7.38670938 -4.91195171\nglucose      0.03346065  0.05216953\n```\n\n\n:::\n:::\n\nvon Hand zusammengefasst,\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncbind(summary(m.glm2)$coef,confint(m.glm2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate  Std. Error   z value     Pr(>|z|)       2.5 %\n(Intercept) -6.09552139 0.629787038 -9.678703 3.713993e-22 -7.38670938\nglucose      0.04242099 0.004760623  8.910805 5.066328e-19  0.03346065\n                 97.5 %\n(Intercept) -4.91195171\nglucose      0.05216953\n```\n\n\n:::\n:::\n\noder einfacher mit `parameters()` auf $logit$-Skala:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nparameters::parameters(m.glm2,exponentiate=FALSE) ##Default\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter   | Log-Odds |       SE |         95% CI |     z |      p\n-------------------------------------------------------------------\n(Intercept) |    -6.10 |     0.63 | [-7.39, -4.91] | -9.68 | < .001\nglucose     |     0.04 | 4.76e-03 | [ 0.03,  0.05] |  8.91 | < .001\n```\n\n\n:::\n:::\n\n\nund auf $OR$-Skala:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nparameters::parameters(m.glm2,exponentiate=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter   | Odds Ratio |       SE |       95% CI |     z |      p\n-------------------------------------------------------------------\n(Intercept) |   2.25e-03 | 1.42e-03 | [0.00, 0.01] | -9.68 | < .001\nglucose     |       1.04 | 4.97e-03 | [1.03, 1.05] |  8.91 | < .001\n```\n\n\n:::\n:::\n\n\n$\\hat{\\beta}_0$ ist das geschätzte $\\mathrm{logit}$ für Diabetes, bei einem Blutzucker von 0 mg/dl. Es macht inhaltlich keinen Sinn, den Wert zu interpretieren. Daher sind wir auch nicht beeindruckt, dass sich dieser $\\mathrm{logit}$ statistisch signifikant von 0, bzw. die Odds statistisch signifikant von 1 unterscheiden. Meistens interessiert dieses Intercept (die Lage des Modells), nicht.\n\n$\\hat{\\beta}_1$ ist der geschätzte Effekt von Blutzucker auf Diabetes, also das $\\log(OR)$. Pro zusätzliches Milligramm Zucker pro Deziliter Blut steigt (das Vorzeichen ist positiv) das $\\mathrm{logit}$ für Diabetes um 0.042421. Anhand des sehr kleinen $p$--Wertes wissen wir bereits, dass es einen statistisch signifikanten Zusammenhang zwischen `glucose` und `diabetes` gibt. Das $OR$ von 1.0433336 unterscheidet sich also statistisch signifikant von 1. Diese Grösse ist der Effekt pro Milligramm Zucker pro Deziliter Blut. \n\nBei einem Unterschied von 10mg/dl beträgt das $OR$ also schon 1.528 (Versuchen Sie, dies aufgrund der Linearität nachzuvollziehen mit $\\exp(10x)=(\\exp(x))^{10})$.\n\n\n\n\n\n### Vorhersage\n\nAnhand der geschätzten Regressionskoeffizienten können wir nun die Regressionsgleichung benutzen, um die Odds für Diabetes bei einer bestimmten Blutzuckerkonzentration, z.B. 170 mg/dl, zu schätzen:\n\n$$\n\\mathrm{logit}(\\hat{\\pi})_{gluc=170} = -6.0955214 + 0.042421 \\times 170 = 1.1160464,\n$$\n\n$$\n\\hat{O}_{gluc=170} = \\exp(-6.0955214 + 0.042421 \\times 170) = 3.0527608,\n$$\n\nund somit\n\n$$\n\\hat{\\pi}_{gluc=170} = \\frac{\\exp(-6.0955214 + 0.042421 \\times 170)}{1+\\exp(-6.0955214 + 0.042421 \\times 170)} = 0.7532546\n$$\n\n\n\n\n\nEs handelt sich dabei genau um den Wert des Einführungsbeispiels aus @sec-warum-keine-lineare-regression:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Zusammenhang zwischen Blutzucker und Diabetes. Links die log(Odds), rechts die Wahrscheinlichkeit auf der y-Achse (n = 392).](09_logistic_regression_files/figure-html/fig-plot-log-reg-2-1.png){#fig-plot-log-reg-2 fig-align='center' width=480}\n:::\n:::\n\n\n\n\n\n\n\n## Multiple logistische Regression {#sec-multiple-logistische-regression}\n\nWie bei der linearen Regression, kann man auch bei einer logistischen Regression zusätzliche Prädiktorvariablen in das Model einfliessen lassen, um entweder \n\n* interessierende Effekte für **potentielle Confounder** zu kontrollieren \n* um ein **optimales Model** zu entwickeln.\n* Effekte **bedingt auf andere Eingangsgrössen** zu quantifizieren.\n\nFür $m$ unabhängige Variablen lautet das Modell (der lineare Prädiktor) dann\n\n$$\n\\boxed{\\mathrm{logit}(\\pi_i) = \\beta_0 + \\beta_1x_{i1}+\\dots+\\beta_m x_{im}.}\n$$\n\nDie wahren $\\beta$'s werden wie immer geschätzt anhand von Stichprobendaten (Auf die Schätzmethode werden weiter unten eingehen):\n\n$$\n\\mathrm{logit}(\\hat{\\pi}_i) = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i1}+\\dots+\\hat{\\beta}_m x_{im},\n$$\n\n$$\n\\hat{O_i} = \\exp(\\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i1}+\\dots+\\hat{\\beta}_m x_{im}),\n$$\n\nund folglich\n\n$$\n\\hat{\\pi}_i = \\frac{\\exp(\\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i1}+\\dots+\\hat{\\beta}_m x_{im})}{1+\\exp(\\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i1}+\\dots+\\hat{\\beta}_m x_{im})}. \n$$\n\nWir erstellen zuerst ein multiples Modell mit allen Prädiktoren und schauen uns den Output an:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Erstellen des multiplen logistischen Regressionsmodell\nm.glmF <- glm(diabetes ~ pregnant_bin + glucose + pressure +\n                triceps + insulin + mass + pedigree + age,\n              data = diabetes, family = binomial())\n\nround(summary(m.glmF)$coef,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate Std. Error z value Pr(>|z|)\n(Intercept)      -10.167      1.307  -7.776    0.000\npregnant_binYes    0.002      0.422   0.005    0.996\nglucose            0.038      0.006   6.603    0.000\npressure          -0.001      0.012  -0.091    0.927\ntriceps            0.012      0.017   0.680    0.496\ninsulin           -0.001      0.001  -0.710    0.478\nmass               0.067      0.028   2.409    0.016\npedigree           1.079      0.423   2.551    0.011\nage                0.052      0.015   3.506    0.000\n```\n\n\n:::\n:::\n\n\n\n\nMit Ausnahme vom Intercept ($\\mathrm{logit}$ für Diabetes, wenn alle Eingangsgrössen 0) sehen wir für jede der acht unabhängigen Variablen einen Effekt mit geschätztem $\\log(OR)$, Standardfehler, $z$-Statistik und $p$-Wert für den test der jeweiligen $H_0:\\beta_k=0, k=1,\\dots,8$. \n\nInteressieren wir uns beispielsweise für das $OR$ bzgl. `glucose`, kann der entsprechende Wert exponiert werden, was ein $OR$ von 1.0389345 ergibt. Pro zusätzliches Milligramm Zucker pro Deziliter Blut steigen (das Vorzeichen ist positiv) die Odds für Diabetes um diesen Faktor. Dies unter Berücksichtigung aller anderen Prädiktorvariablen, d.h. das ist der Effect von `glucuse`, der über den Effekt der anderen Eingangsgrössen im Modell hinausgeht. Beachten Sie, dass das OR für `glucose` im multiplen Modell verschieden ist als im einfachen Modell (1.039 vs. 1.043). Dies, weil im einfachen Modell der Effekt von `glucose` isoliert, im multiplen Modell jedoch unter Berücksichtigung aller anderen Variablen berechnet wird, für diese **kontrolliert** wird. Das Gleiche gilt für die Interpretation aller anderen Koeffizienten.\n\n\nMit `parameters()` aus dem Packet `parameters` kann man sich wieder -- alternativ -- mit `exponentiate=TRUE` direkt geschätzte $OR$, Standardfehler, 95\\% KI, $z$- und $p$-Wert herausgeben lassen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nparameters::parameters(m.glmF,exponentiate=TRUE,digits=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter          | Odds Ratio |        SE |         95% CI |      z |      p\n------------------------------------------------------------------------------\n(Intercept)        |  3.840e-05 | 5.021e-05 | [0.000, 0.000] | -7.776 | < .001\npregnant bin [Yes] |      1.002 |     0.423 | [0.445, 2.347] |  0.005 | 0.996 \nglucose            |      1.039 |     0.006 | [1.028, 1.051] |  6.603 | < .001\npressure           |      0.999 |     0.012 | [0.976, 1.023] | -0.091 | 0.927 \ntriceps            |      1.012 |     0.017 | [0.978, 1.046] |  0.680 | 0.496 \ninsulin            |      0.999 |     0.001 | [0.996, 1.002] | -0.710 | 0.478 \nmass               |      1.069 |     0.030 | [1.013, 1.130] |  2.409 | 0.016 \npedigree           |      2.941 |     1.243 | [1.307, 6.858] |  2.551 | 0.011 \nage                |      1.053 |     0.016 | [1.024, 1.085] |  3.506 | < .001\n```\n\n\n:::\n:::\n\n\n### Vorhersage\n\nWas ist die Wahrscheinlichkeit gemäss Modell für einen Diabetes für eine Frau mit den folgenden Werten?\n\n\n::: {#tbl-ex-mlr .cell layout-align=\"center\" tbl-cap='Was ist die Wahrscheinlichkeit, dass diese Frau Diabetes hat?'}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic\" style='font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> pregnant_bin </th>\n   <th style=\"text-align:right;\"> glucose </th>\n   <th style=\"text-align:right;\"> pressure </th>\n   <th style=\"text-align:right;\"> triceps </th>\n   <th style=\"text-align:right;\"> insulin </th>\n   <th style=\"text-align:right;\"> mass </th>\n   <th style=\"text-align:right;\"> pedigree </th>\n   <th style=\"text-align:right;\"> age </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Yes </td>\n   <td style=\"text-align:right;\"> 197 </td>\n   <td style=\"text-align:right;\"> 70 </td>\n   <td style=\"text-align:right;\"> 45 </td>\n   <td style=\"text-align:right;\"> 543 </td>\n   <td style=\"text-align:right;\"> 30.5 </td>\n   <td style=\"text-align:right;\"> 0.158 </td>\n   <td style=\"text-align:right;\"> 53 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nWir setzen als erstes die Koeffizienten sowie die Werte der jeweiligen Prädiktoren in die Regressionsgleichung ein, um den Wert des linearen Prädiktors zu berechnen:\n\n\n$$\n\\begin{aligned}\n\\mathrm{logit}(\\hat{\\pi}) =&\\;\n-10.1674594\n+ 0.0021074\n+ 0.0381956\\times 197 \\\\\n&+ -0.0010788\\times 70\n+ 0.0116816\\times 45\n+ -9.4250878\\times 10^{-4}\\times 543 \\\\\n&+ 0.0666242\\times 30.5\n+ 1.0786763\\times 0.158\n+ 0.052011\\times 53 \\\\\n=&\\; 2.2566111\n\\end{aligned}\n$$\n\n\n\nDurch Exponieren erhalten wir die Odds:\n\n$$\n\\hat{O} = \\exp(2.2566111) = 9.5506685\n$$\n\nDie Wahrscheinlichkeit ist schliesslich\n\n$$\n\\hat{\\pi} = \\frac{\\exp(2.2566111)}{1+\\exp(2.2566111)} = 0.9052193\n$$\n\n\n\nEine Frau mit den Werten aus @tbl-ex-mlr hat eine Wahrscheinlichkeit von 90.5% für einen Diabetes. Die Werte entsprechen denjenigen der 4. Person im Datensatz. Tatsächlich hat diese Person Diabetes.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic\" style='font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> pregnant_bin </th>\n   <th style=\"text-align:right;\"> glucose </th>\n   <th style=\"text-align:right;\"> pressure </th>\n   <th style=\"text-align:right;\"> triceps </th>\n   <th style=\"text-align:right;\"> insulin </th>\n   <th style=\"text-align:right;\"> mass </th>\n   <th style=\"text-align:right;\"> pedigree </th>\n   <th style=\"text-align:right;\"> age </th>\n   <th style=\"text-align:left;\"> diabetes </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Yes </td>\n   <td style=\"text-align:right;\"> 197 </td>\n   <td style=\"text-align:right;\"> 70 </td>\n   <td style=\"text-align:right;\"> 45 </td>\n   <td style=\"text-align:right;\"> 543 </td>\n   <td style=\"text-align:right;\"> 30.5 </td>\n   <td style=\"text-align:right;\"> 0.158 </td>\n   <td style=\"text-align:right;\"> 53 </td>\n   <td style=\"text-align:left;\"> pos </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nWenn man ein logistisches Modell in `R` rechnet, dann ist die Vorhersage bzgl. dem linearen Prädiktor und bzgl. der Wahrscheinlichkeit für das Ereignis für jede Person bereits hinterlegt. Mit `$linear.predictors` und `$fitted.values` können diese aufgerufen werden.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.glmF$linear.predictors[4] # Der lineare Prädiktor für die 4. Person\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       9 \n2.256611 \n```\n\n\n:::\n\n```{.r .cell-code}\nm.glmF$fitted.values[4] # Die Wahrscheinlichkeit von Diabetes für die  4. Person\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        9 \n0.9052193 \n```\n\n\n:::\n:::\n\n\nDie Wahrscheinlichkeit ist dann die logistische Funktion evaluiert beim Wert des linearen Prädiktors $\\eta$, \n\n$$\n\\hat{\\pi}_i=\\frac{\\exp(\\hat{\\eta}_i)}{1+\\exp(\\hat{\\eta}_i)},\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neta<-m.glmF$linear.predictor[4]\nexp(eta)/(1+exp(eta))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        9 \n0.9052193 \n```\n\n\n:::\n:::\n\n\nHinweis: die *9* im header kommt davon, dass die Person die ID *9* hat.\n\n\n\n<!-- Mit der `effects` package kann man einfach Modellvorhersagen visualisieren: -->\n<!-- ```{r fig.dim = c(9,7)} -->\n<!-- library(effects) -->\n<!-- plot(predictorEffects(m.glmF),axes=list(y=list(type=\"response\")),main=\"\") -->\n<!-- ``` -->\n\n\n\n\n\n\n## Exkurs: Schätzmethoden {#sec-recapLM}\n\nEs gibt drei grundlegende Methoden, um unbekannte Parameter (einer Verteilung) zu schätzen: \n\n * Methode der kleinsten Quadrate\n * Momentenmethode\n * Maximum Likelihood Methode \n \n Die erste haben wir im Rahmen der linearen Regression schon angetroffen, die zweite wird hier der Vollständigkeit halber aufgeführt, **die Maximum Likelihood Methode ist die häufigste und wichtigste Methode**.\n\nZiel dieses Abschnitts ist es, in das Prinzip der Methoden, insbesondere der dritten, der Maximum Likelihood Methode, einzutauchen. Wir wollen ein Gespür dafür entwickeln, wie man aus Daten Schätzer konstruiert. \n\n\n<!-- Es geht darum, dass der/die interessierte Leser:in das Prinzip der Schätzmethoden für Vertrauensintervalle und p-Werte bei der logistischen Regression (und später auch bei der Poisson Regression) nachvollziehen kann. Hier werden die Methoden an einem sehr einfachen Beispiel gezeigt. Es kann darum sein, dass Sei sich denken: \"warum so kompliziert, wenn es auch einfach geht\". Die \"einfache Situation\" wird hier gebraucht, damit man die komplexen Methoden besser nachvollziehen kann. Der Mehrwert der komplexen Methoden liegt aber darin, dass sie eben auch dann funktionieren, wenn die Situation nicht mehr einfach ist (z.B. bei multiplen logistischen Regressionsmodellen). -->\n\n\n\n\n### Methode der kleinsten Quadrate {#sec-LeastSquares}\n\nDiese Methode wurde bereits in der multiplen Regression angewandt. Da sie grundlegend ist, wollen wir sie hier kurz wiederholen. Wir fangen an mit einem grundlegenden Schätzproblem, das Schätzen eines wahren Durchschnitts $\\mu$. Der Kleinste-Quadrate-Schätzer (Least Squares, LS-Schätzer) von $\\mu$ ist der Wert, der die Fehler-Quadratsumme\n\n\n$$\n\\mathrm{SS}(\\mu)\n=\n\\sum_{i=1}^{n} (X_i - \\mu)^2\n$$\n\n\nminimiert. Aus der Schule erinnern wir uns: Gelöst werden solche Probleme in der Regel, indem man $ss(\\mu)$ nach $\\mu$ **ableitet und null setzt**,\n\n$$\n\\frac{\\text{d} ss}{\\text{d} \\mu}=-2(\\sum_{i=1}^nX_i-n\\mu)=0.\n$$ \n\nDaraus folgt für den Schätzer (Variable) und Schätzwert (Zahl):\n\n$$\n\\hat{\\mu}_{LS}=\\frac{\\sum_{i=1}^nX_i}{n}=\\bar{X}, \\qquad \\hat{\\mu}_{LS}=\\frac{\\sum_{i=1}^nx_i}{n}=\\bar{x}\n$$\n\nMan notiert beide, $\\bar{X}$ und $\\bar{x}$, mit $\\hat{\\mu}$. Aus dem Kontext wird meistens klar, ob mit $\\hat{\\mu}$ ein Schätzer oder ein Schätzwert gemeint ist. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nBeispiel: Seien die Daten einer Stichprobe aus $X$: $2.08, 3.41, 4.52, 1.7, 4.39, 4.06, 4.17, 6.23, 1.56, 6.53, 2.51, 1.74, 2.57, 4.51, 4.3, 3.38, 2.09, 2.7, 6.45, 4.4$ mit $\\bar{x}=3.665$. \n\nDer Schätzer von $\\mu$ mit minimaler Fehlerquadratsumme ist\n$\\hat{\\mu}_{LS}=\\bar{X}$ und der Schätzwert damit $3.665$. Es gibt keine andere Statistik (d.h. keine andere Grösse, die wir aus den Daten berechnen können), für die die Summe der Abweichungsquadrate $ss(\\mu)$ kleiner ist. \n\n\nAbbildung @fig-LS zeigt\ndie Summe der Abweichungsquadrate bei diesen Daten als Funktion von $\\mu$.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Summe der Abweichungsquadrate als Funktion von $\\mu$](09_logistic_regression_files/figure-html/fig-LS-1.png){#fig-LS fig-align='center' width=480}\n:::\n:::\n\n\nDiese Methode wird sehr häufig -- wie wir gesehen haben -- in der **linearen Regression** gebraucht. Dort hing der Erwartungswert $\\mathbb{E}(Y_i)=\\mu_i$ von gesuchten Parametern\nab, z.B. den Parametern $\\alpha$ und $\\beta$ in der einfachen\nlineare Regression ($Y_i=\\alpha+\\beta x_i+\\epsilon_i$) also\n$\\mathbb{E}(Y_i)=\\mu_i=\\alpha+\\beta x_i$. Minimiert wird hier die Summe der Fehlerquadrate\n\n$$\n\\sum_{i=1}^n\\hat{\\epsilon}_i^2=\\sum_{i=1}^n\n(Y_i-\\mu_i)^2=\\sum_{i=1}^n (Y_i-\\alpha-\\beta x_i)^2,\n$$ \n\num Schätzer $\\hat{\\alpha}$ und $\\hat{\\beta}$ für $\\alpha$ und $\\beta$ zu finden.\n\n\n\n### Momentenmethode\n\nWir möchten den Therapieerfolg einer neuen Behandlung schätzen und führen zu diesem Zweck die neue Behandlung an 100 Personen durch. Jede Person stellt dabei ein unabhängiges Bernoulli-Experiment dar, welches den Ausgang \"Erfolg\" oder \"Misserfolg\" haben kann. Man sagt auch, dass man dann $n$ Bernoulli Variablen $X_1,\\dots,X_n$ mit unbekanntem Paramteter $\\pi$ hat. Beobachtet wurden nun 37 Erfolge. Wir wollen jetzt einen Schätzer für $\\pi$.\n\nDas Moment der Ordnung $k$ von $X$ ist definiert als\n\n$$\nm_k:=\\mathbb{E}(X^k).\n$$\n\n\nDie Momentenmethode besteht darin, die $k$ Momente als Funktionen von $k$ unbekannten Parametern auszudrücken\n\n\n$$\n\\begin{aligned}\n\\mathbb{E}(X) &= g_1(\\theta_1, \\theta_2, \\dots, \\theta_k) \\\\\n\\mathbb{E}(X^2) &= g_2(\\theta_1, \\theta_2, \\dots, \\theta_k) \\\\\n&\\vdots \\\\\n\\mathbb{E}(X^k) &= g_k(\\theta_1, \\theta_2, \\dots, \\theta_k)\n\\end{aligned}\n$$\n\n\nDiese $k$ Gleichungen werden dann nach den $k$ Parametern aufgelöst. Solche Probleme kennen wir vielleicht noch aus der Schulzeit. Hier haben wir nur einen unbekannten Parameter, $\\pi$, brauchen also nur das erste Moment\n\n$$\nE(X)=g(\\pi)\n$$\n\nDer Erwartungswert einer $\\mathcal{B}(\\pi,1)$ verteilten Variablen ist bekannterweise schon das erste Moment, also haben wir \n\n$$g(\\pi)=\\pi.$$\n\nWir ersetzen nun das theoretische Moment durch das Stichprobenmoment. Der Schätzer und Schätzwert sind dann\n\n$$\n\\hat{\\pi}_{MM}=\\frac{1}{n}\\sum_{i=1}^n X_i, \\qquad \\hat{\\pi}_{MM}=\\frac{1}{n}\\sum_{i=1}^n x_i=\\frac{37}{100}\n$$\n\nDie geschätzte Wahrscheinlichkeit (Punktschätzung), dass die Therapie erfolgreich ist, ist gemäss der Momentenmethode  0.37. Wir wissen  bereits, dass bei Wiederholung der Studie die neue Schätzung aufgrund leicht anderer Beobachtungen nicht zwingend wieder 37% ergeben wird (Stichprobenvariation). Der Schätzer hat ja selber eine Verteilung, über die man dann Konfidenzintervalle konstruieren kann (siehe @sec-proportionen). Eine Methode zur Konstruktion von Konfidenzintervallen werden wir bei der Maximum Likelihood Methode sehen.\n\n\n\n\n\n### Maximum Likelihood Methode {#sec-maxLik}\n\n\nEine wichtige Grösse – für viele sogar die fundamentalste Grösse in der Statistik – ist die **Likelihood**. Die Maximum-Likelihood-Methode (ML) ist die wichtigste Methode zur Schätzung unbekannter Modellparameter aus Daten. Sie erfordert jedoch Kenntnisse über die Verteilung der Daten.\n\n<!-- Betrachten wir $X_i$ als unabhängig und identisch verteilt (i.i.d.) gemäß einer Verteilung, z.B. binomial, $f(x_i) = \\mathcal{B}(\\pi, n)$ (mit bekanntem $n$), Das Ziel ist es, den Parameter $\\pi$ zu schätzen. -->\n\n\n\n#### Likelihood-Funktion\n\nDie Wahrscheinlichkeitsdichte (oder -masse) $p(x;\\theta)$ beschreibt die Verteilung der Variable $X$ für fixierten Parameter $\\theta$. Das Ziel ist nun die Inferenz bezüglich $\\theta$ bei vorliegenden Daten $x$. Im obigen Beispiel war das die Inferenz bezüglich $\\pi$ bei vorliegenden $x=37$ aus $n=100$.\n\nEine zentrale Rolle spielt nun die **Likelihood-Funktion** \n\n$$\n\\boxed{L(\\theta;x)=p(x;\\theta)}\n$$\n\ngesehen als **Funktion von $\\theta$ bei vorliegendem $x$**. Wir schreiben dafür in der Folge nur noch kurz $L(\\theta)$.\n\nDie Likelihood-Funktion für einen Binomialparameter $\\pi$ bei vorliegenden Daten $x=37$ und $n=100$ kann man berechnen mit `dbinom()`. Dabei wird für jedes mögliche $\\pi \\in [0,1]$ die Wahrscheinlichkeit $p(x)$ berechnet und vertikal aufgetragen. \n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwk<-seq(0,1,.001)##Kandidaten für pi\nL<-dbinom(x=37,size=100,prob=wk)##Likelihood von pi (als Funktion von pi!)\nplot(wk,L,type=\"l\",xlab=expression(pi),ylab=expression(L(pi)))\n```\n\n::: {.cell-output-display}\n![](09_logistic_regression_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n::: callout-important\n## Likelihood-Funktion versus Wahrscheinlichkeitsverteilung\nDie Likelihood-Funktion ist keine Wahrscheinlichkeitsverteilung, die Fläche unter $L(\\pi)\\neq 1$. Sie ist eine Funktion von $\\pi$ und nicht eine Funktion von $x$.\n:::\n\n\nDie Maximum-Likelihood-Schätzung (MLE) $\\hat{\\theta}_{ML}$ eines Parameters $\\theta$ wird durch Maximierung der Likelhood-Funktion erreicht:\n\n**Likelihood**: Für unabhängige Daten ($X_1,\\dots,X_n$) ist die Likelihood von $\\theta$, d.h. die Wahrscheinlichkeitsdichte (oder -masse) der Daten gegeben $\\theta$, gleich dem Produkt der $n$ Wahrscheinlichkeitsdichten (oder -massen) $p(x_i)$, wobei $p(x_i)$ die Dichten (oder Massen) sind,\n\n\\begin{equation} \nL(\\theta)=\\prod_{i=1}^n p(x_i). \n\\end{equation}\n\n**Log-Likelihood**: Aus numerischen Gründen wird dann meistens die Log-Likelihood $l(\\theta)$ verwendet. Aus einem Produkt von Likelihoods wird dann eine Summe von Log-Likelihoods, was numerisch leichter zu handhaben ist,\n\n\n\\begin{equation} \nl(\\theta)=\\log L(\\theta)=\\sum_{i=1}^n \\log p(x_i). \n\\end{equation}\n\n\n**Relative Likelihood und relative Log-Likelihood**: Es ist oft nützlich, die Likelihood- oder Log-Likelihood relativ zu ihrem Wert beim MLE zu betrachten. Die relative Likelihood ist\n\n\\begin{equation} \n\\tilde{L}(\\theta)=\\frac{L(\\theta)}{L(\\hat{\\theta}_{ML})}\n\\end{equation}\n\nFolgende Schwellen werden of gebraucht bezüglich Plausibilität von $\\theta$\n\n\n$$\n\\begin{aligned}\n1 &\\ge \\tilde{L}(\\theta) > \\frac{1}{3} &\\quad& \\theta &\\text{ very plausible} \\\\\n\\frac{1}{3} &\\ge \\tilde{L}(\\theta) > \\frac{1}{10} &\\quad& \\theta &\\text{ plausible} \\\\\n\\frac{1}{10} &\\ge \\tilde{L}(\\theta) > \\frac{1}{100} &\\quad& \\theta &\\text{ less plausible} \\\\\n\\frac{1}{100} &\\ge \\tilde{L}(\\theta) > \\frac{1}{1000} &\\quad& \\theta &\\text{ barely plausible} \\\\\n\\frac{1}{1000} &\\ge \\tilde{L}(\\theta) > 0 &\\quad& \\theta &\\text{ not plausible}\n\\end{aligned}\n$$\n\n\n\nDie relative Log-Likelhood ist dann\n\n\n$$\n\\tilde{l}(\\theta)\n=\nl(\\theta) - l(\\hat{\\theta}_{\\mathrm{ML}})\n=\n\\log\\!\\left(\n\\frac{L(\\theta)}{L(\\hat{\\theta}_{\\mathrm{ML}})}\n\\right)\n$$\n\n\nDabei gilt $-\\infty <\\tilde{l}(\\theta)\\leq 0$ und $\\tilde{l}(\\hat{\\theta}_{ML})=0$.\n\n\n@fig-binlik zeigt die verschiedenen Arten der Likelihood für unser Binomialmodell bei vorliegenden Daten $n = 100$ und $x = 37$. Der Maximum-Likelihood-Schätzer ist gut ablesbar als $\\hat{\\pi}_{ML}=0.37$. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Likelihood-Funktion für das Binomialmodel mit n = 100 and x = 37](09_logistic_regression_files/figure-html/fig-binlik-1.png){#fig-binlik fig-align='center' width=768}\n:::\n:::\n\n\n#### Score und Information\n\nDie **erste Ableitung** der Log-Likelihood-Funktion wird als **Score**-Funktion bezeichnet,\n\n$$\nS(\\theta)=\\frac{dl(\\theta)}{d\\theta}.\n$$\n\nDie Berechnung des Maximum-Likelihood-Schätzers (MLE) erfolgt typischerweise durch das Lösen der Score-Gleichung $S(\\theta) = 0$.\n\nDie **negative zweite Ableitung** der Log-Likelihood-Funktion (die negative Krümmung, die misst, wie schnell eine Kurve an einem bestimmten Punkt ihre Richtung ändert), wird als **Fisher-Information** bezeichnet,\n\n$$\nI(\\theta)=-\\frac{d^2 l(\\theta)}{d\\theta^2}=-\\frac{dS(\\theta)}{d\\theta}.\n$$\n\n\n\n\n\n\n#### Beispiel: Binomial model\n\nUnter Binomialverteilung haben wir (für die Interessierten):\n\n* $L(\\pi)={n \\choose x}\\pi^x(1-\\pi)^{n-x}$\n\n* $l(\\pi)=x \\log(\\pi)+(n-x) \\log(1-\\pi)$\n\n* $S(\\pi)=\\frac{x}{\\pi}-\\frac{n-x}{1-\\pi}$\n\n* $\\hat{\\pi}_{ML}=\\frac{x}{n}$\n\n* $I(\\pi)=\\frac{x}{\\pi^2}+\\frac{n-x}{(1-\\pi)^2}$\n\n\n\n\n\n#### Varianz des MLE als Inverse der Fisher-Information\n\n\nDie Fisher Information evaluiert am MLE $\\hat{\\pi}_{ML}$ ist \n\n$$\nI(\\hat{\\pi}_{ML})=\\frac{n}{\\hat{\\pi}_{ML}(1-\\hat{\\pi}_{ML})}\n$$\n\n\nMan kann zeigen, dass die Varianz  $\\mathrm{Var}(\\hat{\\pi}_{ML})$ approximativ dem Kehrwert der Fisher-Information entspricht. Je grösser die Information, umso kleiner die Varianz und umgekehrt. Das macht auch intuitiv Sinn.\n\n$$\n\\mathrm{Var}(\\hat{\\pi}_{ML})=\\frac{1}{I(\\hat{\\pi}_{ML})} \n$$\n\nDamit haben wir einen Standardfehler für den MLE\n\n$$\nSE(\\hat{\\pi}_{ML})=\\sqrt{\\frac{1}{I(\\hat{\\pi}_{ML})}}=\\sqrt{\\frac{\\hat{\\pi}_{ML}(1-\\hat{\\pi}_{ML})}{n}}.\n$$\n\n\n\n\n\n#### Quadratische Approximation\n\n\n::: callout-important\n## Quadratische Approximation der Log-Likelihood\n\nDie quadratische Approximation an die relative Log-Likelihood ist\n\n\n$$\n\\tilde{l}(\\theta)\n=\nl(\\theta) - l(\\hat{\\theta}_{\\mathrm{ML}})\n\\approx\n- \\frac{1}{2}\nI(\\hat{\\theta}_{\\mathrm{ML}})\n(\\theta - \\hat{\\theta}_{\\mathrm{ML}})^2\n$$\n\n:::\n\n\n\n::: {.proof} \n(Für die Interessierten!) Die Taylor Approximation zweiten Grades entwickelt um MLE ist:\n\n$$\n\\begin{aligned}\nl(\\theta)\n&\\approx\nl(\\hat{\\theta}_{\\mathrm{ML}})\n+ \\frac{d l(\\hat{\\theta}_{\\mathrm{ML}})}{d \\theta} (\\theta - \\hat{\\theta}_{\\mathrm{ML}})\n+ \\frac{1}{2} \\frac{d^2 l(\\hat{\\theta}_{\\mathrm{ML}})}{d \\theta^2} (\\theta - \\hat{\\theta}_{\\mathrm{ML}})^2 \\\\[6pt]\n&=\nl(\\hat{\\theta}_{\\mathrm{ML}})\n+ S(\\hat{\\theta}_{\\mathrm{ML}}) (\\theta - \\hat{\\theta}_{\\mathrm{ML}})\n- \\frac{1}{2} I(\\hat{\\theta}_{\\mathrm{ML}}) (\\theta - \\hat{\\theta}_{\\mathrm{ML}})^2 \\\\[6pt]\n&=\nl(\\hat{\\theta}_{\\mathrm{ML}})\n+ 0\n- \\frac{1}{2} I(\\hat{\\theta}_{\\mathrm{ML}}) (\\theta - \\hat{\\theta}_{\\mathrm{ML}})^2 \\\\[6pt]\n&=\nl(\\hat{\\theta}_{\\mathrm{ML}})\n- \\frac{1}{2} I(\\hat{\\theta}_{\\mathrm{ML}}) (\\theta - \\hat{\\theta}_{\\mathrm{ML}})^2\n\\end{aligned}\n$$\n\n:::\n\n\n\nBeispiel. Für $I(\\hat{\\theta}_{ML})=10$ und $\\hat{\\theta}_{ML}=5$, haben wir $y=-0.5\\times 10(x-5)^2$. Dies ist eine einfache quadratische Funktion von $\\theta$ zentriert um $\\hat{\\theta}_{ML}=5$ mit negativer Krümmung $I(\\hat{\\theta}_{ML})=10$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_logistic_regression_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n\nWir brauchen nun obiges Resultat, dass die Varianz vom MLE der Kehrwert der Information ist, \n\n$$\n\\mathrm{Var}(\\hat{\\theta}_{ML})=1/I(\\hat{\\theta}_{ML}),\n$$ \nund können die relative Log-Likelihood schreiben als\n\n\n::: callout-important\n## Quadratische Approximation der Log-Likelihood\n\n$$\n\\large\n\\tilde{l}(\\theta)\\approx -\\frac{1}{2}\\left(\\frac{\\hat{\\theta}_{ML}-\\theta}{SE(\\hat{\\theta}_{ML})}\\right)^2\n$$\n\n:::\n\n\n**Normalverteilung und quadratische Approximation**: \nBei Normalverteilung mit bekanntem $\\sigma^2$ haben wir\n\n* $L(\\mu)=\\prod_{i=1}^n\\frac{1}{\\sqrt{2\\pi\\sigma^2}} \n    \\exp\\left(-\\frac{(x-\\mu)^2}{2\\sigma^2}\\right)$\n* $l(\\mu)=-\\frac{1}{2\\sigma^2}\\sum_{i=1}^n(x_i-\\mu)^2$\n* $S(\\mu)=\\frac{1}{\\sigma^2}\\sum_{i=1}^n(x_i-\\mu)$\n* $\\hat{\\mu}_{ML}=\\bar{x}$\n* $I(\\mu)=\\frac{n}{\\sigma^2}$\n\nWir haben dann für die relative Log-Likelihood:\n\n\n$$\n\\begin{aligned}\n\\tilde{l}(\\mu)\n&=\nl(\\mu) - l(\\hat{\\mu}) \\\\\n&=\n- \\frac{1}{2\\sigma^2}\n\\left[\n\\sum_{i=1}^{n} (x_i - \\mu)^2\n-\n\\sum_{i=1}^{n} (x_i - \\hat{\\mu})^2\n\\right] \\\\[6pt]\n&=\n- \\frac{1}{2} \\frac{n}{\\sigma^2} (\\hat{\\mu} - \\mu)^2 \\\\[6pt]\n&=\n- \\frac{1}{2}\n\\left(\n\\frac{\\hat{\\mu} - \\mu}{\\sigma / \\sqrt{n}}\n\\right)^2\n\\end{aligned}\n$$\n\n\n\n**Die Approximation ist also bei Normalverteilung exakt**! \n\nWir sehen, dass die Log-Likelihood bei Normalverteilung eine quadratische Funktion ist und dass die Information (negative Krümmung) und damit die Varianz nicht von $\\mu$ abhängt (homogene Varianz).\n\n::: callout-important\n## Normalverteilung und quadratische Approximation\n\nDie quadratische Approximation der Log-Likelihood ist bei Normalverteilung **exakt**! Das bedeutet:\n\n- Normalverteilung impliziert quadratische Log-Likelihood\n- Eine quadratische Approximation der Log-Likelihood impliziert approximative Normalverteilung\n\n:::\n\n<!-- $ -->\n<!-- p(x)=\\frac{1}{\\sqrt{2\\pi}\\sigma}\\exp\\left(-\\frac{1}{2}\\frac{(x-\\mu)^2}{\\sigma^2}\\right) -->\n<!-- $$ -->\n\n<!-- i.e., $\\hat{\\mu}_{ML} = \\frac{\\sum{i=1}^n X_i}{n} = \\bar{x}$. -->\n\n\n \n<!-- ```{r normalLik} -->\n<!-- normalLikDemo<-function(x=rnorm(100),sigma=1,approx=FALSE) -->\n<!-- { -->\n<!--     mle<-mean(x) -->\n<!--     n<-length(x) -->\n<!--     info<-n/sigma^2 -->\n<!--     se<-sqrt(1/info) -->\n<!--     mu<-seq(mle-1,mle+1,.01) -->\n<!--     L<-dnorm(x=mean(x),mean=mu,sd=se) -->\n<!--     Lrel<-L/max(L) -->\n<!--     l<-log(Lrel) -->\n<!--     par(mfrow=c(2,2)) -->\n<!--     plot(mu,L,type=\"l\") -->\n<!--     abline(v=mle,lty=2) -->\n<!--     plot(mu,Lrel,type=\"l\") -->\n<!--     abline(v=mle,lty=2) -->\n<!--     plot(mu,l,type=\"l\") -->\n<!--     abline(v=mle,lty=2) -->\n<!--     ci<-confint(glm(x~1,family=\"gaussian\")) -->\n<!--     plotrix::ablineclip(h=-1.96,x1=mle-1.96*se,x2=mle+1.96*se,lty=1,col=\"red\") -->\n<!--     if (approx==TRUE) -->\n<!--     { -->\n<!--     plot(mu,l,type=\"l\") -->\n<!--     abline(v=mle,lty=2) -->\n<!--     lines(mu,-0.5*((mu-mle)/(se))^2,col=\"red\") -->\n<!--     } -->\n<!-- } -->\n<!-- normalLikDemo(approx=TRUE) -->\n<!-- ``` -->\n\n\n\nDie Vorteile der quadratischen Approximation der relativen Log-Likelihood liegen darin, dass wir **nur den MLE und die beobachtete Fisher-Information** kennen müssen, unabhängig davon, wie die tatsächliche Log-Likelihood aussieht.\n\n\n\n\n### Likelihood Inferenz {#sec-likelihood}\n\nWir betrachten nun Statistiken, mit denen wir Hypothesen testen können. Aus der Likelihood-Theorie kann man die asymptotische Verteilung von drei Statistiken ableiten, um Hypothesen der Form\n\n\n$$\nH_0: \\theta=\\theta_0\n$$\n\nzu testen und Konfidenzintervalle für $\\theta$ zu konstruieren:\n\nWir wollen diese drei Statistiken und deren Verteilung unter der $H_0$ jetzt aufführen (ohne Herleitung)\n\n\n* **Wald-Statistik**\n* **Score-Statistik**\n* **Likelihood-Ratio Statistik**\n\n\n#### Wald Tests\n\n::: callout-important \n## Wald-Statistik\n\n\n$$\n\\frac{\\hat{\\theta}_{\\mathrm{ML}} - \\theta_0}{\\mathrm{SE}(\\hat{\\theta}_{\\mathrm{ML}})}\n\\;\\overset{\\mathrm{a}}{\\sim}\\;\n\\mathcal{N}(0, 1)\n$$\n\n\n:::\n\n\nTests einzelner Koeffizienten, die auf der approximativen Normalverteilung basieren, werden als **Wald**-Tests bezeichnet, wobei eine grobe Annahme über die Form der Likelihood getroffen wird. Tests im Output von logistischen Regressionen sind Beispiele für Wald Tests.\n\nDurch das Invertieren von Tests können wir Konfidenzintervalle konstruieren:\n\nDie Menge\n\n$$\n\\left(\\theta: z_{\\alpha/2}\\leq \\frac{\\hat{\\theta}_{ML}-\\theta}{SE(\\hat{\\theta}_{ML})} \\leq z_{1-\\alpha/2}\\right)\n$$\n\nführt nicht zu einer Verwerfung von $H_0: \\theta=\\theta_0$. Diese Werte bilden also ein approximates $(1-\\alpha)\\times 100$ **Wald Konfidenzintervall** für $\\theta$. Das ist dann äquivalent zur bereits bekannten Formel\n\n$$\n\\boxed{\\hat{\\theta}_{ML}\\pm z_{1-\\alpha/2} SE(\\hat{\\theta}_{ML})}.\n$$\n\n\n#### Likelihood Ratio Tests{#sec-likelihood-ratio-tests}\n\nEine sehr wichtige Statistik ist die **Likelihood-Ratio-Statistik**, diese führt zum Likelihood-Ratio-Test. Der Likelihood-Ratio-Test ein Hypothesentest, bei dem die Güte der Anpassung zweier konkurrierender statistischer Modelle verglichen wird. Typischerweise wird dabei ein Modell betrachtet, das durch **Maximierung über den gesamten Parameterraum** gefunden wird, und ein weiteres, das nach der **Auferlegung einer Einschränkung** bestimmt wird. \n\nDieser Test basiert auf dem Verhältnis ihrer Likelihoods. Wenn das stärker eingeschränkte Modell (d.h. die Nullhypothese) durch die beobachteten Daten gestützt wird, sollten sich die beiden Likelihoods nicht stärker unterscheiden als es durch Stichprobenfehler erklärbar wäre. \n\nDer Likelihood-Ratio-Test prüft also, ob dieses Verhältnis signifikant von Eins abweicht, oder äquivalent dazu, ob sein natürlicher Logarithmus signifikant von Null abweicht.\n\n\nLikelihood-Ratio-Tests verwenden die Likelihood, wie sie ist. Daher sind LR-Tests in der Regel den Wald-Tests überlegen. Sie sind asymptotisch aber äquivalent. \n\nUnter der Nullhypothese ist die Likelihood-Ratio-Statistik ist $\\chi^2$-verteilt mit **einem Freiheitsgrad** (wenn nur ein Parameter geschätzt wird). Die $\\chi^2$-Verteilung haben wir in @sec-der-chi2-test bereits kennengelernt:\n\n\n\n::: callout-important \n## Likelihood-Ratio Statistik\n\n$$\n\\Large\n-2 \\tilde{l}(\\theta_0)=-2(l(\\theta_0)-l(\\hat{\\theta}_{ML}))\\overset{a}\\sim \\chi^2(1).\n$$\n\n:::\n\n\n**Beispiel Binomialverteilung**: Wir testen \n\n$$H_0: \\pi=0.2$$\n\n\nmit den Daten $x=37$ und $n=100$. Die Log-Likelihood beim MLE $\\hat{\\pi}=0.37$ ist -2.4961214. Die Log-Likelihood bei  $\\pi_0=0.2$ ist -10.2077998. Die Likelihood-Ratio Statistik ist dann\n\n$$\nLR=-2(l(\\pi_0)-l(\\hat{\\pi}_{ML}))=\n15.4233568\n$$\n\nund die Wahrscheinlichkeit für $LR>15.4233568$ ist kleiner als 5\\%:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nllMLE<-dbinom(x=37,size=100,prob=0.37,log=TRUE)\nll0<-dbinom(x=37,size=100,prob=0.20,log=TRUE)\nLR<- -2*(ll0-llMLE)\np<-1-pchisq(LR,1)\nround(c(llMLE=llMLE,ll0=ll0,LR=LR,p=p),4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   llMLE      ll0       LR        p \n -2.4961 -10.2078  15.4234   0.0001 \n```\n\n\n:::\n:::\n\n\nWir haben somit Evidenz gegen $H_0$.\n\n\nDie Menge \n\n$$\n\\left(\\pi:\\tilde{l}(\\pi)\\geq -\\frac{1}{2}\\chi^2_{1-\\alpha}(1)\\right)\n$$\n\nbildet ein approximates $(1-\\alpha)\\times 100$ percent **Likelihood-Ratio Konfidenzintervall** für $\\pi$. Für ein 95\\% Konfidenzintervall ist das die Menge $\\left(\\pi:\\tilde{l}(\\pi)\\geq -1.9207294 \\right)$. In unserem Beispiel wäre dies \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npi<-seq(0,1,by=.0001)\nl<-dbinom(x=37,size=100,prob=pi,log=TRUE)\nrl<-l-max(l)\nrange(pi[-2*rl < qchisq(0.95,1)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2796 0.4670\n```\n\n\n:::\n:::\n\n\n\n\n\n#### Score Tests\n\n::: callout-important \n\n##  Score-Statistik\n\n$$\n\\Large \n\\frac{S(\\theta_0)}{\\sqrt{I(\\theta_0)}}\\overset{a}\\sim \\mathcal{N}(0,1)\n$$\n:::\n\n\nAuf die Score-Tests und diesbezüglich Intervallschätzungen gehen wir hier nicht näher direkt ein. Für den Score-Test muss nur die Likelihood bei $\\theta=\\theta_0$ berechnet werden. Der Score ist ja die Steigung der Likelhood. Je grösser die Steigung der Likelhood bei $\\theta_0$, umso extremer ist die Statistik. Beim MLE ist der Score Null.  Wir haben  in @sec-berechnungen-von-proportionen-mit-r  `prop.test()` für Tests von Proportionen gesehen, das war ein Beispiel für einen Score-Test. \n\n\n#### Zusammenfassung\n\n\nDie drei klassischen Tests für die Hypothese $H_0: \\theta = \\theta_0$ basieren auf unterschiedlichen Prinzipien, sind aber asymptotisch äquivalent:\n\n- **Wald-Test**: basiert auf der Schätzung $\\hat{\\theta}_{ML}$ und deren Standardfehler.\n- **Score-Test**: verwendet die Ableitung der Log-Likelihood an der Nullhypothese.\n- **Likelihood-Ratio-Test**: vergleicht die Likelihood unter $H_0$ und unter der Maximum-Likelihood-Schätzung.\n\n| Test                     | Teststatistik                                                                 |\n|-------------------------|-------------------------------------------------------------------------------|\n| **Wald-Test**          | $W = \\dfrac{\\hat{\\theta}_{ML} - \\theta_0}{SE(\\hat{\\theta}_{ML})} \\overset{a}{\\sim} \\mathcal{N}(0,1)$ |\n| **Score-Test**         | $Z_S = \\dfrac{S(\\theta_0)}{\\sqrt{I(\\theta_0)}} \\overset{a}{\\sim} \\mathcal{N}(0,1)$       |\n| **Likelihood-Ratio-Test** | $LR = -2 \\log \\left( \\dfrac{L(\\theta_0)}{L(\\hat{\\theta}_{ML})} \\right) \\overset{a}{\\sim} \\chi^2(1)$ |\n\nNotation:\n\n- $\\hat{\\theta}_{ML}$: Maximum-Likelihood-Schätzer\n- $SE(\\hat{\\theta}_{ML})$: Standardfehler des Schätzers\n- $S(\\theta_0)$: Score-Funktion (erste Ableitung der Log-Likelihood an $\\theta_0$)\n- $I(\\theta_0)$: Fisher-Information an $\\theta_0$\n- $L(\\theta)$: Likelihood-Funktion\n\n::: {.callout-note}\n\nAlle drei Tests sind für grosse Stichproben asymptotisch äquivalent. Für kleine Stichproben können die Ergebnisse abweichen.\n\n:::\n\n@fig-trin illustriert die auf der Likelihood-Theorie basierenden asymptotischen Tests für ein Ein-Parameter-Modell mit zu schätzendem Parameter $\\theta$ und dem reduzierten Modell mit fixiertem $\\theta=\\theta_0$.\n\n* Für den Wald-Test muss nur das nicht reduzierte Modell geschätzt werden. \n* Für den Score-Test muss nur das reduzierte Modell geschätzt werden.\n* Für den LR-Test müssen das nicht reduzierte und das reduzierte ($H_0$)-Model berechnet werden.\n\n<!-- ![Asymptotische Teststatistiken](illustrations/Trinity.png \"af\"){#fig-trin} -->\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Log-Likelihood Funktion mit Wald-, Score- und LR-Test](09_logistic_regression_files/figure-html/fig-trin-1.png){#fig-trin fig-align='center' width=768}\n:::\n:::\n\n \nEine Shiny-App dazu kann man in `R` laufen lassen mit\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nshiny::runGitHub(\"Trinity\",\"mcdr65\")\n```\n:::\n\n\noder direkt betrachten über [Asymptotic Tests](https://0194d044-fbd2-1d4d-b675-497b1b36f69b.share.connect.posit.cloud/).\n\n\n\n\n\n#### Vergleich von Wald und LR-Konfidenzintervallen\n\n\n\n@fig-confint zeigt die relative Log-Likelihood für $\\pi$ für unsere Beobachtung $x=37$ auf $n=100$. Die gestrichelte Linie ist die quadratische Approximation, die blaue Linie ist das Wald Konfidenzintervall und die schwarze das Likelihood Ratio Konfidenzintervall. Wald-Intervalle sind oft ungeeignet, vor allem an der Grenze vom Parameterraum oder bei kleinen Stichproben.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Wald und Likelihood Konfidenzintervalle](09_logistic_regression_files/figure-html/fig-confint-1.png){#fig-confint fig-align='center' width=768}\n:::\n:::\n\n\nDie Funktion `confint()` konstruiert Likelihood-Konfidenzintervalle, wenn ein GLM-Objekt als Argument übergeben wird. \n\n\n<!-- ```{r } -->\n<!-- x <- c(rep(1, 37), rep(0, 63)) -->\n<!-- # Wir rechnen eine logistische Regression ohne Prädiktorvariable (darum dieses ~ 1) -->\n<!-- m <- glm(x ~ 1, family = binomial()) -->\n<!-- # Wir exponieren die Schranken des 95% CIs und rechnen die Odds in eine Proportion um -->\n<!-- exp(confint(m))/(1+exp(confint(m))) -->\n<!-- ##Wir können Auch folgende Funktion brauchen -->\n<!-- DescTools::BinomCI(x=37,n=100,method=\"wilson\") -->\n<!-- prop.test(37,100,correct=FALSE) -->\n<!-- ``` -->\n\n\n\n### Zusammenfassung Likelihood\n\nDie wichtigsten Punkte hier noch einmal zusammengefasst:\n \n-   Die Likelihood eines Parameterwertes $L(\\theta)$ ist die Wahrscheinlichkeits(dichte) der beobachteten Daten $x$, gesehen als eine Funktion des unbekannten Parameters $\\theta$,\n\n$$\nL(\\theta)=p(x;\\theta).\n$$\n\n-   Aus mathematischen und numerischen Gründen ist man oft nicht an $L$ interessiert, sondern an der Log-Likelihood.\n\n-   Der Likelihood Approach ist eine generelle Methode, um Parameter zu schätzen und Hypothesen zu testen. Der beste Schätzwert für den Parameter ist jener, welcher die Likelihood-Funktion maximiert (Maximum Likelihood estimate $MLE$).\n\n-   Parameter in Regressionsmodellen wie der logistischen oder der Poisson Regression werden auf diese Art geschätzt.\n\n-  Die Likelihood-Theorie führt zur Wald-, LR-, und Score-Statistik. Mit diesen Statistiken können Tests bezüglich den Parametern gemacht und Konfidenzintervalle konstruiert werden.\n\n-   Der Vorteil des Likelihood Approaches ist, dass er auf komplexe Modelle mit vielen Parametern generalisiert werden kann.\n\n-   Wenn der Stichprobenumfang gross genug ist, kann die Likelihood durch eine quadratische Funktion approximiert werden. Mittels dieser quadratischen Approximation können Standardfehler, Konfidenzintervalle und P-Werte einfacher berechnet werden. Bei Normalverteilung ist diese Approximation sogar exakt. Hypothesentests auf Grundlage der quadratischen Approximation nennt man Wald Tests.\n\n-   P-Werte in den Outputs von logistischen oder einer Poisson Regressionen sind Beispiele für Wald Tests.\n\n\n\n## Verschachtelte Modelle\n\nWie bereits bei der multiplen linearen Regression gehen wir auch hier nicht im Detail darauf ein, wie man die Prädiktorvariablen für eine multiple logistische Regression auswählt. In den Übungen und ggf. in der Prüfung können wir jeweils der Aufgabenstellung entnehmen, welche Variablen in das Modell eingeschlossen werden sollen. Zu Illustrationszwecken wird hier der gleiche, stark vereinfachte Ansatz wie in @sec-wahl-der-prädiktoren verfolgt:\n\n1.  Zuerst wird eine komplexes Modell mit allen Prädiktoren erstellt, unter Berücksichtigung, dass $n \\ge 10p$, wobei $p$ = Anzahl geschätzter Regressionsparameter [@harrell2015].\n\n2.  Schrittweise wird jeweils der Prädiktor mit dem höchsten P-Wert entfernt.\n\n3.  Das reduzierte Modell wird mit dem komplexen Modell verglichen.\n\n4.  Falls sich das reduzierte Modell nicht vom komplexen Modell unterscheidet, fährt man bei 2. fort.\n\nWir schauen uns als erstes das komplexe Modell mit allen acht Prädiktorvariablen an, welches wir weiter oben (@sec-multiple-logistische-regression) bereits erstellt haben:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m.glmF)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = diabetes ~ pregnant_bin + glucose + pressure + \n    triceps + insulin + mass + pedigree + age, family = binomial(), \n    data = diabetes)\n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -1.017e+01  1.307e+00  -7.776 7.47e-15 ***\npregnant_binYes  2.107e-03  4.223e-01   0.005 0.996019    \nglucose          3.820e-02  5.785e-03   6.603 4.04e-11 ***\npressure        -1.079e-03  1.180e-02  -0.091 0.927170    \ntriceps          1.168e-02  1.717e-02   0.680 0.496209    \ninsulin         -9.425e-04  1.327e-03  -0.710 0.477665    \nmass             6.662e-02  2.766e-02   2.409 0.015993 *  \npedigree         1.079e+00  4.228e-01   2.551 0.010727 *  \nage              5.201e-02  1.483e-02   3.506 0.000455 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 498.10  on 391  degrees of freedom\nResidual deviance: 346.24  on 383  degrees of freedom\nAIC: 364.24\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\nZum Begriff der **Devianz** im Output kommen wir weiter unten.\nObwohl die Stichprobe ($n$ = 392) gross genug wäre um neun Regressionsparameter zu schätzen ($\\beta_0$ plus die Effekte $\\beta_1,\\dots,\\beta_8$), scheinen einige Variablen nicht im Zusammenhang mit Diabetes zu stehen. Es ist darum sinnvoll, das Modell zu vereinfachen. Wir entfernen als erstes die Variable `pregnant_bin`. Das geht einfach mit der `update()` Funktion. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.glmF2<-update(m.glmF,.~.-pregnant_bin)\n```\n:::\n\n\nAnschliessend wird das reduzierte Modell mit dem ersten Modell verglichen. Dies kann mit einem Likelihood ratio Test gemacht werden:\n\n* $H_0$: Reduziertes Modell with $p_{reduz}$ Parametern ist wahr.\n* $H_1$: Nicht-reduziertes Modell mit  $p_{gross}$ Parametern ist wahr.\n\n\"Das reduzierte Modell ist wahr\" bedeutet ja: $\\beta_{pregnant.bin}=0$.  Hier wird zuerst im grossen Modell *ein* Parameter fixiert, $\\beta_{pregnant_bin}=0$, darum hat die LRT-Statistik einen Freiheitsgrad. \n\nIn Multiparameter-Modellen gilt dann für den **verallgemeinerten Likelihood-Ratio Test**, dass die Anzahl Freiheitsgrade sich immer ergibt als  der Differenz der zu schätzenden Parameter im nicht-reduzierten relativ zum reduzierten Modell. \n\nDie verallgemeinerte Likelihood-Ratio Statistik ist dann\n\n::: callout-important\n## Verallgemeinerte Likelihood-Ratio Statistik\n\n$$\n\\Large\n-2(l_{reduz}-l_{gross}) \\overset{a}\\sim \\chi^2_{p_{gross}-p_{reduz}}\n$$\n\n:::\n\nDie Grösse $-2(l_{reduz}-l_{gross})$ ist der Unterschied in der **Devianz** zwischen dem reduzierten und dem nicht reduzierten Modell. \n\nDie Devianz eines Modells ist $-2(l_{reduz}-l_{saturated})$ mit $l_{saturated}$ als der Log-likelihood des maximalen Modells (ein Modell mit einem Parameter für jede Beobachtung $i$, also der bestmögliche Fit)\n\n\n$$\n\\begin{aligned}\nD_{\\text{small}} - D_{\\text{large}}\n&=\n-2 (l_{\\text{small}} - l_{\\text{saturated}})\n- \\bigl[-2 (l_{\\text{large}} - l_{\\text{saturated}})\\bigr] \\\\\n&=\n-2 (l_{\\text{small}} - l_{\\text{large}})\n\\end{aligned}\n$$\n\n\n\nHier wird die Funktion `lrtest()` aus dem `lmtest` Package dazu verwendet (`anova()` wäre hier äquivalent). Wir schreiben `anova(kleines Modell, grosses Modell)`:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lmtest)\nlrtest (m.glmF2, m.glmF)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: diabetes ~ glucose + pressure + triceps + insulin + mass + pedigree + \n    age\nModel 2: diabetes ~ pregnant_bin + glucose + pressure + triceps + insulin + \n    mass + pedigree + age\n  #Df  LogLik Df Chisq Pr(>Chisq)\n1   8 -173.12                    \n2   9 -173.12  1     0      0.996\n```\n\n\n:::\n\n```{.r .cell-code}\n# anova(m.glmF2, m.glmF,test=\"Chisq\") # äquivalent\n```\n:::\n\n\n\n\n\n\nWir haben keine Evidenz gegen das Nullmodell (das reduzierte Modell). Aus statistischer Sicht kann man also gut auf die Variable `pregnant_bin` verzichten. Im nächsten Schritt wird zusätzlich die Variable `pressure` entfernt. Anschliessend erfolgt wiederum der Vergleich mit dem ersten Modell.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: diabetes ~ glucose + triceps + insulin + mass + pedigree + age\nModel 2: diabetes ~ pregnant_bin + glucose + pressure + triceps + insulin + \n    mass + pedigree + age\n  #Df  LogLik Df  Chisq Pr(>Chisq)\n1   7 -173.12                     \n2   9 -173.12  2 0.0086     0.9957\n```\n\n\n:::\n:::\n\n\n\nDem Output entnehmen wird, dass das Modell ohne die Variablen `pregnant_bin` und `pressure` (im Output `Model 1`) nicht verworfen werden kann.\n\nWenn man dieses Prozedere nun weiterführt, dann kann man nebst den Variablen `pregnant_bin` und `pressure` auch auf die Variablen `triceps`, `insulin` und `pedigree` verzichten (d.h. ohne dass man das jeweils reduzierte Modell verwerfen kann).\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: diabetes ~ glucose + insulin + mass + pedigree + age\nModel 2: diabetes ~ pregnant_bin + glucose + pressure + triceps + insulin + \n    mass + pedigree + age\n  #Df  LogLik Df  Chisq Pr(>Chisq)\n1   6 -173.35                     \n2   9 -173.12  3 0.4711     0.9252\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: diabetes ~ glucose + mass + pedigree + age\nModel 2: diabetes ~ pregnant_bin + glucose + pressure + triceps + insulin + \n    mass + pedigree + age\n  #Df  LogLik Df  Chisq Pr(>Chisq)\n1   5 -173.62                     \n2   9 -173.12  4 0.9995     0.9099\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: diabetes ~ glucose + mass + age\nModel 2: diabetes ~ pregnant_bin + glucose + pressure + triceps + insulin + \n    mass + pedigree + age\n  #Df  LogLik Df  Chisq Pr(>Chisq)\n1   4 -177.18                     \n2   9 -173.12  5 8.1301     0.1492\n```\n\n\n:::\n:::\n\n\nErst durch die Wegnahme von `mass` ist das neue reduzierte Modell zu verwerfen:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: diabetes ~ glucose + age\nModel 2: diabetes ~ pregnant_bin + glucose + pressure + triceps + insulin + \n    mass + pedigree + age\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1   3 -185.34                         \n2   9 -173.12  6 24.454  0.0004307 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: callout-important \n## Modellvergleich\n\nLetzteren Modellvergleich können wir reproduzieren mit:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(dl<-deviance(m.glmF))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 346.2355\n```\n\n\n:::\n\n```{.r .cell-code}\n(ds<-deviance(m.glmF7))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 370.6897\n```\n\n\n:::\n\n```{.r .cell-code}\n(LR<-ds-dl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.45421\n```\n\n\n:::\n\n```{.r .cell-code}\n1-pchisq(LR,6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0004307352\n```\n\n\n:::\n:::\n\n:::\n\n\nSomit beinhaltet das finale Modell die Prädiktoren `glucose`, `mass` und `age`:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = diabetes ~ glucose + mass + age, family = binomial(), \n    data = diabetes)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -9.677346   1.041873  -9.288  < 2e-16 ***\nglucose      0.036266   0.004906   7.391 1.45e-13 ***\nmass         0.077860   0.020120   3.870 0.000109 ***\nage          0.054075   0.013236   4.085 4.40e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 498.10  on 391  degrees of freedom\nResidual deviance: 354.37  on 388  degrees of freedom\nAIC: 362.37\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\nWir berechnen anhand dieses Modells noch einmal die Wahrscheinlichkeit, dass die vierte Person im Datensatz Diabetes hat. Die Werte für diese Person sind:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndiabetes[4,c(\"glucose\",\"mass\",\"age\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  glucose mass age\n9     197 30.5  53\n```\n\n\n:::\n:::\n\nDer lineare Prädiktor ist dann\n\n\n$$\n\\begin{aligned}\n\\mathrm{logit}(\\hat{\\pi})\n&=\n-9.6773458\n+ 0.0362656 \\times 197\n+ 0.07786 \\times 30.5\n+ 0.0540755 \\times 53 \\\\\n&=\n2.7077043\n\\end{aligned}\n$$\n\n\nDie geschätzten Odds für Diabetes sind dann\n\n$$\n\\hat{O} = \\exp(2.70776) = 14.9956,\n$$\n\nund die geschätzte Wahrscheinlichkeit \n\n$$\n\\hat{\\pi} = \\frac{14.99566}{1+14.99566} = 0.937\n$$\n\n\n\n<!-- **Exkurs**: Obwohl das Modell stark reduziert wurde, ist die geschätzte Wahrscheinlichkeit für Diabetes ähnlich wie mit dem komplexen Modell (93.5% vs. 90.5%). Dies lässt sich auch grafisch darstellen: -->\n\n\n<!-- ```{r include=FALSE} -->\n<!-- m.glmF6$linear.predictors[4] # Der lineare Prädiktor für die 4. Person -->\n<!-- m.glmF6$fitted.values[4] # Der lineare Prädiktor für die 4. Person -->\n<!-- ``` -->\n\n\n\n\n<!-- ```{r} -->\n<!-- #| label: fig-plot-model-full-vs-model-red -->\n<!-- #| fig-cap: \"Geschätzte Wahrscheinlichkeit für Diabetes mit dem komplexen Modell (x-Achse) und dem reduzierten Modell (y-Achse). Man sieht, dass das reduzierte Modell kaum mehr Fehler macht als das komplexe Modell.\" -->\n<!-- p1 <- m.glmF$fitted.values -->\n<!-- p2 <- m.glmF6$fitted.values -->\n\n<!-- TP1 <- ifelse(diabetes$diabetes == \"pos\" & p1 >= 0.5, \"TP1\", \"\") -->\n<!-- TN1 <- ifelse(diabetes$diabetes == \"neg\" & p1 < 0.5, \"TN1\", \"\") -->\n<!-- FP1 <- ifelse(diabetes$diabetes == \"pos\" & p1 < 0.5, \"FP1\", \"\") -->\n<!-- FN1 <- ifelse(diabetes$diabetes == \"neg\" & p1 >= 0.5, \"FN1\", \"\") -->\n<!-- T1 <- paste(TP1, TN1, sep = \"\") -->\n<!-- F1 <- paste(FP1, FN1, sep = \"\") -->\n<!-- M1 <- paste(T1, F1, sep = \"\") -->\n\n\n<!-- TP2 <- ifelse(diabetes$diabetes == \"pos\" & p2 >= 0.5, \"TP2\", \"\") -->\n<!-- TN2 <- ifelse(diabetes$diabetes == \"neg\" & p2 < 0.5, \"TN2\", \"\") -->\n<!-- FP2 <- ifelse(diabetes$diabetes == \"pos\" & p2 < 0.5, \"FP2\", \"\") -->\n<!-- FN2 <- ifelse(diabetes$diabetes == \"neg\" & p2 >= 0.5, \"FN2\", \"\") -->\n<!-- T2 <- paste(TP2, TN2, sep = \"\") -->\n<!-- F2 <- paste(FP2, FN2, sep = \"\") -->\n<!-- M2 <- paste(T2, F2, sep = \"\") -->\n\n<!-- M <- paste(M1, M2, sep = \"-\") -->\n\n<!-- ggplot(data.frame(p1, p2, M), aes(x = p1, y = p2, color = M)) + -->\n<!--   geom_hline(yintercept = 0.5, lty = 2, color = \"darkgray\") + -->\n<!--   geom_vline(xintercept = 0.5, lty = 2, color = \"darkgray\") + -->\n<!--   scale_shape_manual(values=1:8) + -->\n<!--   geom_point(aes(pch = M)) + -->\n<!--   labs(x = \"Wahrscheinlichkeit für Diabetes mit Modell 1\", -->\n<!--        y = \"Wahrscheinlichkeit für Diabetes mit Modell 2\", -->\n<!--        color = \"\", -->\n<!--        pch = \"\") -->\n\n<!-- ``` -->\n\n<!-- Die @fig-plot-model-full-vs-model-red lässt sich in vier Quadranten aufteilen. Im nordöstlichen sowie im südwestlichen Quadranten stimmen die Resultate der beiden Modelle überein (was nicht heisst, dass sie mit der Wahrheit übereinstimmen!). Die blauen Dreiecke in @fig-plot-model-full-vs-model-red sind alle Personen, welche sowohl von Modell 1 sowie von Modell 2 als richtig-negativ (TN) beurteilt wurden. Die pinken Sternchen repräsentieren alle Personen, welche von beiden Modellen als richtig-positiv (TP) beurteilt wurden, usw. Es gibt aber auch einige falsch-negative (FN) und falsch-positive (FP) Resultate, beide Modelle sind demnach längst nicht perfekt, um Diabetes vorauszusagen. -->\n\n<!-- Man sieht, dass die Modelle insgesamt nur in 13 von 392 Fällen zu unterschiedlichen Resultaten kommen (nordwestlicher und südöstlicher Quadrant). Das reduzierte Modell macht sogar einen Fehler weniger (insgesamt 52 falsch-positive und 28 falsch-negative Resultate) als das komplexe Modell (insgesamt 53 falsch-positive und 28 falsch-negative Resultate). Eine Vereinfachung des Modells durch Wegnahme von Prädiktoren scheint in dieser Situation also vertretbar zu sein. -->\n\n\n\n\n**Modellvergleiche mit Wald-Test**. Tests einzelner Koeffizienten, die im `summary(m.glmF)` ersichtlich sind, sind bekanntlich Wald Tests. Wir können diese auch reproduzieren als explizite Modellvergleiche mit der Wald-Statistik:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.glmW<-update(m.glmF,.~.-insulin)## Modell ohne Insulin\nsummary(m.glmF)$coef[6,4]## p-Wert von Insulin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4776647\n```\n\n\n:::\n\n```{.r .cell-code}\n##Wald-Test als Modellvergleich\nlmtest::waldtest(m.glmF,\"insulin\",test=\"Chisq\")$Pr##Wald Test, gleicher p-Wert wie der Z-Test (da Z^2=Chisq(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]        NA 0.4776647\n```\n\n\n:::\n:::\n\n\n\n## Anhang: Hilfreiche `R` Codes für die logistische Regression\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# simulation of data\nn <- 200\nx1 <- rnorm(n, 50, 10)\nx2 <- factor(sample(c(\"A\", \"B\"), n, TRUE))\np <- plogis(-5 + 0.08 * x1 + 1.5 * (x2 == \"B\")) \ny <- rbinom(n, 1, p)\ndata <- data.frame(y, x1, x2)\nhead(data)\n\n# fit logistic regression\nmodel <- glm(y ~ x1 + x2, data, family = binomial)\n\n# summary output\nsummary(model) ## compare with true values\n\n# nicer output\nparameters::parameters(model,exponentiate=TRUE,digits=3)\n\n# predictions (probability)\npredict(model, newdata=data.frame(x1 = 50, x2 = \"A\"), type=\"response\")\n\n# compare two nested models\nmodel.red <- glm(y ~ x1, data, family = binomial)\nlibrary(lmtest)\nlrtest (model.red, model)\n```\n:::\n\n\n\n\n",
    "supporting": [
      "09_logistic_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}