# date: 12/17/2024
date: today
date-format: "DD.MM.YYYY"
format:
    revealjs-light:
      slide-number: true
      theme: [default, styles.scss]
      # footer: "Physiotherapy, Bern Movement Lab"
      logo: "../images/BFH_Logo_A_en_100_RGB.svg"
      # chalkboard: true # only works when not embedding resources
      template-partials:
        - title-slide.html
    revealjs-dark:
      slide-number: true
      theme: [dark, styles.scss]
      # footer: "Physiotherapy, Bern Movement Lab"
      logo: "../images/BFH_Logo_A_en_100_RGB.svg"
      # chalkboard: true # only works when not embedding resources
      template-partials:
        - title-slide.html
embed-resources: true

bibliography: bibliography.bib

execute:
  freeze: auto
