{
  "hash": "01d8e7bfac1654be36cbc541b2e74957",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.hidden}\n$$\n \\def\\logit{\\text{logit}}\n \\def\\Var{\\text{Var}}\n \\def\\iid{\\text{i.i.d.}}\n \\newcommand{\\vect}[1]   {\\left( \\begin{array}{c} #1 \\end{array}\\right)}\n \\def\\Cor{\\text{Cor}}\n  \\def\\Cov{\\text{Cov}}\n$$\n<!-- remove definitions to enable html and pdf -->\n\n:::\n\n\n# Linear Mixed Model\n\n\n::: {.callout-important}\n\n# Lernziele\n\n\n1. Sie können ein Random Intercept Modell anpassen mit den Packeten `lme4` und `lmerTest`.\n2. Sie kennen den Code zum Anpassen von einem Random Intercept Model für Response $Y$, Eingangsgrösse(n) $x$ und Cluster $ID$, `lmer(Y~x+(1|ID))`.\n3. Sie können ein Random Intercept Modell interpretieren (feste Effekte, zufällige Effekte, Varianzkomponenten und Intraklassenkorrelation). \n4. Sie müssen sonst **keinen zusätzlichen Code kennen (lernen)** (zusätzlich benötigter Code für Übungen oder Prüfung zu diesem Thema wird gegeben).\n5. Alternativer Code ist zum späteren Nachschauen gedacht (relativ viele MSc-Arbeiten brauchen Mixed-Models).\n\nAbschnitte mit * sind **für die Interessierten**.\n\n:::\n\n\n\n<!-- ##  Inhalte {.smaller60} -->\n\n<!-- - Recap General Linear Model -->\n<!-- - Bedingte Unabhängigkeit -->\n<!-- - Linear Mixed Models -->\n<!-- - Gepaarter $t$-Test  -->\n<!-- - Within-subject Design -->\n<!-- - Between-Within-subject Design -->\n<!--   - Random intercept -->\n<!--   - Random slope -->\n\n## Recap: General Linear Model (LM) {#sec-recapLM}\n\nDas Allgemeine Lineare Modell mit kontinuierlicher abhängiger Variable $Y$ war: \n\n$$\n\\boxed{Y_i=\\mathbf{x}_i^ T\\mathbf{\\beta}+\\epsilon_i}, \\quad i=1,\\dots, n \n$$\n\nDabei stand $\\mathbf{x}_i^ T\\mathbf{\\beta}$ für den linearen Prädiktor ($T$ steht für *transponiert*; wenn $\\mathbf{x}$ ein Kolonnenvektor ist, ist $\\mathbf{x}^T$ ein Zeilenvektor). Der lineare Prädiktor ist das Skalarprodukt\n\n$$\n\\mathbf{x}_i^T\\mathbf{\\beta}=(1, x_{i1}, \\ldots, x_{im}) \\vect{\\beta_0\\\\\\vdots \\\\\n  \\beta_{im}}=\\beta_0+\\beta_1x_{i1}+\\dots+\\beta_mx_{im}.\n$$ \n\nDabei nahmen wir unabhängige und identisch verteilte stochastische Fehler an, $\\epsilon_i\\, \\iid$, meistens $\\epsilon_i \\sim \\mathcal{N}(0,\\sigma^2)$. Mit $m$ Eingangsgrössen und einem Intercept, also mit $p=m+1$ Parametern und $n$ Beobachtungen können wir das Modell auch in Matrixform schreiben:\n\n\\begin{equation}\n  \\label{eq:42}\n  \\boxed{\\overset{n\\times 1}{\\mathbf{Y}}=\\overset{n\\times\n  p}{X}\\times\\overset{p\\times\n  1}{\\mathbf{\\beta}}+\\overset{n\\times 1}{\\mathbf{\\epsilon}}}\n\\end{equation}\n\n\\begin{equation}\n\\small\n  \\label{eq:43}\n  \\vect{Y_1\\\\Y_2\\\\\\vdots\\\\Y_i\\\\\\vdots\\\\Y_n}=\n  \\begin{pmatrix}\n    1& x_{11}&\\ldots&x_{1m}\\\\\n    1&x_{21}&\\ldots &x_{2m}\\\\\n    \\vdots&\\vdots&\\vdots\\\\\n    1&x_{i1}&\\ldots& x_{im}\\\\\n    \\vdots&\\vdots&\\vdots\\\\\n    1&x_{n1}&\\ldots &x_{nm} \n\\end{pmatrix} \n  \\vect{\\beta_0\\\\ \\vdots \\\\\\beta_m}\n  +\\vect{\\epsilon_1\\\\\\epsilon_2\\\\\\vdots\\\\\\epsilon_i\\\\\\vdots\\\\\\epsilon_n}.  \n\\end{equation}\n\n<!-- - Wir schrieben bisher: $Y_i=\\beta_0+\\beta_1x_{i1}+\\cdots+\\beta_mx_{im}+\\epsilon_i, -->\n<!--   \\quad i=1,\\ldots,n.$ -->\n\nMan nennt die Matrix $X$ **Design-Matrix**. Wir haben also $n$ Gleichungen mit $p$ Unbekannten.\n\n\n\n### Kleinster Quadrate Schätzer* \n\nDie Methode der kleinsten Quadrate haben wir kennengelernt in @sec-LeastSquares. Die Optimierungsfunktion ist also für dieses Modell\n\n$$\n\\mathbf{\\hat{\\beta}}=\\arg \\underset{\\mathbf{\\beta}}{\\operatorname{min\\,}}||\\mathbf{Y}-X\\mathbf{\\beta}||^2.\n$$\n\nDer Ausdruck $\\|\\mathbf{Y} - X\\boldsymbol{\\beta}\\|^2$ bezeichnet die quadratische Norm der Residuen im linearen Regressionsmodell und ist nichts anderes als die Residuenquadratsumme\n$$\n\\|\\mathbf{Y} - X\\boldsymbol{\\beta}\\|^2 = (\\mathbf{Y} - X\\boldsymbol{\\beta})^\\top (\\mathbf{Y} - X\\boldsymbol{\\beta}) = \\sum_{i=1}^n (y_i - \\hat{y}_i)^2.\n$$\n\nAbleiten der Optimierungsfunktion nach $\\mathbf{\\hat{\\beta}}$ gibt\n\\begin{equation}\n  (-2)X^T(\\mathbf{Y}-X\\mathbf{\\hat{\\beta}})=\\mathbf{0}\n\\end{equation}\n\nDies führt uns zu den **Normalgleichungen**\n\\begin{equation}\n   \\overset{p\\times p}{X^TX}\\quad\\overset{p\\times\n     1}{\\mathbf{\\hat{\\beta}}}=\\overset{p\\times 1}{X^T\\mathbf{Y}}.\n\\end{equation}\n\n$X^T$ ist die transponierte Design-Matrix. Das sind dann $p$ lineare Gleichungen für $p$ Unbekannte (Komponenten\nvon $\\mathbf{\\hat{\\beta}}$). \nWenn die Kolonnen der Design-Matrix $X$ linear unabhängig sind, dann ist die $p\\times p$-Matrix $X^TX$\ninvertierbar und der Kleinste-Quadrate-Schätzer ist dann\n\\begin{equation}\n  \\boxed{\\mathbf{\\hat{\\beta}}=(X^TX)^{-1}X^T\\mathbf{Y}}\n\\end{equation}\nund kann aus den Daten berechnet werden. Aus den Residuen  $r_i=y_i-\\mathbf{x}_i^T\\mathbf{\\hat{\\beta}}$ bekommt\nman schliesslich eine Schätzung für $\\sigma^2$, \n\\begin{equation}\n  \\label{eq:s2hat}\n  \\boxed{\\hat{\\sigma}^2=\\frac{1}{n-p}\\sum_{i=1}^n r^2_i}\n\\end{equation}\nDabei entspricht $n-p$, also Anzahl Beobachteten minus die Anzahl Parameter dem Freiheitsgraden.\n\n#### Verteilung der Schätzer bei Normalverteilung*\n\nUnter der Annahme $\\epsilon_i \\,\\iid \\sim \\mathcal{N}(0,\\sigma^2)$ gilt dann:\n\n- Schätzer ist multivariat normalverteilt, $\\mathbf{\\hat{\\beta}}\\sim \\mathcal{N}_p(\\mathbf{\\beta},\\Cov(\\mathbf{\\hat\\beta}))$\n\nmit \n\n\\begin{align}\n \\Cov(\\mathbf{\\hat\\beta})=\n\\begin{pmatrix}\n\\Var(\\hat{\\beta}_1) & \\Cov(\\hat{\\beta}_1,\\hat{\\beta}_2) & \\cdots & \\Cov(\\hat{\\beta}_1,\\hat{\\beta}_p) \\\\ \\\\\n \\Cov(\\hat{\\beta}_2,\\hat{\\beta}_1)  & \\Var\\hat{\\beta}_2) & \\cdots & \\Cov(\\hat{\\beta}_2,\\hat{\\beta}_p) \\\\ \\\\\n \\vdots & \\vdots & \\ddots & \\vdots \\\\ \\\\\n\\Cov(\\hat{\\beta}_p,\\hat{\\beta}_1) & \\Cov(\\hat{\\beta}_p,\\hat{\\beta}_2)\n& \\cdots & \\Var(\\hat{\\beta}_p)\n\\end{pmatrix}\n\\end{align}\n\n- Die Wurzeln der Diagonalelemente entsprechen dann den Standardfehlern. \n\n- Man kann zeigen, dass $\\Cov(\\mathbf{\\hat\\beta})=\\sigma^2 (X^TX)^{-1}$.\n\n- Die geschätzte Residualvarianz hat die Verteilung: $\\hat{\\sigma}^2\\sim \\frac{\\sigma^2}{n-p}\\chi^2_{n-p}$ \n\nDie Normalverteilung der Fehler ist oft nicht erfüllt. Für grosse $n$ sind die Aussagen dann trotzdem annähernd wahr (Zentraler Grenzwertsatz). Das ist dann die herkömmliche Begründung in der Praxis für die Konstruktion von Konfidenzintervallen und Tests für die Parameter des Modells.\n\n\n\n\n## Linear Mixed Model\n\nWir kommen nun zu einer Erweiterung des Linearen Modells, zum Linear Mixed Model (LMM) (Lineares Gemischtes Modell). Oft haben wir in der Gesundheitsforschung zum Beispiel Messwiederholungen innerhalb einer statistischen Einheit (mehrere Beobachtungen innerhalb einer Person) oder wir haben mehrere Beobachtungen innerhalb eines  Clusters (z.B. einem Spital). Die Beobachtungen **innerhalb** einer Person (oder eines Clusters) sind dann ähnlicher als die Beobachtungen **zwischen** Personen (oder Clustern). Die Beobachtungen innerhalb einer statistischen Einheit sind dann nicht mehr unabhängig. Wir haben dann korrelierte Fehler, die wir berücksichtigen müssen (da i.i.d. Annahme dadurch verletzt). Die statistische Einheit ist die Person oder das Cluster, nicht die Beobachtung. \n\n  \n  \n### Bedingte Unabhängigkeit\n \nBedingte Unabhängigkeit spielt eine zentrale Rolle bei den Modellen, die wir unten einführen. \n\nBei Jugendlichen sind `Körpergrösse` und `Wortschatz` offensichtlich nicht unabhängig. Aber sie sind **bedingt unabhängig**, wenn wir für jeden Jugendlichen eine **latente Variable** wie `Maturität` kennen würden. Wenn man den Reifegrad (Maturität) kennt, liefert die Körpergrösse keine zusätzliche Information über den Wortschatz. Das gilt natürlich unter der Annahme, dass die Körpergrösse nur über die Maturität mit dem Wortschatz zusammenhängt.\n\nDieses Prinzip wird nun in Modellen mit latenten Variablen angewandt. Man nimmt an, dass die manifesten Variablen nichts mehr **gemeinsam** haben, nachdem man für eine latente Variable kontrolliert hat.\n\nWir können dies z.B. anwenden für gepaarte Beobachtungen $Y_{i1}$ und $Y_{i2}$ innerhalb einer $i$ten Einheit. Beobachtungen innerhalb einer statistischen Einheit $i$ sind nun korreliert, weil sie einen gemeinsamen Term $U_i$ enthalten. Dieser gemeinsame Term ist latent. Wenn wir ihn kennen würden (auf ihn bedingen), dann sind die Beobachtungen innerhalb einer Einheit unabhängig. Die bedingte Verteilung von $Y_1$ gegeben $Y_2$​ und $U_i$​ ist dann gleich der bedingten Verteilung von $Y_1$ gegeben nur $U_i$​,\n$$\n\\Pr(Y_{i1}\\mid Y_{i2},U_i)=\\Pr(Y_{i1} \\mid U_i).\n$$\n\nWenn man also den latenten Effekt $U_i$ kennt, dann liefert die Information über $Y_2$ keinen zusätzlichen Erkenntnisgewinn über die Verteilung von $Y_1$​. Der gemeinsame Einfluss ist dann herausgerechnet – und die Beobachtungen $Y_{ij}$ sind nur noch durch unabhängige Fehler beeinflusst. Wenn wir $U_i$ nicht kennen, dann sind $Y_{i1}$ und $Y_{i2}$ marginal abhängig. \n\n\nWir können die Korrelation der Beobachtungen innerhalb einer Einheit (Person, Cluster) durch das Hinzufügen von zufälligen oder latenten Variablen $\\mathbf{U}_i$ berücksichtigen. Diese zusätzliche(n) Zufallsvariable(n) induzieren eine Korrelation der wiederholten Beobachtungen und erklären dann die Korrelation der wiederholten Beobachtungen. Bedingt auf die latenten Zufallsvariable(n) $U_i$ sind die Beobachtungen innerhalb einer Einheit unabhängig.\n\nDer Vorteil, die $\\mathbf{U}_i$ als zufällig zu behandeln, ist, dass wir weniger Parameter brauchen. In linearen Mixed Models (LMM) sind die zusätzlichen Parameter **Varianzkomponenten**, die die Varianz der $\\mathbf{U}_i$ spezifizieren, nicht die $\\mathbf{U}_i$ selber. Zudem hätten Fixed-Effects-Parameter $\\mathbf{U}_i$ keine Interpretation als Populationsparameter.\n\n\n\n\n\n##  Allgemeiner Fall*\n\nFür die Interessierten betrachten wir zuerst den allgemeinen Fall. Die für uns wichtigen Spezialfälle weiter unten sind dann einfacher.  \nNeu ist nun der $\\color{red}{rote}$ Teil in der Modellformel.\n\nDas Modell für die Einheit $i$ (Person, Cluster) mit $n_i$ Beobachtungen lautet:\n\n$$\n\\mathbf{Y}_i = \\underbrace{X_i\\boldsymbol{\\beta}}_{\\text{fixed}} + \\underbrace{\\color{red}{Z_i \\mathbf{U}_i}}_{\\text{random}} + \\underbrace{\\boldsymbol{\\epsilon}_i}_{\\text{random}}, \\quad i = 1,\\dots,n.\n$$ {#eq-LMM} \n\n- $\\mathbf{Y}_i$: $n_i \\times 1$-Vektor der kontinuierlichen Zielgrößen für Einheit $i$ (Individuum oder Cluster).\n- $X_i$: $n_i \\times p$ Designmatrix der erklärenden Variablen (Kovariaten), die **Fixed Effects**.\n- $\\boldsymbol{\\beta}$: $p \\times 1$-Vektor der Populationsparameter (Fixed-Effects-Koeffizienten).\n- $\\color{red}{Z_i}$: $n_i \\times k$ Designmatrix der Zufallseffekte.\n- $\\color{red}{\\mathbf{U}_i}$: $k \\times 1$-Vektor der Zufallseffekte mit Erwartungswert $0$ und Kovarianzmatrix $D$.\n- $\\boldsymbol{\\epsilon}_i$: $n_i \\times 1$ Fehlerterm mit unabhängigen Komponenten, jede mit Erwartungswert $0$ und Varianz $\\sigma^2$ (within-subject).\n\nBezüglich Erwartungswert und Varianz gilt:\n\n- Bedingte Erwartung: $E(\\mathbf{Y}_i \\mid \\mathbf{U}_i) = X_i\\boldsymbol{\\beta} + Z_i\\mathbf{U}_i$\n- Marginale Erwartung: $E(\\mathbf{Y}_i) = X_i\\boldsymbol{\\beta}$\n- Bedingte Varianz: $\\operatorname{Cov}(\\mathbf{Y}_i \\mid \\mathbf{U}_i) = \\sigma^2 I_{n_i}$\n- Marginale Varianz: $\\operatorname{Cov}(\\mathbf{Y}_i) = Z_i D Z_i^\\top + \\sigma^2 I_{n_i}$  \n  mit $I_{n_i}$ als $n_i \\times n_i$-Einheitsmatrix.\n\n\nWenn z. B. $Z_i$ eine Spalte aus Einsen ist ($k = 1$), haben wir das **Random Intercept Model**:\n\n$$\n\\mathbf{Y}_i = X_i\\boldsymbol{\\beta} + \\mathbf{U}_i + \\boldsymbol{\\epsilon}_i, \\quad i = 1,\\dots,n.\n$$\n\nDie bedingte Kovarianz ist:\n\n$$\n\\operatorname{Cov}(\\mathbf{Y}_i \\mid \\mathbf{U}_i) =\n\\begin{bmatrix}\n\\sigma^2 & 0 & \\cdots & 0 \\\\\n0 & \\sigma^2 & \\cdots & 0 \\\\\n\\vdots & \\vdots & \\ddots & \\vdots \\\\\n0 & 0 & \\cdots & \\sigma^2\n\\end{bmatrix}\n$$\n\nDie marginale Kovarianz ist:\n\n$$\n\\operatorname{Cov}(\\mathbf{Y}_i) =\n\\begin{bmatrix}\n\\nu^2 + \\sigma^2 & \\nu^2 & \\cdots & \\nu^2 \\\\\n\\nu^2 & \\nu^2 + \\sigma^2 & \\cdots & \\nu^2 \\\\\n\\vdots & \\vdots & \\ddots & \\vdots \\\\\n\\nu^2 & \\nu^2 & \\cdots & \\nu^2 + \\sigma^2\n\\end{bmatrix}\n$$\n\nDies entspricht einem Modell mit **konstanter Korrelation (Intraklassenkorrelation)**:\n\n$$\n\\rho = \\frac{\\nu^2}{\\nu^2 + \\sigma^2}.\n$$\n\nEs gibt viele Modelle mit **nicht-konstanter Korrelation** (z.B. auto-regressive Fehlern), die wir hier nicht behandeln.\n\n <!-- =\\nu^2 J_{n_i}+\\sigma^2I_{n_i}$ [^1] -->\n <!-- [^1]: Mit $J_{n_j}$ als eine $n_i\\times n_i$ Matrix mit Einsen und $I_{n_i}$ als eine $n_i\\times n_i$ Matrix mit Einsen in der Diagonale. -->\n\n\n\n## Random Intercept Model\n\nWir bleiben nun beim Random Intercept Model, welches das bei weitem häufigste LMM darstellt. Eine Zeile (eine Beobachtung $j$ von Einheit $i$) schreiben wir dann\n$$\n\\boxed{Y_{ij}=\\mathbf{x}^T_{ij}\\mathbf{\\beta}+{\\color{red}{U_i}}+\\epsilon_{ij}}, \\quad i=1,\\dots,n, \\quad j=1,\\dots,n_i. \n$$ {#eq-LMMRI}\n\n$n$ steht für die Anzahl Personen oder Cluster und $n_i$ für die Anzahl Beobachtungen für Einheit $i$. Wir haben also total $\\sum_{i=1}^n n_i$ Beobachtungen. Im Gegensatz zum linearen Modell haben wir jetzt zwei Zufallsvariablen, $U_i$ zusätzlich zu $\\epsilon_{ij}$. Wir nehmen für beide Normalverteilungen an, nämlich $U_i\\sim \\mathcal{N}(0, \\nu^2)$ und $\\epsilon_{ij}\\sim \\mathcal{N}(0,\\sigma^2)$. \n\n**Between-und within-subject Varianz**: Der Parameter  $\\nu^2$ stellt nun die  **between-subject Varianz** und  der Parameter $\\sigma^2$ stellt die **within-subject Varianz** dar. \n\nVerglichen mit einem linearen Modell haben wir also zusätzlich ein **random intercept**, $$\\beta_{0i}=\\beta_0+U_i.$$\nWir können [-@eq-LMM] dann schreiben als\n$$\nY_{ij}=\\underbrace{\\beta_0+U_i}_{\\beta_{0i}}+\\beta_1x_{i1}+\\dots+\\beta_m x_{im}+\\epsilon_{ij}.\n$$\n\n\n\n\n### Erwartungswert und Varianz \n\nErwartungswert und Varianz sind dann:\n\n- Erwartungswert\n   -  Bedingte Erwartung: $E(Y_{ij} \\mid U_i)=\\mathbf{x}^T_{ij}\\mathbf{\\beta}+U_i$ \n   -  Marginale Erwartung:\n      $E(Y_{ij})=\\mathbf{x}^T_{ij}\\mathbf{\\beta}$ \n- Varianz\n  - Bedingte Varianz: $\\Var(Y_{ij}\\mid U_i)=\\sigma^ 2$\n  - Marginale Varianz: $\\Var(Y_{ij})=\\nu^2+\\sigma^ 2$\n\n- Intraklassenkorrelation: $\\Cor(Y_{ij},Y_{ij'})=\\frac{\\nu^2}{\\nu^2+\\sigma^2}$. Diese Grösse stellt den Anteil der between-subject Varianz and der totalen Varianz dar.\n\n\n\n## Gepaarter $t$-Test als LMM\n\nDas grundlegendste LMM ist ein Modell, das wir schon kennen, nämlich das Modell, das einem gepaarten $t$-Test entspricht. \n\nMit einen dichotomen Prädiktor $T$, der z.B. einen pre- und einen post-Zeitpunkt definiert, ist das Modell\n$$\nY_{ij}=\\beta_0+\\beta_1T_{ij}+U_i+\\epsilon_{ij}\n$${#eq-ttestpaired} mit $i=1,\\dots, n, \\quad j=1,2$ und\n      $T_{ij}=\\begin{cases} 1 &\\mbox{wenn } j=2, \\\\\n0 & \\mbox{wenn } j=1  \\end{cases}$ \n\nWir haben wieder $U_i\\sim \\mathcal{N}(0, \\nu^2),\\quad \\epsilon_{ij}\\sim \\mathcal{N}(0,\\sigma^2)$ und $\\Cor(Y_{i1},Y_{i2})=\\frac{\\nu^2}{\\nu^2+\\sigma^2}$.\n\nDie Quantität von Interesse ist wie beim gepaarten $t$-Test die erwartete Veränderung zwischen $t_1$ und $t_2$. Diese Quantität entspricht dem Parameter $\\beta_1$.\n\n\n### Daten\n\nDas data.frame `d.long2` beinhaltet eine kontinuierliche abhängige Variable zu zwei Zeitpunkten mit $n=30$ und $n_i=2$ für alle $i$. Daten sind im **Long Format**, d.h. wir haben eine Zeile für jede Beobachtung, also zwei Zeilen für jede statistische Einheit.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd.long2<-read.csv(\"https://raw.githubusercontent.com/mcdr65/StatsRsource/master/Data/Rep2.csv\",stringsAsFactors=TRUE)\nstr(d.long2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t60 obs. of  3 variables:\n $ subject : Factor w/ 30 levels \"s1\",\"s10\",\"s11\",..: 1 1 12 12 23 23 25 25 26 26 ...\n $ time    : Factor w/ 2 levels \"t1\",\"t2\": 1 2 1 2 1 2 1 2 1 2 ...\n $ response: num  22.9 38.4 10.8 18.2 33.2 ...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(psych)\nheadTail(d.long2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    subject time response\n1        s1   t1    22.93\n2        s1   t2    38.43\n3        s2   t1     10.8\n4        s2   t2    18.17\n...    <NA> <NA>      ...\n57      s29   t1     6.53\n58      s29   t2    16.07\n59      s30   t1    34.25\n60      s30   t2     42.4\n```\n\n\n:::\n:::\n\n\n### Wide und Long Format\n\nMit `reshape()` kann man Daten vom Wide Format ins Long Format umwandeln und umgekehrt. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd.wide2<-reshape(d.long2,timevar=\"time\",idvar=\"subject\",direction=\"wide\")\nheadTail(d.wide2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    subject response.t1 response.t2\n1        s1       22.93       38.43\n3        s2        10.8       18.17\n5        s3       33.22        37.9\n7        s4       24.82       41.64\n...    <NA>         ...         ...\n53      s27       29.69       36.21\n55      s28       23.93       33.57\n57      s29        6.53       16.07\n59      s30       34.25        42.4\n```\n\n\n:::\n:::\n\n\nDas Studieren der Beispiele in `?reshape` lohnt sich, da entsprechende Umwandlungen doch oft benötigt werden. Wenn man gerne `tidyverse` verwendet, kann man mit den Funktionen `pivot_longer` und `pivot_wider` arbeiten.\n\n\nIm Wide Format haben wir nun eine Zeile pro statistische Einheit, dafür mehrere (hier zwei) Kolonnen.\n\nDie beobachtete Korrelation der wiederholten Messungen bekommen wir mit\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor(d.wide2[,-1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            response.t1 response.t2\nresponse.t1   1.0000000   0.7097983\nresponse.t2   0.7097983   1.0000000\n```\n\n\n:::\n:::\n\n\nUm ein Linear Mixed Model anzupassen, brauchen wir Daten **immer im Long Format**. Eine Zeile entspricht dann einer Beobachtung, nicht einer statistischen Einheit.\n\n\n\n\n### Beschreiben \n\nZuerst beschreiben wir die Daten\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npsych::describeBy(d.long2$response,group=d.long2$time,mat=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     item group1 vars  n mean       sd median trimmed     mad min max range\nX1*1    1     t1    1 30 15.5 8.803408   15.5    15.5 11.1195   1  30    29\nX1*2    2     t2    1 30 15.5 8.803408   15.5    15.5 11.1195   1  30    29\n     skew  kurtosis       se\nX1*1    0 -1.320495 1.607275\nX1*2    0 -1.320495 1.607275\n```\n\n\n:::\n\n```{.r .cell-code}\n##Alternativen\ntapply(d.long2$response,d.long2$time,summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$t1\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  6.528  17.648  23.270  24.734  33.667  41.388 \n\n$t2\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  9.754  32.226  36.445  34.892  40.367  52.976 \n```\n\n\n:::\n\n```{.r .cell-code}\nsapply(split(d.long2$response,d.long2$time),summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               t1        t2\nMin.     6.528457  9.754138\n1st Qu. 17.648453 32.225761\nMedian  23.270037 36.444692\nMean    24.734463 34.891809\n3rd Qu. 33.666633 40.366996\nMax.    41.388153 52.975589\n```\n\n\n:::\n\n```{.r .cell-code}\npsych::describe(d.wide2[,-1]) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            vars  n  mean   sd median trimmed  mad  min   max range  skew\nresponse.t1    1 30 24.73 9.15  23.27   24.73 9.94 6.53 41.39 34.86  0.07\nresponse.t2    2 30 34.89 9.25  36.44   35.73 6.45 9.75 52.98 43.22 -0.76\n            kurtosis   se\nresponse.t1    -1.10 1.67\nresponse.t2     0.57 1.69\n```\n\n\n:::\n:::\n\n\nMit `arsenal::paired()` bekommen wir\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntmp<-arsenal::paired(time~response,id=subject,data=d.long2,test=FALSE)\nsummary(tmp,text=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n|             |   t1 (N=30)    |   t2 (N=30)    | Difference (N=30) |\n|:------------|:--------------:|:--------------:|:-----------------:|\n|response     |                |                |                   |\n|-  Mean (SD) | 24.734 (9.148) | 34.892 (9.252) |  10.157 (7.009)   |\n|-  Range     | 6.528 - 41.388 | 9.754 - 52.976 |  -3.896 - 27.889  |\n```\n\n\n:::\n:::\n\n\nEin **Spaghetti plot** ist bei gepaarten Daten besser geeignet als ein Boxplot, da aus einem Boxplot das Design nicht eindeutig ist. Die Paarung der Beobachtungen ist im Boxplot nicht ersichtlich. \n  \n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nwith(d.long2,interaction.plot(time,subject,response,ylab=\"response\"))\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=480}\n:::\n\n```{.r .cell-code}\nboxplot(response~time,d.long2)\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-8-2.png){fig-align='center' width=480}\n:::\n:::\n\n  \nEs gibt viele Alternativen zum Plotten, z.B. mit `lattice` oder `ggplot2`:\n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nlattice::xyplot(response~time,groups=subject,data=d.long2,type=\"b\")\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=480}\n:::\n\n```{.r .cell-code}\n##\nlibrary(ggplot2)  \np <- ggplot(data = d.long2, aes(x = time, y = response, group = subject))\np <- p+geom_point()+geom_line()+stat_smooth(aes(group = 1),method=\"lm\",se=FALSE)\np <- p + stat_summary(aes(group=1), geom = \"point\", fun = mean,shape = 17, size = 4)\np\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-9-2.png){fig-align='center' width=480}\n:::\n:::\n\n\n\n\n### Analyse: Als gepaarter $t$-test\n\nEin gepaarter Test ist bekannterweise äquivalent zu einem one-sample Test der Veränderung:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npre<-d.long2$response[d.long2$time==\"t1\"]\npost<-d.long2$response[d.long2$time==\"t2\"]\nchange<-post-pre\nprint(t.test(post,pre,paired=TRUE,data=d.long2),digits=6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  post and pre\nt = 7.937, df = 29, p-value = 9.4e-09\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n  7.53997 12.77472\nsample estimates:\nmean difference \n        10.1573 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(t.test(change),digits=6) # äquivalent  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  change\nt = 7.937, df = 29, p-value = 9.4e-09\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n  7.53997 12.77472\nsample estimates:\nmean of x \n  10.1573 \n```\n\n\n:::\n:::\n\n\n\n\n### Analyse: Als Repeated Measures ANOVA*\n\n`aov()` dient wie `lm()` zum Anpassen linearer Modelle. Der Unterschied ist die Art und Weise, wie `print()` und `summary()` den Fit behandeln.\nMit `aov()` ist der Ausdruck in der traditionellen Sprache der Varianzanalyse anstelle der linearen Modelle. Wenn die Modellformel einen einzelnen Fehlerterm enthält, wird dieser verwendet, um Fehlerstrata zu spezifizieren, und es werden geeignete Modelle innerhalb jeder Fehlerschicht angepasst.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.aov<-aov(response~time+Error(subject),data=d.long2)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nError: subject\n          Df Sum Sq Mean Sq F value Pr(>F)\nResiduals 29   4197   144.7               \n\nError: Within\n          Df Sum Sq Mean Sq F value  Pr(>F)    \ntime       1 1547.6  1547.6      63 9.4e-09 ***\nResiduals 29  712.4    24.6                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWir können die entsprechenden Quadratsummen von `aov()` reproduzieren. Dazu passen wir folgende Modelle an:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod0 <- lm(response~1,d.long2) \nmods <- lm(response~subject,d.long2)\nmodt <- lm(response~time,d.long2)\nmodts <-lm(response~subject+time,d.long2)\n```\n:::\n\nDie Residual-Quadratsummen der Modelle sind dann:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrss.0 <- sum((mod0$residuals)^2)\nrss.s <- sum((mods$residuals)^2)\nrss.t <- sum((modt$residuals)^2)\nrss.ts<- sum((modts$residuals)^2)\n```\n:::\n\n\nWir haben dann:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrss.0 #SS_total\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6456.65\n```\n\n\n:::\n\n```{.r .cell-code}\nrss.0-rss.t #SS_time\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1547.575\n```\n\n\n:::\n\n```{.r .cell-code}\nrss.0-rss.s #SS_subject\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4196.653\n```\n\n\n:::\n\n```{.r .cell-code}\nrss.ts #SS_residual_within\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 712.4216\n```\n\n\n:::\n\n```{.r .cell-code}\nrss.0-rss.t+rss.ts#SS_total_within\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2259.997\n```\n\n\n:::\n:::\n\n\nRepeated Measures ANOVA ist meistens nicht empfehlenswert für die Analyse von wiederholten Messungen. Eine flexiblere und\nmoderne Alternative ist ein LMM. Ein solches Modell wollen wir jetzt an die Daten anpassen.\n\n\n### Analyse: Als Linear Mixed Model (LMM)\n\nLineare Gemischte Modelle (LMM) sind die moderne Alternative zur Analyse von Messwiederholungen oder Beobachtungen mit korrelierten Fehlern. Der Vorteil gegenüber Repeated-Measures ANOVA ist, dass LMM nicht-balancierte Daten oder Daten mit fehlenden Werten besser verarbeiten. Klassische Repeated Measures ANOVA `aov(...+Error(subject))` brauchen balancierte Daten ohne Missings.\n\nWir verwenden im Folgenden die Funktion `lmer()` aus dem Paket `lme4` Zusätzlich nutzen wir auch das Paket `lmerTest` (mehr dazu später).\nLMM werden mit der Maximum-Likelihood-Schätzung (siehe @sec-maxLik) angepasst (im Gegensatz zu `lm()` und `aov()`, die mit der Methode der kleinsten Quadrate angepasst werden).\n\n\n\n#### LMM anpassen\n\nWir laden zuerst `lme4`, gefolgt von `lmerTest`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lme4) \nlibrary(lmerTest) #immer laden nach lme4\n```\n:::\n\nDie Syntax für ein Random Intercept Modell ist \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.2rep<-lmer(response~time+(1|subject), data=d.long2)\n```\n:::\n\n\nWir brauchen die `lmer()` Funktion. Das neue Element in der Modellformel ist der Term `(1|subject)`. Dieser stellt ein Random Intercept dar (Abstand für Einheit $i$ zum fixed Intercept). Der Grund ist inzwischen bekannt: Die Beobachtungen innerhalb eines Subjekts sind gruppiert (wiederholte Messungen innerhalb eines Subjekts). Das Random Intercept induziert dann eine Korrelation der wiederholten Messungen.\n\n\n#### Model Fit\n\n`summary()` ist eine generische Funktion, der auch `lmer` Objekte übergeben werden können:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m.2rep,cor=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: response ~ time + (1 | subject)\n   Data: d.long2\n\nREML criterion at convergence: 408.5\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-2.0380 -0.4875 -0.0289  0.5657  2.1045 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n subject  (Intercept) 60.07    7.751   \n Residual             24.57    4.956   \nNumber of obs: 60, groups:  subject, 30\n\nFixed effects:\n            Estimate Std. Error    df t value Pr(>|t|)    \n(Intercept)    24.73       1.68 38.57  14.726  < 2e-16 ***\ntimet2         10.16       1.28 29.00   7.937  9.4e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nIm Output sind neu die Between-subject und Within-subject Varianz der Random effects ersichtlich. Das sind die Parameter, die die Verteilung der Random effects spezifizieren. Die Random effects selber, die $U_i$, sehen wir hier nicht. Ersichtlich ist auch die Anzahl Beobachtungen und die Anzahl statistischer Einheiten. Die Fixed effects sind analog zum Linearen Modell zu interpretieren. Die geschätzte erwartete Veränderung ist 10.1573458.\n\n\n#### Shrinkage*\n\nDie geschätzten Random effects $\\hat{U}_i$ selber können wir extrahieren mit `ranef()`. Sie sind posterior-Schätzungen bedingt auf die Daten, $\\hat{U}_i=E(U_i\\mid Y_i)$. Ihre Varianz ist kleiner als die wahre Varianzkomponente aufgrund von sogenannter Shrinkage (auf die wir hier nicht eingehen), $\\Var(\\hat{U}_i)<\\nu^2$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nranef(m.2rep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$subject\n    (Intercept)\ns1    0.7234120\ns10   8.9460286\ns11  -1.5461913\ns12  -2.7086903\ns13   2.4543710\ns14  -3.6550798\ns15  -0.8162158\ns16  -2.1832215\ns17   7.6531476\ns18  -4.1532914\ns19  -3.3900425\ns2  -12.7239664\ns20  -5.1947473\ns21   8.5356755\ns22  -3.8224224\ns23   8.0093269\ns24   6.2283789\ns25  -0.4167840\ns26  -3.7005501\ns27   2.6031749\ns28  -0.8796224\ns29 -15.3696272\ns3    4.7682908\ns30   7.0648977\ns4    2.8367827\ns5    7.7111655\ns6    5.3103447\ns7  -15.0365021\ns8   -8.8412370\ns9   11.5931946\n\nwith conditional variances for \"subject\" \n```\n\n\n:::\n\n```{.r .cell-code}\nmean(ranef(m.2rep)$subject$\"(Intercept)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -4.186281e-14\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(ranef(m.2rep)$subject$\"(Intercept)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 49.875\n```\n\n\n:::\n:::\n\n\n<!-- Einen besseren  Output bekommen wir mit -->\n\n<!-- ```{r } -->\n<!-- parameters::parameters(m.2rep) -->\n<!-- parameters(m.2rep,ci_method=\"satterthwaite\") -->\n<!-- ``` -->\n\n#### Verteilung der $t$-Statistik für fixed effects*\n\nIn gemischten linearen Modellen (LMMs) ist die Verteilung der Teststatistiken für feste Effekte komplizierter als in klassischen linearen Modellen, da die Schätzung der Varianzkomponenten (zufällige Effekte) zusätzliche Unsicherheit einführt. \n\nAngenommen, wir testen einen festen Effekt $\\beta_j$. Die Teststatistik lautet:\n$$\nt = \\frac{\\hat{\\beta}_j}{\\text{SE}(\\hat{\\beta}_j)}\n$$\n\nDa die Standardabweichung von geschätzten Varianzkomponenten abhängt, ist die Verteilung von \n$t$ nicht exakt eine $t$-Verteilung mit bekannten Freiheitsgraden. Die Satterthwaite-Methode approximiert die Freiheitsgrade $\\nu$ sodass:\n\n$$\nt \\sim t_\\nu\n$$\n\nDie Approximation basiert auf der Idee, die Varianz der Schätzung selbst als Zufallsvariable zu behandeln und deren Unsicherheit zu berücksichtigen. \n\n\n<!-- Die geschätzten Freiheitsgrade $\\nu$ werden durch folgende Formel berechnet: -->\n\n<!-- $$ -->\n<!-- \\nu \\approx \\frac{2 \\cdot \\left[\\text{Var}(\\hat{\\beta}_j)\\right]^2}{\\text{Var}\\left[\\text{Var}(\\hat{\\beta}_j)\\right]} -->\n<!-- $$ -->\n\n<!-- Diese Formel basiert auf der Delta-Methode, einer Technik zur Approximation der Varianz einer Funktion einer Zufallsvariablen. -->\n\nDie `lmerTest`-Erweiterung zu `lme4` berechnet $p$-Werte und Freiheitsgrade für feste Effekte. Die Freiheitsgrade sind nicht ganzzahlig und hängen vom jeweiligen Effekt und der Struktur der zufälligen Effekte ab.\nDie Methode ist besonders nützlich bei unausgeglichenen Designs oder komplexen Random-Strukturen, wo klassische df-Schätzungen versagen. Das Laden von `lmerTest` nach dem Laden von `lme4` wird empfohlen (und das haben wir auch gemacht), wenn $p$-Werte benötigt werden, da es Freiheitsgrade approximiert und die $t$-Statistiken somit für Hypothesentests interpretierbarer macht.\n\n\n\n#### Tests\n\nDen Zeiteffekt explizit als Modellvergleich machen wir mit einem Modellvergleich:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.2rep0<-update(m.2rep,.~.-time)\nanova(m.2rep0,m.2rep)##LR-Test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: d.long2\nModels:\nm.2rep0: response ~ (1 | subject)\nm.2rep: response ~ time + (1 | subject)\n        npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nm.2rep0    3 454.16 460.44 -224.08    448.16                         \nm.2rep     4 421.52 429.90 -206.76    413.52 34.633  1   3.98e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAlternativen wären `drop1()` für Wald-Tests und einfach `anova()`, weil wir nur eine Eingangsgrösse haben:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndrop1(m.2rep) ##Wald-type\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSingle term deletions using Satterthwaite's method:\n\nModel:\nresponse ~ time + (1 | subject)\n     Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)    \ntime 1547.6  1547.6     1    29  62.996 9.4e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(m.2rep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n     Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)    \ntime 1547.6  1547.6     1    29  62.996 9.4e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n\n#### Intraklassenkorrelation\n\nDie Intraklassenkorrelation hatten wir oben schon berechnet. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprint(VarCorr(m.2rep),comp=\"Variance\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups   Name        Variance\n subject  (Intercept) 60.073  \n Residual             24.566  \n```\n\n\n:::\n:::\n\n\nDie geschätzte Intraklassenkorrelation ist also\n\n$$\n\\widehat{\\Cor}(Y_{i1},Y_{i2})=\\frac{\\hat{\\nu}^2}{\\hat{\\nu}^2+\\hat{\\sigma}^2}=0.7097532\n$$\n\n\n<!-- ## Alternativer Output{.smaller60} -->\n\n<!-- ```{r } -->\n<!-- library(easystats) -->\n<!-- model_parameters(m.2rep,ci_method=\"satterthwaite\") -->\n<!-- `` -->\n\n<!-- ## Model performance{.smaller60} -->\n\n<!-- ```{r } -->\n<!-- performance::icc(m.2rep) -->\n<!-- ``` -->\n\n\n\n\n#### Kontraste\n\nIn diesem Fall gibt es nur einen Kontrast von Interesse, der selber schon ein Parameter der Grundparametrisierung ist: \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(emmeans)\nsummary(emmeans(m.2rep,revpairwise~time),infer=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n time emmean   SE   df lower.CL upper.CL t.ratio p.value\n t1     24.7 1.68 38.6     21.3     28.1  14.726 <0.0001\n t2     34.9 1.68 38.6     31.5     38.3  20.773 <0.0001\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n\n$contrasts\n contrast estimate   SE df lower.CL upper.CL t.ratio p.value\n t2 - t1      10.2 1.28 29     7.54     12.8   7.937 <0.0001\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nHier bringt dieser Schritt keine zusätzliche Information. Mit dem `emmeans()` kann man sich dann aber vor allem bei komplexeren Modellen Kontraste von Interesse berechnen lassen, wie wir das früher schon gemacht haben. \n\n\n#### Vorhersagen\n\nLMM sind zweistufige Modelle, man hat bedingte (auf Subject bedingt) und marginale Vorhersagen. Wir können ein Data frame erstellen mit den bedingten und marginalen Vorhersagen und diese plotten:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredictions <- data.frame(\n  actual = d.long2$response,\n  CondPred = predict(m.2rep),  # PREDICT AT SUBJECT LEVEL\n  MargPred=predict(m.2rep,re.form=~0), # PREDICT MARGINALLY\n  time = d.long2$time,\n  subject=d.long2$subject)\n```\n:::\n\nWir sehen, dass die marginalen Vorhersagen nicht von `subject` abhängen.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheadTail(predictions,8,8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    actual CondPred MargPred time subject\n1    22.93    25.46    24.73   t1      s1\n2    38.43    35.62    34.89   t2      s1\n3     10.8    12.01    24.73   t1      s2\n4    18.17    22.17    34.89   t2      s2\n5    33.22     29.5    24.73   t1      s3\n6     37.9    39.66    34.89   t2      s3\n7    24.82    27.57    24.73   t1      s4\n8    41.64    37.73    34.89   t2      s4\n...    ...      ...      ... <NA>    <NA>\n53   29.69    27.34    24.73   t1     s27\n54   36.21    37.49    34.89   t2     s27\n55   23.93    23.85    24.73   t1     s28\n56   33.57    34.01    34.89   t2     s28\n57    6.53     9.36    24.73   t1     s29\n58   16.07    19.52    34.89   t2     s29\n59   34.25     31.8    24.73   t1     s30\n60    42.4    41.96    34.89   t2     s30\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(predictions, aes(x = time, y = CondPred, color = subject)) +\n    geom_point(aes(y=actual,color=subject))+\n    geom_line(aes(y=CondPred,group=subject),lty=1)+\n    geom_line(aes(y=MargPred,group=subject),lty=2,lwd=1.3,col=\"black\")+theme(legend.position=\"none\")+ylab(\"prediction\")\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nEine Alternative für bedingte Vorhersagen wäre \n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nlattice::xyplot(fitted(m.2rep)~time,groups=subject,data=d.long2,type=\"b\")\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-26-1.png){fig-align='center' width=480}\n:::\n\n```{.r .cell-code}\n##oder\nd.longG <- nlme::groupedData(fitted(m.2rep) ~ time | subject, data = d.long2)\nplot(d.longG)\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-26-2.png){fig-align='center' width=480}\n:::\n:::\n\n\n\n\n#### Nicht-Berücksichtigung der Korrelation\n\nWas passiert bei Nicht-Berücksichtigung der korrelierten Fehler? Die Punktschätzungen werden nicht beeinflusst, aber die Standardfehler, und damit die Resultate von Intervallschätzungen und Tests:\n\n- Die Unsicherheit des Effekts von between-subject oder between-cluster Variablen wird unterschätzt.\n(Grund: Künstliche Erhöhung der Stichprobengrösse).\n\n- Die Unsicherheit des Effekts von within-subject oder within-cluster Variablen wird überschätzt.\n(Grund: Die Variabilität wird überschätzt, z. B. hat ein gepaarter $t$-Test mehr Power als ein unabhängiger $t$-Test).\n\n- Vergleichen wir also mit den Resultate, wenn wir statt ein LMM ein LM (`lm()`) anpassen würden:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(lm(response~time,data=d.long2))$coef ## false\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error   t value     Pr(>|t|)\n(Intercept) 24.73446   1.679675 14.725746 2.976139e-21\ntimet2      10.15735   2.375419  4.276023 7.190056e-05\n```\n\n\n:::\n:::\n\n\n\nWir sehen, dass der within-subject Effekt dann einen grösseren Standardfehler hat und damit einen kleineren $t$-Wert als im LMM:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m.2rep)$coef ## correct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error       df   t value     Pr(>|t|)\n(Intercept) 24.73446   1.679675 38.57025 14.725746 2.025810e-17\ntimet2      10.15735   1.279746 29.00000  7.936999 9.399616e-09\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Within-subject Design\n\nWir verallgemeinern nun den gepaarten $t$-Test auf ein within-subject Design.\n \n\n### Daten und Design\n\nDas Data frame `d.long` besteht aus 80 Beobachtungen mit $n_i=4$ wiederholten Messungen (`time`) von $n=20$ subjects (`subject`) auf einer kontinuierlichen abhängigen Variablen (`response`). \n\nHier haben wir $n_i=4$ konstant für alle $i$. Die Anzahl Beobachtungen pro Einheit muss aber nicht konstant sein. Wir könnten ein LMM auch dann anpassen, wenn wir für jede Einheit $i$ eine unterschiedliche Anzahl Beobachtungen hätten (z.B. $n_1=2,n_2=5,\\dots,n_n=3$).\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd.long<-read.csv(\"https://raw.githubusercontent.com/mcdr65/StatsRsource/master/Data/ToyRepAnova.csv\",\n                 stringsAsFactors=TRUE)\nstr(d.long)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t80 obs. of  3 variables:\n $ subject : Factor w/ 20 levels \"s1\",\"s10\",\"s11\",..: 1 1 1 1 12 12 12 12 14 14 ...\n $ time    : Factor w/ 4 levels \"t1\",\"t2\",\"t3\",..: 1 2 3 4 1 2 3 4 1 2 ...\n $ response: num  53 43 66.2 62.5 26.4 ...\n```\n\n\n:::\n\n```{.r .cell-code}\npsych::headTail(d.long)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    subject time response\n1        s1   t1    52.98\n2        s1   t2       43\n3        s1   t3    66.25\n4        s1   t4    62.47\n...    <NA> <NA>      ...\n77      s20   t1    63.77\n78      s20   t2    23.15\n79      s20   t3    54.46\n80      s20   t4    26.16\n```\n\n\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwith(d.long,xtabs(~time))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntime\nt1 t2 t3 t4 \n20 20 20 20 \n```\n\n\n:::\n:::\n\n\n### Beschreiben \n\nZuerst beschreiben wir die Daten.\n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nwith(d.long,interaction.plot(time,subject,response,ylab=\"response\"))\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=480}\n:::\n\n```{.r .cell-code}\n## alternative with ggplot2\np <- ggplot(data = d.long, aes(x = time, y = response, group = subject))\np <- p+geom_point()+geom_line(lty=2)+stat_summary(fun=mean,geom=\"line\",aes(group = 1),color=\"red\",lwd=2)\np <- p + stat_summary(aes(group=1), geom = \"point\", fun = mean,shape = 17, size = 4)\np\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-31-2.png){fig-align='center' width=480}\n:::\n:::\n\n\n<!-- Wie immer gibt es viele Alternativen, z.B.: -->\n\n<!-- ```{r } -->\n<!-- #| layout-ncol: 2 -->\n<!-- d.longG<-nlme::groupedData(response~time|subject,data=d.long) -->\n<!-- plot(d.longG) -->\n<!-- d.longG<-nlme::groupedData(response~as.numeric(time)|subject,data=d.long) -->\n<!-- plot(d.longG) -->\n<!-- ``` -->\n\n\nWir können jeden Zeitpunkt einzeln beschreiben:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npsych::describeBy(d.long$response,group=d.long$time,mat=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     item group1 vars  n mean      sd median trimmed   mad min max range skew\nX1*1    1     t1    1 20 10.5 5.91608   10.5    10.5 7.413   1  20    19    0\nX1*2    2     t2    1 20 10.5 5.91608   10.5    10.5 7.413   1  20    19    0\nX1*3    3     t3    1 20 10.5 5.91608   10.5    10.5 7.413   1  20    19    0\nX1*4    4     t4    1 20 10.5 5.91608   10.5    10.5 7.413   1  20    19    0\n      kurtosis       se\nX1*1 -1.380929 1.322876\nX1*2 -1.380929 1.322876\nX1*3 -1.380929 1.322876\nX1*4 -1.380929 1.322876\n```\n\n\n:::\n\n```{.r .cell-code}\ntapply(d.long$response,d.long$time,summary) #alternative\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$t1\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n -9.232  10.966  26.576  26.582  35.109  63.772 \n\n$t2\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n-0.5464 24.2050 36.4388 39.0144 52.7406 72.5708 \n\n$t3\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  11.93   27.87   47.44   44.69   55.25   96.31 \n\n$t4\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  6.818  22.668  32.504  36.900  48.607  81.482 \n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(response~time,data=d.long,summary) #alternative\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  time response.Min. response.1st Qu. response.Median response.Mean\n1   t1    -9.2323379       10.9655202      26.5757505    26.5815129\n2   t2    -0.5464301       24.2050217      36.4388469    39.0143684\n3   t3    11.9344197       27.8672784      47.4391539    44.6869727\n4   t4     6.8175026       22.6681781      32.5041280    36.8996576\n  response.3rd Qu. response.Max.\n1       35.1086532    63.7719879\n2       52.7406216    72.5707588\n3       55.2541992    96.3130758\n4       48.6071278    81.4817148\n```\n\n\n:::\n:::\n\n\nWir können auch mit dem Wide-Format arbeiten. Manchmal ist das für die deskriptive Anlayse einfacher. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd.wide<-reshape(d.long,v.names=\"response\",idvar=\"subject\",timevar=\"time\",direction=\"wide\")\nheadTail(d.wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    subject response.t1 response.t2 response.t3 response.t4\n1        s1       52.98          43       66.25       62.47\n5        s2       26.43       26.45       57.62       47.31\n9        s3       10.35       71.25       49.91       64.49\n13       s4       10.88       13.85       61.11       32.41\n...    <NA>         ...         ...         ...         ...\n65      s17          11       23.05       32.81       23.58\n69      s18       26.93       33.05       11.93       18.14\n73      s19       22.18       48.82       50.68        32.6\n77      s20       63.77       23.15       54.46       26.16\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(d.wide[,-1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  response.t1      response.t2       response.t3     response.t4    \n Min.   :-9.232   Min.   :-0.5464   Min.   :11.93   Min.   : 6.818  \n 1st Qu.:10.966   1st Qu.:24.2050   1st Qu.:27.87   1st Qu.:22.668  \n Median :26.576   Median :36.4388   Median :47.44   Median :32.504  \n Mean   :26.582   Mean   :39.0144   Mean   :44.69   Mean   :36.900  \n 3rd Qu.:35.109   3rd Qu.:52.7406   3rd Qu.:55.25   3rd Qu.:48.607  \n Max.   :63.772   Max.   :72.5708   Max.   :96.31   Max.   :81.482  \n```\n\n\n:::\n:::\n\n\n\n### Anpassen des LMM\n\nDie Syntax ist äquivalent zum gepaarten $t$-Test. Wir nennen das neue Modellobjekt `m.4rep`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.4rep<-lmer(response~time+(1|subject), data=d.long)\nsummary(m.4rep,cor=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: response ~ time + (1 | subject)\n   Data: d.long\n\nREML criterion at convergence: 684\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.8422 -0.5911 -0.1200  0.6007  2.2892 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n subject  (Intercept)  97.31    9.865  \n Residual             333.95   18.274  \nNumber of obs: 80, groups:  subject, 20\n\nFixed effects:\n            Estimate Std. Error     df t value Pr(>|t|)    \n(Intercept)   26.582      4.644 65.930   5.724 2.77e-07 ***\ntimet2        12.433      5.779 57.000   2.151  0.03569 *  \ntimet3        18.105      5.779 57.000   3.133  0.00273 ** \ntimet4        10.318      5.779 57.000   1.786  0.07950 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nNeu sind nun zusätzliche feste Effekte, da `time` nun vierwertig ist. Der Globaltest für den Effekt von `time` mit `drop1()` zeigt, dass man `time` nicht aus dem Modell nehmen darf.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndrop1(m.4rep) ##Wald-type\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSingle term deletions using Satterthwaite's method:\n\nModel:\nresponse ~ time + (1 | subject)\n     Sum Sq Mean Sq NumDF DenDF F value  Pr(>F)  \ntime 3430.7  1143.6     3    57  3.4244 0.02305 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nDie Between-und within-subject Varianz ist im Output ersichtlich, kann aber auch extrahiert werden mit\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprint(VarCorr(m.4rep),comp=\"Variance\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups   Name        Variance\n subject  (Intercept)  97.31  \n Residual             333.95  \n```\n\n\n:::\n:::\n\n\n\n\nDie geschätzte within-subject (within-unit) Korrelation -- also die Intraklassenkorrelation -- ist:\n\n$\\widehat{\\Cor}(Y_{ij},Y_{ij'})=\\frac{\\hat{\\sigma}^2_{U}}{\\hat{\\sigma}^2_{U}+\\hat{\\sigma}^2_{\\epsilon}}=0.2256404$\n\n<!-- ```{r } -->\n<!-- pie(v$percent,labels=c(\"Subject\",\"Residual\")) -->\n<!-- ``` -->\n\nWir schauen uns noch den Tukey-Anscombe- und den Q-Q Plot an. Die Varianz der Residuen sollte homogen sein und sie sollten normalverteilt sein. \n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(m.4rep,type=c(\"p\",\"smooth\"))\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-38-1.png){fig-align='center' width=480}\n:::\n\n```{.r .cell-code}\nqqnorm(residuals(m.4rep))\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-38-2.png){fig-align='center' width=480}\n:::\n:::\n\nEs gibt hier keine klare Evidenz gegen die Modellannahmen. \n\nIm `summary()`-Output sehen wir die geschätzten Zeiteffekte relativ zur Referenzkategorie. Wenn wir alle paarweisen Kontraste wollen (mit Konfidenzintervallen), können wir wieder `emmeans` brauchen.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(emmeans(m.4rep,revpairwise~time,infer=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n time emmean   SE   df lower.CL upper.CL t.ratio p.value\n t1     26.6 4.64 65.9     17.3     35.9   5.724 <0.0001\n t2     39.0 4.64 65.9     29.7     48.3   8.402 <0.0001\n t3     44.7 4.64 65.9     35.4     54.0   9.623 <0.0001\n t4     36.9 4.64 65.9     27.6     46.2   7.946 <0.0001\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n\n$contrasts\n contrast estimate   SE df lower.CL upper.CL t.ratio p.value\n t2 - t1     12.43 5.78 57    -2.86    27.73   2.151  0.1495\n t3 - t1     18.11 5.78 57     2.81    33.40   3.133  0.0141\n t3 - t2      5.67 5.78 57    -9.62    20.97   0.982  0.7604\n t4 - t1     10.32 5.78 57    -4.98    25.61   1.786  0.2908\n t4 - t2     -2.11 5.78 57   -17.41    13.18  -0.366  0.9831\n t4 - t3     -7.79 5.78 57   -23.08     7.51  -1.348  0.5370\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \nConf-level adjustment: tukey method for comparing a family of 4 estimates \nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Within-Between-subject Design\n\nWir kommen jetzt zu einem Design, das in den Gesundheitswissenschaften häufig ist. Wir haben jetzt einen between-subject Faktor `group` $G$ und eine within-subject Variable `time` $T$.\n\nEs werden also z.B. zwei Gruppen $A$ und $B$ (Levels des between-subject Faktors `group`) über die Zeit (within) beobachtet. Im Folgenden behandeln wir aber `time` nicht als Faktor, sondern als eine kontinuierliche Eingangsgrösse. `time` $T$ könnte aber auch als Faktor behandelt werden (Zeitpunkt statt Zeit).\n\n\n\n### Modellstruktur\n\nWir haben jetzt einen linearen Prädiktor mit vier Parametern $\\beta_0,\\dots,\\beta_3$, da jede Gruppe eine Lage und eine Steigung bezüglich Zeit hat. Das Random Intercept Modell schreiben wir\n$$\nY_{ij}=\\underbrace{\\beta_0+\\beta_1 G_{ij} + \\beta_2 T_{ij}+\\beta_3 GT_{ij}}_{fixed}+\\underbrace{\\overbrace{U_i}^{rand.intercept}+\\overbrace{\\epsilon_{ij}}^{resid.error}}_{random}\n$${#eq-SPRI}\n\n\nmit\n\n$$G_{ij}=\\begin{cases} 1 &\\mbox{if }group=B\\\\\n0 & \\mbox{if } group=A  \\end{cases}, \\qquad GT_{ij}=\\begin{cases} T_{ij} &\\mbox{if }group=B\\\\\n0 & \\mbox{if } group=A  \\end{cases}\n$$\n\n**Marginale Erwartung**: Schauen wir uns die Erwartungswerte an. Für die **marginale Erwartung** haben wir -- da alle random effects im Schnitt Null sind -- einfach den linearen Prädiktor $\\beta_0+\\beta_1 G_{ij} + \\beta_2 T_{ij}+\\beta_3 GT_{ij}$. Für Gruppe $A$ und $B$ gibt das:\n\n$$\n\\begin{align}\nA: E(Y_{ij})=&\\beta_0+ \\beta_2 T_{ij}\\\\\nB: E(Y_{ij})=&(\\beta_0+\\beta_1) + (\\beta_2+\\beta_3)T_{ij}\\\\\n\\end{align}\n$$\n\nWir sehen hier schön, dass jede Gruppe eine eigene Lage und eine eigene Steigung hat. Der Parameter von Interesse ist häufig der **Interaktionsparameter**$\\beta_3$. Dieser ist als **Unterschied der Steigungen zwischen den beiden Gruppen** zu interpretieren.\nInteraktion bedeutet: Der Effekt von `group` ist dann $\\beta_1+\\beta_3 T$, also eine Funktion der Zeit! Oder: Der Effekt von `time` ist dann $\\beta_2+\\beta_3 G$, also eine Funktion der Gruppe!\n\nDie $U_i$'s interessieren häufig nicht, sie müssen aber im Modell sein, um der Korrelationsstruktur der Daten Rechnung zu tragen. \n\nEine Erweiterung des Modells ist das **Random Slope Modell**, dieses erlaubt zusätzlich zum Random Intercept Modell noch unterschiedliche Slopes (also unterschiedliche Zeiteffekte) für jedes Subject. Das Random Slope Modell schreiben wir\n$$\nY_{ij}=\\underbrace{\\beta_0+\\beta_1 G_{ij} + \\beta_2 T_{ij}+\\beta_3 GT_{ij}}_{fixed}+\\underbrace{\\overbrace{U_{i0}}^{rand.intercept}+T_{ij}\\overbrace{U_{i1}}^{rand.slope}+\\overbrace{\\epsilon_{ij}}^{resid.error}}_{random}\n$${#eq-SPRS}\n\nDie Interpretation der Fixed Effects ist analog. Das Modell erlaubt aber noch unterschiedliche Slopes bezüglich `time`. Jedes Subject hat dann eine eigene Lage und eine eigene Steigung.\n\n\n<!-- **Bedingte Erwartung** (für die Interessierten) -->\n\n<!-- - Random Intercept -->\n<!-- $$ -->\n<!-- \\begin{align} -->\n<!-- A: E(Y_{ij}|U_i)=&\\beta_0+ \\beta_2 T_{ij}+U_i\\\\ -->\n<!-- B: E(Y_{ij}|U_i)=&(\\beta_0+\\beta_1) + (\\beta_2+\\beta_3)T_{ij}+U_i -->\n<!-- \\end{align} -->\n<!-- $$ -->\n\n<!-- - Random slope -->\n<!-- $$ -->\n<!-- \\begin{align} -->\n<!-- A: E(Y_{ij}|U_{i0},U_{i1})=&\\beta_0+ \\beta_2 T_{ij}+U_{i0}+T_{ij}U_{i1}\\\\ -->\n<!-- B: E(Y_{ij}|U_{i0},U_{i1})=&(\\beta_0+\\beta_1) + (\\beta_2+\\beta_3)T_{ij}+U_{i0}+T_{ij}U_{i1} -->\n<!-- \\end{align} -->\n<!-- $$ -->\n\n\n\n\n### Simulation von Daten aus Modell*\n\nFür die Interessierten: Mit dem folgenden Code simulieren wir Daten aus dem besprochenen Design: Wir simulieren den Verlauf von $n=100$ statistischen Einheiten aus zwei Gruppen $A$ und $B$. Jede Einheit hat vier Beobachtungen über die Zeit. Die abhängige Variable ist $Y$. Natürlich kennen wir bei realen Daten die wahren Parameter nicht, aber es lohnt sich, Daten aus einem Modell zu simulieren und dann die Analyse zu machen. Dies ist sehr hilfreich für das Verständnis des Designs, des Modells und schliesslich der Anlayse.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimulate <- function(seed=62) {\n    n <-100  # number of subjects\n    K <- 4  # number of measurements per subject\n    # data frame with the design: everyone has a baseline measurement, and then measurements at random follow-up times\n    d.SP <- data.frame(id = rep(seq_len(n), each = K), time = rep(1:K, n), group = rep(gl(2, n/2, labels = c(\"A\", \"B\")), each = K))\n    # design matrices for the fixed and random effects\n    X <- model.matrix(~group * time, data = d.SP)\n    Z_base <- cbind(1, d.SP$time[1:K])  # intercept and time columns for one subject\n    Z <- kronecker(diag(n), Z_base)   # Block-diagonal matrix for all subjects\n    beta <- c(10, 3, 1, 4)  # fixed effects coefficients\n    ##\n    var_intercept <- 1           # variance of random intercepts\n    var_slope <- 1               # variance of random slopes\n    correlation <- 0             # correlation between intercept and slope\n    D <- matrix(c(var_intercept, correlation * sqrt(var_intercept * var_slope),\n                       correlation * sqrt(var_intercept * var_slope), var_slope), nrow=2)\n    sigma <- 2  # sd error terms\n    # Simulate random effects for intercept and slope\n    set.seed(seed)\n    B <- MASS::mvrnorm(n, rep(0, ncol(Z_base)), D)\n    b <- as.vector(t(B))\n    # linear predictor\n    eta <- X %*% beta + Z%*%b\n    # we simulate continuous longitudinal data\n    d.SP$y <- rnorm(n * K, mean = eta, sd = sigma)\n    list(data=d.SP,parms=list(random=data.frame(varInt=1,varSlope=1,Corr=0),fixed=data.frame(beta0=10,beta1=3,beta2=1,beta3=4),sigma2=sigma^2))\n}\nsimSP<-simulate()\nd.SP<-simSP$data\n```\n:::\n\n\n### Design und Daten\n\nWir haben ein `group`(2) $\\times$ `time`(4) between-within Design (auch Split-Plot Design), mit $n=100$ (50 pro Gruppe mit je vier Beobachtungen). Wir behandeln Zeit als eine kontinuierliche Eingangsgrösse! \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstr(d.SP)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t400 obs. of  4 variables:\n $ id   : int  1 1 1 1 2 2 2 2 3 3 ...\n $ time : int  1 2 3 4 1 2 3 4 1 2 ...\n $ group: Factor w/ 2 levels \"A\",\"B\": 1 1 1 1 1 1 1 1 1 1 ...\n $ y    : num  12.5 12.9 13.7 18.8 10.2 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nwith(d.SP,xtabs(~group+time))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     time\ngroup  1  2  3  4\n    A 50 50 50 50\n    B 50 50 50 50\n```\n\n\n:::\n:::\n\n\nDa wir die Daten aus einem Modell simuliert haben, kennen wir hier die wahren Werte der Parameter. Unter `$fixed` sehen wir die wahren Parameter der fixed effects. Unter `$random` sehen wir die wahre Varianz der Random Intercepts, der Random Slopes und die Korrelation dieser (die wir auf Null gesetzt haben). Unter `$sigma2` sehen wir die Residualvarianz.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimSP$parms\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$random\n  varInt varSlope Corr\n1      1        1    0\n\n$fixed\n  beta0 beta1 beta2 beta3\n1    10     3     1     4\n\n$sigma2\n[1] 4\n```\n\n\n:::\n:::\n\n\nDie (aus dem bekannten Modell simulierten) Daten im Long Format (400 Zeilen) sind dann\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npsych::headTail(d.SP,4,4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     id time group     y\n1     1    1     A 12.48\n2     1    2     A 12.93\n3     1    3     A 13.71\n4     1    4     A 18.82\n... ...  ...  <NA>   ...\n397 100    1     B 16.04\n398 100    2     B  22.9\n399 100    3     B 29.33\n400 100    4     B 32.19\n```\n\n\n:::\n:::\n\n\nund im Wide Format (100 Zeilen), oft nützlich für deskriptive Statistik:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd.SPwide<-reshape(d.SP,v.names=\"y\",timevar=\"time\",idvar=\"id\",direction=\"wide\")\npsych::headTail(d.SPwide,4,4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     id group   y.1   y.2   y.3   y.4\n1     1     A 12.48 12.93 13.71 18.82\n5     2     A 10.16 14.46  9.18 14.67\n9     3     A  7.27  9.44  6.97  6.88\n13    4     A 17.14 15.11 16.96 15.81\n... ...  <NA>   ...   ...   ...   ...\n385  97     B 16.94 21.71 20.28 31.72\n389  98     B 19.42 20.78 32.12 34.45\n393  99     B 19.31 25.29  31.9 31.84\n397 100     B 16.04  22.9 29.33 32.19\n```\n\n\n:::\n:::\n\n\n\n\n\n### Beschreiben\n\nHier wieder mit mehreren Varianten:\n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nwith(d.SP,interaction.plot(x.factor=time,trace.factor=group,response=y))\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-45-1.png){fig-align='center' width=480}\n:::\n\n```{.r .cell-code}\nlattice::xyplot(data = d.SP, y ~ time | group,groups = id, type = \"l\")\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-45-2.png){fig-align='center' width=480}\n:::\n:::\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntapply(d.SP$y, list(d.SP$group,d.SP$time), mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         1        2        3        4\nA 11.10430 12.43844 13.20379 14.75693\nB 18.07467 23.24057 28.65372 34.07037\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npsych::describeBy(d.SP$y, list(d.SP$group,d.SP$time), mat = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     item group1 group2 vars  n mean       sd median trimmed     mad min max\nX1*1    1      A      1    1 50 25.5 14.57738   25.5    25.5 18.5325   1  50\nX1*2    2      B      1    1 50 25.5 14.57738   25.5    25.5 18.5325   1  50\nX1*3    3      A      2    1 50 25.5 14.57738   25.5    25.5 18.5325   1  50\nX1*4    4      B      2    1 50 25.5 14.57738   25.5    25.5 18.5325   1  50\nX1*5    5      A      3    1 50 25.5 14.57738   25.5    25.5 18.5325   1  50\nX1*6    6      B      3    1 50 25.5 14.57738   25.5    25.5 18.5325   1  50\nX1*7    7      A      4    1 50 25.5 14.57738   25.5    25.5 18.5325   1  50\nX1*8    8      B      4    1 50 25.5 14.57738   25.5    25.5 18.5325   1  50\n     range skew  kurtosis       se\nX1*1    49    0 -1.272202 2.061553\nX1*2    49    0 -1.272202 2.061553\nX1*3    49    0 -1.272202 2.061553\nX1*4    49    0 -1.272202 2.061553\nX1*5    49    0 -1.272202 2.061553\nX1*6    49    0 -1.272202 2.061553\nX1*7    49    0 -1.272202 2.061553\nX1*8    49    0 -1.272202 2.061553\n```\n\n\n:::\n:::\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naggregate(y~time+group,data=d.SP,summary)##Alternative\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  time group    y.Min. y.1st Qu.  y.Median    y.Mean y.3rd Qu.    y.Max.\n1    1     A  6.086921  9.327115 10.600989 11.104296 12.848087 17.608980\n2    2     A  7.400169 10.410568 12.740514 12.438442 14.324042 17.327829\n3    3     A  3.591481 10.185784 13.058277 13.203787 16.477755 21.812738\n4    4     A  6.877855 11.556186 14.380528 14.756929 17.703400 22.928708\n5    1     B 13.001167 17.025762 18.298287 18.074673 19.320991 22.855254\n6    2     B 17.528504 21.137155 22.842381 23.240574 25.285105 31.719640\n7    3     B 20.279260 25.879617 28.568727 28.653717 31.480437 38.704880\n8    4     B 24.810750 31.304031 33.857658 34.070374 36.346075 45.635979\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntapply(d.SPwide,d.SPwide$group,summary)##mit d.SPwide\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$A\n       id        group       y.1              y.2             y.3        \n Min.   : 1.00   A:50   Min.   : 6.087   Min.   : 7.40   Min.   : 3.591  \n 1st Qu.:13.25   B: 0   1st Qu.: 9.327   1st Qu.:10.41   1st Qu.:10.186  \n Median :25.50          Median :10.601   Median :12.74   Median :13.058  \n Mean   :25.50          Mean   :11.104   Mean   :12.44   Mean   :13.204  \n 3rd Qu.:37.75          3rd Qu.:12.848   3rd Qu.:14.32   3rd Qu.:16.478  \n Max.   :50.00          Max.   :17.609   Max.   :17.33   Max.   :21.813  \n      y.4        \n Min.   : 6.878  \n 1st Qu.:11.556  \n Median :14.381  \n Mean   :14.757  \n 3rd Qu.:17.703  \n Max.   :22.929  \n\n$B\n       id         group       y.1             y.2             y.3       \n Min.   : 51.00   A: 0   Min.   :13.00   Min.   :17.53   Min.   :20.28  \n 1st Qu.: 63.25   B:50   1st Qu.:17.03   1st Qu.:21.14   1st Qu.:25.88  \n Median : 75.50          Median :18.30   Median :22.84   Median :28.57  \n Mean   : 75.50          Mean   :18.07   Mean   :23.24   Mean   :28.65  \n 3rd Qu.: 87.75          3rd Qu.:19.32   3rd Qu.:25.29   3rd Qu.:31.48  \n Max.   :100.00          Max.   :22.86   Max.   :31.72   Max.   :38.70  \n      y.4       \n Min.   :24.81  \n 1st Qu.:31.30  \n Median :33.86  \n Mean   :34.07  \n 3rd Qu.:36.35  \n Max.   :45.64  \n```\n\n\n:::\n:::\n\n\n\n\n\n\n### Modelle anpassen\n\nWir haben als fixed effects: `group`, `time` und  `group:time`-Interaktion. Wir haben zwei verschiedene Random-Effects Strukturen `(1|subject)` (für das random intercept Modell) und  `(time|subject)` (für das random slope Modell):\n\n1. Random intercept model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1 <- lmer(y ~ group * time + (1 | id), data = d.SP)\n```\n:::\n\n2. Random slope. Schätzt zusätzlich die Varianz der Slopes und die Kovarianz Intercept-Slopes. Syntax: `time|id`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm2 <- lmer(y ~ group * time + (time | id), data = d.SP)\n```\n:::\n\n\n\n\n\n### Angepasste Modelle\n\n#### Random Intercept\n\nVersuchen Sie, die Parameterschätzungen der festen Effekte unten in der rechten Graphik nachzuvollziehen. So ist z.B. $\\hat{\\beta}_3=4.1677004$ der geschätzte erwartete Unterschied in der Steigung zwischen Gruppe $A$ und $B$, $\\hat{\\beta}_2=1.1723243$ ist die geschätzte erwartete Steigung für Gruppe $A$, usw. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m1, cor = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: y ~ group * time + (1 | id)\n   Data: d.SP\n\nREML criterion at convergence: 1985.8\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.97793 -0.54881  0.00251  0.58228  2.78736 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n id       (Intercept) 6.778    2.603   \n Residual             5.342    2.311   \nNumber of obs: 400, groups:  id, 100\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)   9.9451     0.5439 266.3516  18.285  < 2e-16 ***\ngroupB        2.7147     0.7692 266.3517   3.529 0.000491 ***\ntime          1.1723     0.1462 298.0000   8.020 2.44e-14 ***\ngroupB:time   4.1677     0.2067 298.0000  20.161  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\npredicted <- predict(m1)\nlattice::xyplot(data = d.SP, y ~ time | group,groups = id, type = \"l\",main=\"Daten\")\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-55-1.png){fig-align='center' width=480}\n:::\n\n```{.r .cell-code}\nlattice::xyplot(data = d.SP, predicted ~ time | group, groups = id, type = \"l\",main=\"Modell\")\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-55-2.png){fig-align='center' width=480}\n:::\n:::\n\n\n#### Random Slope\n\nFür das random slope Modell sehen wir zusätzlich eine Variabilität in den Steigungen für jede statistische Einheit. Die Punktschätzungen für die fixed effects bleiben aber gleich. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m2, cor = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: y ~ group * time + (time | id)\n   Data: d.SP\n\nREML criterion at convergence: 1908.9\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-2.9705 -0.5587  0.0275  0.5456  2.2772 \n\nRandom effects:\n Groups   Name        Variance Std.Dev. Corr  \n id       (Intercept) 1.600    1.265          \n          time        1.015    1.007    -0.12 \n Residual             3.673    1.917          \nNumber of obs: 400, groups:  id, 100\n\nFixed effects:\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)   9.9451     0.3771 97.9991  26.374  < 2e-16 ***\ngroupB        2.7147     0.5333 97.9991   5.091 1.73e-06 ***\ntime          1.1723     0.1871 98.0009   6.267 9.87e-09 ***\ngroupB:time   4.1677     0.2645 98.0009  15.755  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\npredicted <- predict(m2)\nlattice::xyplot(data = d.SP, y ~ time | group,groups = id, type = \"l\",main=\"Daten\")\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-57-1.png){fig-align='center' width=480}\n:::\n\n```{.r .cell-code}\nlattice::xyplot(data = d.SP, predicted ~ time | group, groups = id, type = \"l\",main=\"Modell\")\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-57-2.png){fig-align='center' width=480}\n:::\n:::\n\n\nBeim Random Slope Modell ist die Varianz des zufälligen Beitrags eine quadratische Funktion der Zeit, also nicht mehr konstant wie beim Random Intercept Modell. Die zufällige Komponente für Zeit $T$ ist $U_{i0} + U_{i1} \\cdot T$ und die Varianz\n\n$$\n\\begin{align}\n\\text{Var}(U_{i0} + U_{i1} \\cdot T)\n&= \\text{Var}(U_{i0}) + T^2 \\text{Var}(U_{i1}) + 2T \\,\\text{Cov}(U_{i0}, U_{i1})\\\\\n&= \\sigma^2_0 + T^2 \\sigma^2_1 + 2T \\sigma_{01}.\n\\end{align}\n$$\n\n\n\n\n\n#### Testen von Random Effects \n\nModell `m1` ist ja verschachtelt im Modell `m2`. Wir können also die Hypothese testen, dass die Variabilität der random slopes Null ist:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(m1, m2,refit=FALSE) #damit REML wie lmerTest::ranova()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: d.SP\nModels:\nm1: y ~ group * time + (1 | id)\nm2: y ~ group * time + (time | id)\n   npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nm1    6 1997.8 2021.7 -992.89    1985.8                         \nm2    8 1924.9 1956.8 -954.44    1908.9 76.908  2  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\noder \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlmerTest::ranova(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nANOVA-like table for random-effects: Single term deletions\n\nModel:\ny ~ group * time + (time | id)\n                    npar  logLik    AIC    LRT Df Pr(>Chisq)    \n<none>                 8 -954.44 1924.9                         \ntime in (time | id)    6 -992.89 1997.8 76.908  2  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nDas Random Intercept Modell wird also zugunsten des Random Slope Modells verworfen.\n\n\n#### Caterpillar Plot von Random Effects\n\nIm Output hatten wir bis jetzt **Varianzparameter**, nicht die Random Effects selber. Die geschätzten zufälligen Effekte (**Best linear unbiased predictions (BLUPs)**) für jedes Subjekt im Modell, dargestellt als Punktdiagramm bekommen wir mit \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndotplot.ranef.mer(ranef(m2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$id\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-60-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n\n\n\n\n### Testen von Fixed Effects\n\nDas Hauptinteresse liegt meistens im Testen der fixed effects. Zuerst der Interaktionseffekt:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndrop1(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSingle term deletions using Satterthwaite's method:\n\nModel:\ny ~ group * time + (time | id)\n           Sum Sq Mean Sq NumDF  DenDF F value    Pr(>F)    \ngroup:time 911.66  911.66     1 98.001  248.21 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n`drop1()` testet richtigerweise nur die Interaktion. Haupteffekte sollten in der Gegenwart von Interaktion nicht getestet werden. \n\n**Type III Tests**: Macht man es trotzdem, muss man sogenannte Type III Tests und den Zusammenhang mit der Default-Effektkodierung sehr gut verstehen. Wir gehen hier nicht näher darauf ein. Die Funktion `anova.lmerModLmerTest()` aus `lmerTest` macht diese Tests korrekt bei Aufruf von `anova()` und Übergabe eines `lmer`-Objekts und ist unabhängig von der Parametrisierung (im Gegensatz zu `car::Anova(...,type=3)`). \n\n\n\n### Trends und Kontraste von Trends \n\nDie Effektparameterisierung gab uns für die fixed effects:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m2)$coef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error       df   t value     Pr(>|t|)\n(Intercept) 9.945053  0.3770772 97.99907 26.374053 2.650478e-46\ngroupB      2.714720  0.5332676 97.99908  5.090727 1.725057e-06\ntime        1.172324  0.1870577 98.00087  6.267181 9.871747e-09\ngroupB:time 4.167700  0.2645395 98.00088 15.754548 1.313324e-28\n```\n\n\n:::\n:::\n\n\nWir wollen jetzt eine Schätzung für die Zeiteffekte in beiden Gruppen $A$ und $B$ und eine Schätzung des Unterschieds des Zeiteffekts zwischen Gruppe $A$ und $B.$ Dies bekommen wir die mit `emmeans::emtrends()`\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(emmeans::emtrends(m2,trt.vs.ctrl~group,var=\"time\"),infer=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emtrends\n group time.trend    SE df lower.CL upper.CL t.ratio p.value\n A           1.17 0.187 98    0.801     1.54   6.267 <0.0001\n B           5.34 0.187 98    4.969     5.71  28.547 <0.0001\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n\n$contrasts\n contrast estimate    SE df lower.CL upper.CL t.ratio p.value\n B - A        4.17 0.265 98     3.64     4.69  15.755 <0.0001\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\nDie Gruppe $B$ verändert sich pro Zeiteinheit um 4.17 Einheiten auf $Y$ mehr als die Gruppe $A$. Eine Schätzung der Steigung in der Gruppe $A$ und vom Unterschied in den Steigungen zwischen den Gruppen hatten wir schon in der Effektparameterisierung. Die Steigung in der Gruppe $B$ ist 5.34, das entspricht in der Grundparametrisierung 1.172+4.168.\n\n\n\n\n### Modellannahmen\n\nDas Testen von Modellannahmen ist oft nicht trivial. Es lohnt sich diesbezüglich bei Bedarf Hilfe zu holen. \n\nHier gibt es keine Evidenz gegen die Modellannahmen. Das wäre auch erstaunlich, haben wir doch die Daten aus demselben Modell simuliert, welches wir dann an die Daten angepasst haben.\n\nStreuung Residuen\n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(m2,resid(.)~fitted(.)|group)\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-64-1.png){fig-align='center' width=960}\n:::\n\n```{.r .cell-code}\nplot(m2,resid(.)~fitted(.)|group*time)\n```\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-64-2.png){fig-align='center' width=960}\n:::\n:::\n\n\n\nStreuung und Verteilung Random effects\n\n\n::: {.cell layout=\"[[1,1,1],[1,1,1]]\" layout-align=\"center\"}\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-65-1.png){fig-align='center' width=480}\n:::\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-65-2.png){fig-align='center' width=480}\n:::\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-65-3.png){fig-align='center' width=480}\n:::\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-65-4.png){fig-align='center' width=480}\n:::\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-65-5.png){fig-align='center' width=480}\n:::\n\n::: {.cell-output-display}\n![](12_LMM_files/figure-html/unnamed-chunk-65-6.png){fig-align='center' width=480}\n:::\n:::\n\n\n\n\n<!-- ## Software {.smaller50} -->\n\n<!-- ```{r echo=FALSE} -->\n<!-- library(grateful) -->\n<!-- cite_packages(pkgs = \"Session\",output=\"table\",out.dir=getwd(),cite.tidyverse=FALSE,omit=c(\"grateful\",\"knitr\")) -->\n<!-- ``` -->\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "12_LMM_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}