{
  "hash": "d3e8474b23f23c907c093f66aa65cd63",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n# Verteilungen von Wahrscheinlichkeiten {#sec-verteilung-von-wahrscheinlichkeiten}\n\n> Es gehört zur Wahrscheinlichkeit, dass viele unwahrscheinliche Dinge geschehen werden.\n>\n> --- Aristoteles\n\n## Lernziele\n\n::: callout-important\n1.  Definiere eine **Zufallsvariable** als Beobachtungsmerkmal, dessen Ausprägung variiert und daher nicht exakt vorhergesagt werden kann.\n\n2.  Interpretiere die **Wahrscheinlichkeitsverteilung** einer Variable als Modell, das sich auf eine Grundpopulation bezieht.\n\n3.  Beachte, dass die **Wahrscheinlichkeit** $P$ für ein Ereignis stets zwischen 0% und 100% liegt. $P$ kann daher nur Werte zwischen 0 und 1 annehmen.\n\n4.  Interpretiere die **Binomialverteilung** als diskrete Verteilung und zwar als Wahrscheinlichkeitsverteilung für die Zufallsvariable \"Anzahl Erfolge/Misserfolge\" (Eintreten eines bestimmten Ereignisses) bei $n$ unabhängigen Versuchen.\n\n    -   Verwende die Binomialverteilung, um die Wahrscheinlichkeit für genau $x$, maximal $x$ oder mehr als $x$ Erfolge bei $n$ unabhängigen Versuchen bei gegebener Erfolgswahrscheinlichkeit $\\pi$ zu berechnen.\n\n5.  Interpretiere die **Normalverteilung** als eine kontinuierliche/stetige Verteilung.\n\n6.  In kontinuierlichen Verteilungen ist die Wahrscheinlichkeit für ein ganz bestimmtes Ereignis stets Null. Es ist aber möglich Wahrscheinlichkeiten für Wertebereiche (Intervalle) zu berechnen.\n\n7.  Die Normalverteilung ist symmetrisch um den Mittelwert und kann durch die Parameter Mittelwert $\\mu$ und Standardabweichung $\\sigma$ vollständig beschrieben werden. Mittelwert und Median sind in diesem Fall identisch.\n\n8.  Interpretiere die **Standardnormalverteilung** als eine Normalverteilung mit dem Mittelwert $\\mu = 0$ und der Standardabweichung $\\sigma = 1$.\n\n9.  Jede Normalverteilung kann durch $z$-Transformation in die Standardnormalverteilung umgewandelt werden.\n\n10. Interpretiere den $z$-Wert als Abstand eines Wertes vom Mittelwert in Anzahl Standardabweichungen. Punkte mit negativen $z$-Werten liegen links vom Mittelwert und Punkte mit positiven $z$-Werten liegen rechts vom Mittelwert.\n\n\n$$Z=\\frac{X - \\mu}{\\sigma}$$\n\n1.  Verwende den $z$-Wert,\n\n    -   ... um die Quantile für $X=x$ zu bestimmen (z.B. bei der Berechnung von Konfidenzintervallen).\n\n    -   ... um zu bestimmen, ob ein Wert als ungewöhnlich beurteilt werden muss (Faustregel: $Z$ \\> \\|2\\| ist ungewöhnlich).\n\n    -   ... um Wahrscheinlichkeiten zu berechnen: $P(X \\le x)$, $P(X \\ge x)$ und $P(x \\le X \\le x)$.\n\n2.  Bei rechtsschiefen Verteilungen hat der Median einen negativen $z$-Wert.\n\n3.  Bei linksschiefen Verteilungen hat der Median einen postiven $z$-Wert.\n\n4.  Die **68-95-99.7%-Regel** ist eine Faustregel die besagt, dass unter der Normalverteilungskurve 68% der Fläche innerhalb von $\\mu \\pm \\sigma$, 95% der Fläche innerhalb von $\\mu \\pm 2 \\sigma$ und 99.7% der Fläche innerhalb von $\\mu \\pm 3 \\sigma$ liegen.\n\n5.  Beurteile anhand eines Histogramms, eines Boxplots oder eines **QQ-Plots**, ob die beobachteten Daten aus einer normalverteilten Population stammen oder nicht.\n\n6.  Interpretiere die $t$**-Verteilung** als Anpassung der Normalverteilung, wenn die Standardabweichung $\\sigma$ einer Population unbekannt ist (was fast immer der Fall ist).\n\n    -   Die Form der $t$-Verteilung ist nur abhängig vom Stichprobenumfang. Dieser wird in Freiheitsgraden $df$ angegeben, wobei $df = n-1$.\n\n    -   Ist der Stichprobenumfang $n$ \\> 30, nähert sich die Form der $t$-Verteilung der Normalverteilung an.\n\n    -   Die $t$-Verteilung wird mit dem Parameter $df$ vollständig beschrieben.\n\n    -   Interpretiere $t$-Werte, die von Statistikprogrammen angegeben werden, gleich wie $z$-Werte.\n\n7.  Erstelle QQ-Plots in `R`, um zu prüfen, ob eine Variable von einer Normalverteilung abwicht.\n:::\n\n## Zufallsvariablen\n\nEine **Zufallsvariable** ist eine numerische Grösse, deren Wert vom Ausgang eines Zufallsexperiments abhängt. Sie erlaubt es, zufällige Phänomene mathematisch zu beschreiben und statistisch zu analysieren.\n\nDie **Verteilung** einer Zufallsvariable beschreibt, mit welcher Wahrscheinlichkeit sie bestimmte Werte annimmt. Sie ist ein zentrales Konzept, um die Eigenschaften und das Verhalten der Zufallsvariable zu verstehen – etwa ob sie eher kleine oder grosse Werte liefert, ob sie symmetrisch verteilt ist, usw.\n\n## Wahrscheinlichkeitsverteilungen\n\nEine Wahrscheinlichkeitsverteilung ist eine mathematische Funktion (ein Modell), welche die Wahrscheinlichkeiten für alle möglichen Werte einer Zufallsvariablen beschreibt.\n\nDas tönt recht technisch, ist aber anhand von einem Beispiel leicht zu verstehen: Stellen Sie sich vor, Sie möchten wissen, wie gross Ihre Kolleginnen in der Klasse sind. Dazu messen Sie von jeder Person die Körpergrösse und stellen fest, dass gewisse Körpergrössen häufig und andere eher selten sind. Wahrscheinlichkeitsverteilungen helfen, wenn es darum geht zu verstehen, welche Merkmalsausprägungen eher häufig und welche eher selten zu erwarten sind. Sie erlauben auch die Beantwortung von Fragen wie: \"Wie gross ist die Wahrscheinlichkeit, dass die nächste Person, die ich messe, grösser als zwei Meter ist?\".\n\nIn der deskriptiven Statistik haben wir bereits Verteilungen von Zufallsvariablen kennen gelernt: Sie lassen sich durch Form (symmetrisch, links- oder rechtsschief, irregulär), Kennzahlen der zentralen Tendenz und Kennzahlen der Streuung beschreiben.\n\n> Beachte, dass Histogramme, Boxplots und Streudiagramme die Verteilung von Stichprobendaten beschreiben (empirische Verteilung), während Wahrscheinlichkeitsverteilungen Modelle für die theoretische Verteilung von Daten sind.\n\nIn der mathematischen Schreibweise wird die Wahrscheinlichkeit, dass $X$ einen Wert $x$ annimmt, geschrieben als\n\n$$P(X = x) = [0, 1] = Zahl~zwischen~0~und~1.$$\n\nDie Summe der Wahrscheinlichkeiten für alle möglichen Werte von $X$ ist stets 1. Ausserdem ist die Wahrscheinlichkeit für einen bestimmten Wert zwischen 0 (0%) und 1 (100%). Wenn wir also eine Münze werfen, dann ist die Wahrscheinlichkeit\n\n$$P(X = Kopf) = 0.5,$$\n\n$$P(X = Zahl) = 0.5.$$\n\nWobei 0.5 die Wahrscheinlichkeit für den Wert {$Kopf, Zahl$} ist. Eine andere Möglichkeit für $X$ existiert nicht. Die Summe aller möglichen Werte für $X$ bei einem Münzwurf ist daher\n\n$$P(X = Kopf \\cup X = Zahl) = P(Kopf) + P(Zahl) = 1.$$\n\nHinweis: $\\cup$ steht für ein mathematisches *oder*, $\\cap$ für ein mathematisches *und.* Weil in diesem Fall Kopf und Zahl disjunkt sind, das heisst nicht zusammen eintreffen können, ist $P(X = Kopf \\cap X = Zahl) = 0$.\n\nWahrscheinlichkeitsverteilungen beschreiben also die theoretische Verteilung der Werte (Merkmalsausprägungen) einer bestimmten Zufallsvariable (Beobachtungsmerkmal). Daher ist es naheliegend, dass die Art der Variable einen Einfluss auf den Verteilungstyp hat. In der Statistik unterscheidet man zwischen\n\n-   Verteilungen für diskrete Variablen (z.B. Binomialverteilung) und\n-   Verteilungen für kontinuierliche/stetige Variablen (z.B. Normalverteilung).\n\nSie werden in diesem Kurs einigen Verteilungen begegnen. Für die reine Anwendung ist es jedoch nicht nötig, alle diese Verteilungen im Detail zu kennen. Wir beschränken uns darum im Folgenden auf die Binomialverteilung (eine Wahrscheinlichkeitsverteilung für diskrete Variablen) und die Normalverteilung (eine Wahrscheinlichkeitsverteilung für stetige Variablen). Wenn Sie das Konzept dieser beiden Wahrscheinlichkeitsverteilungen verstanden haben und damit rechnen können, dann sind diese Kenntnisse einfach auf weitere Verteilungen (wie z.B. die $t$-Verteilung oder die Poissonverteilung) übertragbar.\n\n## Die Binomialverteilung\n\nWie wahrscheinlich ist es, in zwei Würfen von Würfeln genau eine 6 zu würfeln? Diese vermeintlich einfache Frage kann mit Hilfe der Binomialverteilung beantwortet werden (wenn Sie meinen, die Antwort ist $\\frac{2}{6} = \\frac{1}{3}$, dann liegen Sie falsch). Die Binomialverteilung gibt die Wahrscheinlichkeit für $x$ Erfolge bei $n$ unabhängigen Versuchen und einer Erfolgswahrscheinlichkeit $\\pi$ an. Im genannten Beispiel ist unsere Zufallsvariable $X$ Binomialverteilt mit $n = 2$ (zwei Würfe) und $\\pi = \\frac{1}{6}$ (wir gehen von einem fairen Würfel aus).\\\nEtwas formaler: $$X \\sim Binomial(n, \\pi).$$\\\nAus Zeitgründen (und nicht weil es zu schwierig wäre), verzichten wir auf die Formel und die manuelle Berechnung. Unsere Frage $P(X = 1)$, also genau einen 6er in zwei Würfen, können wir mit R einfach beantworten:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# dbinom gibt uns die Wahrscheinlichkeits(masse) bei X = x\ndbinom(x = 1, size = 2, prob = 1/6) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2777778\n```\n\n\n:::\n:::\n\n\nIn @fig-plot-binom-dice sehen Sie die **Wahrscheinlichkeitsverteilung** für $X \\sim Binomial(2, \\frac{1}{6}).$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Wahrscheinlichkeitsverteilung X~Bin(2, 1/6)](02_prop_distributions_files/figure-html/fig-plot-binom-dice-1.png){#fig-plot-binom-dice fig-align='center' width=480}\n:::\n:::\n\n\nDas Experiment kann also drei mögliche Ausgänge haben, wobei $P(X = 1) = 0.278 = 27.8\\%.$\n\nGerade wenn $n$ grösser wird, ist man froh, dank `R` auf eine manuelle Berechnung verzichten zu können. Wie wahrscheinlich ist es, bei $30$ Würfelwürfen genau eine $6$ zu würfeln?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndbinom(x = 1, size = 30, prob = 1/6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02527632\n```\n\n\n:::\n:::\n\n\nEs ist natürlich sehr unwahrscheinlich, bei 30 Würfen genau einen 6er zu würfeln. Wir sehen in @fig-plot-binom-dice30, dass es am wahrscheinlichsten ist, bei $30$ Würfen 5-Mal eine $6$ zu würfeln. Das macht ja auch Sinn, da wir in einem Sechstel der Fälle eine $6$ erwarten, also $30/6 = 5.$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Wahrscheinlichkeitsverteilung X~Bin(30, 1/6)](02_prop_distributions_files/figure-html/fig-plot-binom-dice30-1.png){#fig-plot-binom-dice30 fig-align='center' width=480}\n:::\n:::\n\n\nWir können mit der Binomialverteilung nicht nur $P(X = x)$ berechnen, sondern auch $P(X \\le x)$ oder $P(X > x)$. Dafür muss man einfach die entsprechenden Wahrscheinlichkeiten zusammenrechnen. Mit $n = 30$ und $\\pi = \\frac{1}{6}$ ist $P(X \\le 3) = P(X = 0) + P(X = 1) + P(X = 2) + P(X = 3)$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Aufsummieren der einzelnen Wahrscheinlichkeiten für x von 0 bis 3.\nsum(dbinom(x = c(0:3), size = 30, prob = 1/6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2396195\n```\n\n\n:::\n:::\n\n\nWeil das Aufsummieren der einzelnen Wahrscheinlichkeiten mühsam ist, gibt es eine R-Funktion, welche das für uns erledigt.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# pbinom gibt uns die Wahrscheinlichkeit für X <= x\npbinom(3, 30, 1/6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2396195\n```\n\n\n:::\n:::\n\n\nMan nennt die Funktion für $P(X \\le x)$ auch kumulative Verteilungsfunktion. Beachten Sie, dass bei solchen Berechnungen immer von links (also vom tiesten Wert her) aufsummiert wird. $P(X > 3)$ lässt sich dann einfach als Gegenwahrscheinlichkeit berechnen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Die Gegenwahrscheinlichkeit für X <= x ist X > x\n1-pbinom(3, 30, 1/6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7603805\n```\n\n\n:::\n:::\n\n\n### Anwendungsbeispiele der Binomialverteilung\n\n**Beispiel 1:** Nächste Woche findet die Versammlung eines Berufsverbandes statt. Das Komitee besteht aus 18 Personen. Die Wahrscheinlichkeit, dass ein Mitglied des Komitees zur Versammlung kommt, beträgt 70%.\n\nWie gross ist die Wahrscheinlichkeit, dass alle Mitglieder anwesend sind? Die Anzahl anwesender Personen ist binomialverteilt mit $n = 18$ und $\\pi = 0.7$, also $X\\sim Bin(18, 0.7)$. Gefragt ist $P(X = 18).$ Dies lässt sich wie folgt berechnen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndbinom(18,18,0.7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.001628414\n```\n\n\n:::\n:::\n\n\nWie gross ist die Wahrscheinlichkeit, dass eine Zweidrittelmehrheit anwesend ist?\n\nDie Anzahl anwesender Personen ist Binomialverteilt mit $n = 18$ und $\\pi = 0.7$, also $X\\sim Bin(18, 0.7)$. Gefragt ist $P(X > 11)$, also die Gegenwahrscheinlichkeit von $P(X\\leq11)$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n1-pbinom(11, 18, 0.7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7216964\n```\n\n\n:::\n:::\n\n\nDie ganze **Wahrscheinlichkeitsverteilung** zu dieser Frage ist in @fig-plot-binom-members ersichtlich. Wie bereits erwähnt, führt das Aufsummieren der Wahrscheinlichkeiten $P(X = 12) + P(X = 13) + …. + P(X = 18)$ zum gleichen Resultat von 72.17%.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Wahrscheinlichkeitsverteilung X~Bin(18, 0.7)](02_prop_distributions_files/figure-html/fig-plot-binom-members-1.png){#fig-plot-binom-members fig-align='center' width=480}\n:::\n:::\n\n\n**Beispiel 2:** Eine Labormitarbeiterin hat neue Reagenzgläser bestellt. Laut Hersteller beläuft sich der Anteil defekter Gläser auf 3%. Zur Sicherheit nimmt die Labormitarbeiterin eine Stichprobe: Sie wählt einen zufälligen Karton mit 50 Gläsern aus, darin sind 7 Gläser defekt. Wie wahrscheinlich sind 7 oder sogar noch mehr defekte Gläser, wenn die Angabe des Herstellers stimmt?\n\nDie Anzahl defekter Gläser ist Binomialverteilt mit $n = 50$ und $\\pi = 0.03$, also $X\\sim Bin(50, 0.03)$. Gefragt ist $P(X > 6)$, also die Gegenwahrscheinlichkeit von $P(X\\leq6)$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0007037346\n```\n\n\n:::\n:::\n\n\nDie Berechnung mit der Binomialverteilung legt nahe, dass die Angabe des Herstellers nicht korrekt ist. Es ist sehr unwahrscheinlich, 7 oder mehr defekte Gläser zu finden, wenn der wahre Anteil defekter Gläser wirklich 3% sein sollte. Um die Fragestellung der Labormitarbeiterin abschliessend zu klären, ist ein statistischer Test nötig (siehe nächstes Kapitel).\n\n## Die Normalverteilung\n\nWenn eine Variable innerhalb eines Bereichs unendlich viele Werte annehmen kann, wird diese mittels einer kontinuierlichen Verteilung modelliert.\n\nMathematisch ausgedrückt ist die Wahrscheinlichkeit, dass eine kontinuierliche Variable einen ganz bestimmten Wert annimmt gleich null:\n\n$$P(X = x) = 0$$\n\nZ.B. die Wahrscheinlichkeit, dass eine Temperaturmessung exakt 37° C ergibt ist gleich null. Warum? In einem unendlichen Wertespektrum kann die aktuelle Temperatur unendlich viele kleinere oder grössere Werte annehmen, z.B. 36.99999999 oder 36.999999998 oder 37.000000001 etc. (es sind unendlich viele Nachkommastellen möglich).\n\n### Wahrscheinlichkeiten für kontinuierliche Daten\n\nDa es unmöglich ist, die Wahrscheinlichkeit für einen bestimmten Wert in einem kontinuierlichen Datenspektrum anzugeben, werden Wahrscheinlichkeiten für kontinuierliche Daten für Wertebereiche (Werteintervalle) berechnet und nicht für einzelne Werte. Was berechnet werden kann, ist die Wahrscheinlichkeit, dass ein gesuchter Wert in einem bestimmten Intervall liegt, z.B. $P(X\\le x)$ oder $P(a \\le X \\le b)$.\n\nIn einem Wahrscheinlichkeitsdiagramm ist die Fläche unter der Kurve gleich 1 (@fig-plot-normal-curve ). Dies entspricht der Summe der Wahrscheinlichkeiten für alle möglichen Ausprägungen einer kontinuierlichen Variablen $X$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Die Fläche unter der Kurve ist gleich 1](02_prop_distributions_files/figure-html/fig-plot-normal-curve-1.png){#fig-plot-normal-curve fig-align='center' width=480}\n:::\n:::\n\n\nIn der Statistik nimmt die Normalverteilung (auch Gauss-Verteilung, Glockenkurve) eine zentrale Stellung ein. Diese symmetrische Wahrscheinlichkeitsverteilung erlaubt es, eine Vielzahl von kontinuierlichen Variablen wie z.B. Körpergrösse oder Ergebnisse von Intelligenztests (IQ-Scores) zu modellieren.\n\nEine Normalverteilung wird durch die Parameter *Mittelwert* $\\mu$ und *die Varianz* $\\sigma^2$ (bzw. dien Standardabweichung $\\sigma$) vollständig beschrieben. Folgt eine Variable $X$ einer Normalverteilung, wird das wie folgt notiert:\n\n$$\nX \\sim N(\\mu, \\sigma^2).\n$$\n\nFür Berechnungen mit der Normalverteilung braucht man oft die Standardabeichung $\\sigma$ statt die Varianz $\\sigma^2$. Es spielt in der Praxis aber keine Rolle, ob die Varianz oder die Standardabweichung vorliegt weil $\\sigma = \\sqrt{\\sigma^2}$. Während eine Änderung des Mittelwerts die Glockenkurve nach links oder nach rechts verschiebt, führt eine Änderung der Standardabweichung dazu, dass die Kurve breiter oder schmaler wird.\n\nDie Normalverteilung von Daten ist eine wichtige Voraussetzung für zahlreiche statistische Verfahren. Üblicherweise kennt man die wahre Verteilung einer Variablen in einer Population jedoch nicht und man muss aus den Stichprobendaten ermitteln, ob Evidenz dafür vorliegt, dass die Daten aus einer normalverteilten Population stammen. Wie man dabei vorgeht, wird weiter unten beschrieben.\n\n#### Exkurs: Wahrscheinlichkeitsfunktion und Dichtefunktion {#sec-exkurs-wahrscheinlichkeitsfunktion-und-dichtefunktion}\n\nWie Sie bei der Binomialverteilung gelernt haben, kann man bei diskreten Variablen die Wahrscheinlichkeit für alle $x$ im Wertebereich von $X$ angeben. Diese Verteilung von Wahrscheinlichkeiten nennt man **Wahrscheinlichkeitsverteilung**. Die Wahrscheinlichkeit $P(X = x)$ ist gegeben durch die **Wahrscheinlichkeitsfunktion** $f(x)$. Man nennt $f(x)$ bei diskreten Variablen auch **Wahrscheinlichkeitsmasse** oder **Gewichtsfunktion**. Wir gehen in diesem Kurs nicht auf weitere Details dieser Wahrscheinlichkeitsfunktionen ein. In `R` kann man die Wahrscheinlichkeitsfunktion der Binomialverteilung durch `dbinom(x, n, p)` abrufen (siehe Kapitel zur Binomialverteilung). Nebst der Wahrscheinlichkeitsfunktion ist häufig die kumulative Wahrscheinlichkeitsfunktion $F(x) = P(X \\le x)$ von Interesse. Diese erhält man, wie bei der Binomialvertelung beschrieben, durch das Aufsummieren der einzelnen Wahrscheinlichkeiten. In `R` erhalten wir die kumulative Wahrscheinlichkeitsverteilung für $P(X \\le x)$ durch `pbinom(x, n, p)`.\n\nIn @fig-plot-binom-20 sehen Sie links die Wahrscheinlichkeitsverteilung und rechts die kummulaitve Wahrscheinlichkeitsverteilung für $X \\sim Binomial(20, 0.2)$. Erkennen Sie, dass man jeweils von der einen Verteilung auf die andere schliessen kann?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Wahrscheinlichkeitsverteilung und kumulative Wahrscheinlichkeitsverteilung für X~Bin(20, 0.2)](02_prop_distributions_files/figure-html/fig-plot-binom-20-1.png){#fig-plot-binom-20 fig-align='center' width=480}\n:::\n:::\n\n\nFür eine kontinuierliche Zufallsvariable $X$ gilt jedoch $P(X = x) = 0$ für alle $x$. Anders als bei diskreten Variablen können wir also die Wahrscheinlichkeitsverteilung von $X$ nicht mittels der Angaben von \"Punkt\"-Wahrscheinlichkeiten beschreiben. Die Wahrscheinlichkeitsverteilung einer kontinuierlichen Variablen $X$ kann jedoch beschrieben werden, indem man die Wahrscheinlichkeiten für Intervalle angibt:\n\n$$\nP(X \\in [a, b]) = P(a < X \\le b)\n$$\n\nAnmerkung: Bei kontinuierlichen Variablen ist $<$ und $\\le$ dasselbe, weil $P(X = x) = 0$. \n\nUm $P(a < X \\le b)$ zu berechnen, reicht es, die kumulative Verteilungsfunktion $F(x) = P(X \\le x)$ zu kennen, weil $P(a<X ≤b)=F(b)−F(a)$. Zusammenfassend heisst dies, dass die Wahrscheinlichkeitsverteilung einer kontinuierlichen Variablen $X$ durch die kumulative Verteilungsfunktion $F(\\cdot)$ beschrieben werden kann. Analog zur Wahrscheinlichkeitsfunktion bei diskreten Variablen gibt es für kontinuierliche Variablen die **Dichtefunktion** $f(x)$. Diese erhält man durch Ableiten der kumulativen Wahrscheinlichkeitsfunktion: $$f(x) = F'(x).$$\n\nUmgekehrt kann man aus der Dichte die kumulative Wahrscheinlichkeitsfunktion durch Integrieren zurückgewinnen:\n\n$$\nF(x) = \\int_{-\\infty}^x f(t)dt\n$$\n\n\nIn `R` erhalten wir die Dichte der Normalverteilung mit `dnorm(x, mu, sigma)` (darum dieses *d* (wie oben gesehen, steht im diskreten Fall das *d* für die Wahrscheinlichkeitsmasse statt für die Wahrscheinlichkeitsdichte)) und die kumulative Wahrscheinlichkeitsfunktion mit `pnorm(x, mu, sigma)`. In @fig-plot-norm-0 sehen Sie links die Dichtefunktion und rechts die kumulaitve Wahrscheinlichkeitsverteilung für $X \\sim N(0, 1)$. Erkennen Sie, dass man jeweils von der einen Verteilung auf die andere schliessen kann?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Dichte und kumulative Wahrscheinlichkeitsverteilung für X~N(0, 1)](02_prop_distributions_files/figure-html/fig-plot-norm-0-1.png){#fig-plot-norm-0 fig-align='center' width=480}\n:::\n:::\n\n\n\n\n### Anwendung der Normalverteilung\n\nBeispiel: Der Intelligenzquotient (IQ-Score) ist normalverteilt. Er hat einen Mittelwert $\\mu$ = 100 und eine Standardabweichung $\\sigma$ = 15. Die @fig-plot-normal-iq zeigt die Wahrscheinlichkeitsverteilung für den IQ-Score. Uns interessiert z.B. die Frage, wie gross ist die Wahrscheinlichkeit, dass bei einem Test der IQ-Score zwischen 120 und 140 (also in ein bestimmtes Werteintervall) fällt, also $P(120 \\le X \\le 140)$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Wahrscheinlichkeit für IQ-Score zwischen 120 und 140](02_prop_distributions_files/figure-html/fig-plot-normal-iq-1.png){#fig-plot-normal-iq fig-align='center' width=480}\n:::\n:::\n\n\nDie @fig-plot-normal-iq zeigt, dass die Verteilung des IQ-Score symmetrisch ist. Die Höhe der Kurve ist die Dichte und gibt in einem bestimmten Abschnitt die \"Wahrscheinlichkeit\" für einen bestimmten Wertebereich an. Beachte, dass die Wahrscheinlichkeit für einen bestimmten Wert aber immer 0 ist (siehe @sec-exkurs-wahrscheinlichkeitsfunktion-und-dichtefunktion). Die Kurve hat ihr Maximum im Wertebereich um 100, also beim Mittelwert. Je weiter wir uns nach links oder rechts vom Mittelwert entfernen, desto geringer wird die Wahrscheinlichkeit für einen bestimmten IQ-Score. Die blaue Fläche zwischen den IQ-Scores 120 und 140 macht 8.7% der Gesamtfläche unter der Kurve aus (wie man diese Fläche berechnet, folgt später). Damit ist die Wahrscheinlichkeit, dass der IQ-Score zwischen 120 und 140 fällt $p$ = 0.087 bzw. 8.7%. Wir sehen also, dass ein IQ-Score zwischen 120 und 140 ein nicht sehr häufiges Ereignis ist.\n\nWie bereits erwähnt ist die Normalverteilung eine wichtige Wahrscheinlichkeitsverteilung in der Statistik, weil sie die Modellierung zahlreicher natürlicher Phänomene erlaubt. So sind z.B. Körpergrösse, Blutdruck, Messfehler von Instrumenten und Hämoglobin-Gehalt im Blut annähernd normal verteilt. Als Dichtefunktion beschreibt sie, wie die Werte (Merkmalsausprägungen) einer Variablen (Beobachtungsmerkmal) verteilt sind. Die Kurve hat die Form einer Glocke (Gauss'sche Glockenkurve) und ist symmetrisch bezüglich des Mittelwerts, d.h. die häufigsten Merkmalsausprägungen liegen in der Nähe des Mittelwerts. Mit zunehmendem Abstand vom Mittelwert nach links oder rechts nimmt die Wahrscheinlichkeit für Werte ab und die Verteilungskurve nähert sich dem Wert 0, den sie aber nie erreicht! Das heisst die untere und obere Grenze einer Normalverteilung sind $(-\\infty ; \\infty)$.\n\nBeispiel: Körpergrösse ist eine normalverteilte Variable. Die @fig-plot-frauen-14 zeigt die Verteilung der Körpergrösse von 14-jährigen Frauen aus einer Stichprobe von $n$ = 800.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Körpergrösse 14-jähriger Mädchen in m (n = 800)](02_prop_distributions_files/figure-html/fig-plot-frauen-14-1.png){#fig-plot-frauen-14 fig-align='center' width=480}\n:::\n:::\n\n\nDas Histogramm in @fig-plot-frauen-14 zeigt die Verteilung der Daten in der Stichprobe und wir erkennen, dass die meisten Werte um den Mittelwert $\\bar{x}$ = 1.52 m liegen. Werte über 1.65 m oder unter 1.4 m sind vergleichsweise selten anzutreffen. Die rote Kurve ist die theoretische Normalverteilungskurve mit dem Mittelwert $\\mu$ = 1.52 m und der Standardabweichung $\\sigma$ = 0.07 m. Obwohl die Kurve das Histogramm nicht exakt abbildet, scheint sie ein akzeptables Modell für die emprirische Häufigkeitsverteilung zu liefern und wir dürfen annehmen, dass unsere Stichprobe aus einer annähernd normalverteilten Population stammt.\n\n### Parameter der Normalverteilung\n\nEine Normalverteilung wird mit den Parametern *Mittelwert* $\\mu$ und *Varianz* $\\sigma^2$ vollständig beschrieben. Die Form einer Normalverteilung variiert jedoch in Abhängigkeit von diesen Parametern.\n\nFür die mathematisch Interessierten: Eine normalverteilte Variable $X$ mit Parametern $\\mu$\nund $\\sigma^2$ hat die Dichte\n\\begin{equation}\n  f(x)=\\frac{1}{\\sqrt{2\\pi\\sigma^2}} \n    \\exp\\left(-\\frac{(x-\\mu)^2}{2\\sigma^2}\\right), \\quad x\\in \\mathbb{R}.\n\\end{equation}\n\nDer Mittelwert ist die Kennzahl der zentralen Lage. Er gibt den Wert an, an dem die Glockenkurve ihr Maximum hat. Die meisten Werte gruppieren sich um den Mittelwert herum. Eine Veränderung des Mittelwerts verschiebt die Kurve nach links oder nach rechts auf der x-Achse einer Grafik.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Der Mittelwert beeinflusst die Lage der Verteilung auf der x-Achse](02_prop_distributions_files/figure-html/fig-plot-normal-mean-influence-1.png){#fig-plot-normal-mean-influence fig-align='center' width=480}\n:::\n:::\n\n\nDie Standardabweichung ist eine Kennzahl der Streuung. Unterschiedliche Standardabweichungen beeinflussen die Breite der Glockenkurve.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Die Standardabweichung beeinflusst die Breite der Glockenkurve](02_prop_distributions_files/figure-html/fig-plot-normal-sd-influence-1.png){#fig-plot-normal-sd-influence fig-align='center' width=480}\n:::\n:::\n\n\n### Kennzahlen der Population vs. Kennzahlen von Stichproben\n\nWie oben ausgeführt, beschreibt das Normalverteilungsmodell die Verteilung der Daten in der Population. **Um Stichprobenkennzahlen und Populationparameter leicht zu unterschieden, ist es gebräuchlich, Populationskennzahlen mit griechischen Buchstaben und Stichprobenkennzahlen mit römischen Buchstaben anzugeben.** Daher wird ein Populationsmittelwert mit dem griechischen Symbol $\\mu$ und eine Populationsstandardabweichung stets mit dem griechischen Symbol $\\sigma$ angegeben.\n\nÜblicherweise sind $\\mu$ und $\\sigma$ einer Population jedoch unbekannt, da es in der Regel unmöglich ist, eine gesamte Population zu messen. Wir können jedoch Zufallsstichproben ziehen um diese Parameter zu *schätzen*. Die Stichprobenkennzahlen, die als Punktschätzer (engl. point estimate) für die Populationsparameter dienen, werden mit den Symbolen $\\bar{x}$ für den Stichprobenmittelwert und $s$ für die Stichprobenstandardabweichung angegeben. Es kann sein, dass sie manchmal den Symbolen $\\hat{\\mu}$ und $\\hat{\\sigma}$ begegnen. Der Hut bedeutet, dass $\\mu$ und $\\sigma$ geschätzt wurden. Es gilt also $\\hat{\\mu} = \\bar{x}$ und $\\hat{\\sigma} =s$. Aus technischen Gründen muss in Grafiken gelegentlich auf griechische Buchstaben verzichtet werden.\n\n### Eigenschaften von Normalverteilungen\n\nTrotz ihrer unterschiedlichen Formen haben alle Normalverteilungen folgende gemeinsamen Eigenschaften:\n\n-   Alle Normalverteilungen sind symmetrisch.\n\n-   Median und Mittelwert sind identisch.\n\n-   Eine Hälfte der Werte liegt unter und eine Hälfte über dem Mittelwert.\n\n-   Die 68-95-99.7 Regel erlaubt es, den Anteil der Werte innerhalb einer bestimmten Distanz vom Mittelwert zu bestimmen.\n\n### Die 68 -- 95 -- 99.7 -- Regel\n\nDie 68-95-99.7 Regel ist eine empirische Regel der angewandten Statistik, die einen anschaulichen Zusammenhang zwischen Mittelwert und Standardabweichung eines normalverteilten Zufallsereignisses ermöglicht. Sie gibt an, wie viel Prozent der Daten innerhalb einer, zwei bzw. drei Standardabweichungen $\\sigma$ vom Mittelwert $\\mu$ entfernt sind.\n\nAls Faustregel gilt:\n\n-   Mittelwert +/- 1 Standardabweichung: 68% der Werte\n-   Mittelwert +/- 2 Standardabweichungen: 95% der Werte\n-   Mittelwert +/- 3 Standardabweichungen: 99.7% der Werte\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Die 68-95-99.7 - Regel](02_prop_distributions_files/figure-html/fig-plot-6895997-rule-1.png){#fig-plot-6895997-rule fig-align='center' width=480}\n:::\n:::\n\n\nBeispiel: Ihr Lieblingspizzakurier wirbt damit, dass er innerhalb von durchschnittlich $\\bar{x}$ = 30 Minuten, mit einer Standardabweichung von $s$ = 5 Minuten die bestellte Pizza liefern kann. Unter Anwendung der 68-95-99.7-Regel bedeutet dies, dass die Auslieferung\n\n-   in 68% der Bestellungen innerhalb von 25 bis 35 Minuten,\\\n-   in 95% der Bestellungen innerhalb von 20 bis 40 Minuten und\\\n-   in 99.7% der Bestellungen innerhalb von 15 bis 45 Minuten erfolgt.\n\n## Die Standardnormalverteilung\n\nWenn wir beliebige, normalverteilte Merkmale messen, werden wir immer wieder neue Normalverteilungen mit jeweils ihrem eigenen Mittelwert und ihrer eigenen Standardabweichung erhalten. D.h. die Normalverteilungskurve wird manchmal breiter, manchmal schmaler, manchmal höher, manchmal tiefer sein. Jedes Merkmal weist seine charakteristische Verteilung auf. In der Statistik interessieren wir uns oft für die Wahrscheinlichkeit, dass ein bestimmtes Ereignis eintritt z.B. das Ereignis, dass eine Studentin mindestens 168 cm gross ist: $P(X > 168)$. Bei Daten aus normalverteilten Populationen erfolgt die Berechnung von Wahrscheinlichkeiten über die Berechnung von Flächeninhalten unter der Normalverteilungskurve. Allerdings ist diese Berechnung von Flächen unter Kurven eine nicht ganz triviale Angelegenheit. Das Integral der Dichtefunktion der Normalverteilung ist nicht explizit darstellbar mit Standardfunktionen wie $exp(x)$, $log(x)$ etc. Um diese Berechnungen zu erleichtern, wurde die **Standardnormalverteilung** \"erfunden\". Diese ist eine Normalverteilung mit dem Mittelwert $\\mu$ = 0 und der Standardabweichung $\\sigma$ = 1. \n\nMan notiert die Standardnormalverteilung mit $\\phi(x)$ für die Dichte $f(x)$ und $\\Phi(x)$ für die kumulierte Verteilung $F(x)$: Die Standardnormalverteilung hat die Dichte\n\\begin{equation}\n      \\phi(x)=\\frac{1}{\\sqrt{2\\pi}}\\exp{\\left(-\\frac{1}{2}x^2\\right)}\n\\end{equation}\nund die kumulative Verteilungsfunktion der Standardnormalverteilung ist demnach\n\\begin{align}\n  \\Phi(x)=\\Pr(X<x)=\\int_{-\\infty}^x\\phi(t)dt.\n\\end{align}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02_prop_distributions_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nJede beliebige Normalverteilung kann durch die **Transformation** \n\n$$Z = \\frac{X-\\mu}{\\sigma}$$\n\nin eine Standardnormalverteilung umgewandelt werden, was Flächenberechnungen erheblich erleichtert, da die Werte der dazugehörigen kumulativen Verteilungsfunktion tabelliert vorliegen. Mann muss diese also nicht jedes mal neu ausrechnen, sondern es reicht, wenn man eine Transformation in eine Standardnormalverteilung vornimmt.\n\nUmgekehrt kann man mit der Umkehrfunktion\n\n$$X=Z\\sigma+\\mu$$ \n\neine normalverteilte Variable mit willkürlichem $\\mu$ und $\\sigma$ generieren, also beliebig zentrieren und skalieren, wie das verschiedene Messinstrumente machen, die z.B. ein $X$ mit einen Mittelwert von 100 und eine Standardabweichung von 15 wollen.\n\nEin bestimmter Wert von $Z$ in der Standardnormalverteilung wird als $z$-Wert bezeichnet. Der $z$-Wert gibt an, *um wie viele Standardabweichungen dieser Wert vom Mittelwert entfernt ist*. Ist der $z$-Wert negativ, liegt der Wert links vom Mittelwert, d.h. er ist kleiner als der Mittelwert. Ist der $z$-Wert positiv, liegt der Wert rechts vom Mittelwert und ist somit grösser. Der Mittelwert selber hat stets den $z$-Wert 0. Es gilt also $Z \\sim N(0,1)$.\n\n\n\n### Berechnung von $z$-Werten ($z$-Transformation)\n\nUm Stichprobendaten zu standardisieren, müssen die Rohdaten in $z$-Werte umgerechnet werden. Die Umwandlung einer beliebigen Normalverteilung in die Standardnormalverteilung erfolgt nach der Formel:\n\n$$z_i=\\frac{x_i - \\bar{x}}{s}$$\n\nBeispiel: Du hast zwei Äpfel, der eine wiegt 85g, der andere wiegt 110 g. Das durchschnittliche Gewicht von Äpfeln beträgt $\\bar{x}$ = 100g mit einer Standardabweichung $s$ = 10 g.\n\n-   z-Wert für den 85g-Apfel: $z_{85}=\\frac{85-100}{10} = -1.5$\\\n-   z-Wert für den 110g-Apfel: $z_{110}=\\frac{110-100}{10} = 1$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Gewicht von Äpfeln (g), roh und standardisiert. Der Blaue Punkt ist der Mittelwert.](02_prop_distributions_files/figure-html/fig-plot-apple-raw-1.png){#fig-plot-apple-raw fig-align='center' width=672}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![z-Werte der beiden Äpfel](02_prop_distributions_files/figure-html/fig-plot-apple-z-1.png){#fig-plot-apple-z fig-align='center' width=672}\n:::\n:::\n\n\nDer $z$-Wert für den 85g Apfel ist negativ da er leichter ist als ein durchschnittlicher Apfel. Um wie viel leichter? Um -1.5 Standardabweichungen = -1.5 $\\times$ 10 = -15g. Der $z$-Wert für den 110g-Apfel ist positiv, d.h. er ist schwerer als ein durchschnittlicher Apfel. Um wie viel schwerer? Um 1 Standardabweichung = 1 $\\times$ 10 = 10g.\n\n### Interpretation von z-Werten\n\nUns interessiert jetzt die Frage: Wie wahrscheinlich ist es, dass ein Apfel 85g schwer oder leichter ist? Also $P(X \\le 85) = P(Z \\le \\frac{85-100}{10}) = P(Z \\le -1.5)$. Wie oben bereits erwähnt ist bei kontinuierlichen Variablen $P(Z \\le -1.5) = P(Z < -1.5)$. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Wahrscheinlichkeit für Z <= -1.5](02_prop_distributions_files/figure-html/fig-plot-le-z-1.png){#fig-plot-le-z fig-align='center' width=672}\n:::\n:::\n\n\nDie blaue Fläche unter der Kurve in @fig-plot-le-z entspricht der Wahrscheinlichkeit für $Z \\leq -1.5$. Mit Hilfe der kumulativen Wahrscheinlichkeitsfunktion $\\Phi(z)$ kann man diese leicht ablesen als $\\Phi(-1.5)$:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Kumulative Wahrscheinlichkeitsfunktion der Standardnormalverteilung. Eingezeichnet die kumulative Wahrscheinlichkeit bei Z < -1.5\"](02_prop_distributions_files/figure-html/fig-plot-kum-norm-1.png){#fig-plot-kum-norm fig-align='center' width=480}\n:::\n:::\n\n\nVor dem Computerzeitalter hat man die kumulative Wahrscheinlichkeitsfunktion tabelliert, siehe z.B. [hier](https://de.wikipedia.org/wiki/Standardnormalverteilungstabelle). Mit dem Computer können wir bequemer auf diese kumulative Wahrscheinlichkeitsfunktion zugreifen. In diesem Fall erhalten wir mit der Funktion `pnorm(-1.5)` die kumulative Wahrscheinlichkeit von $-\\infty$ bis $-1.5$ (was der blauen Fläche entspricht).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(-1.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0668072\n```\n\n\n:::\n:::\n\n\n`R` gibt eine Wahrscheinlichkeit von $p$ = 0.067 für $z \\leq -1.5$ an. Das bedeutet, dass wir erwarten können, dass die Wahrscheinlichkeit einen Apfel von 85g oder einen leichteren Apfel zu erhalten bei 6.7% liegt. Umgekehrt heisst es auch, dass die Wahrscheinlichkeit, einen Apfel zu erhalten, der schwerer als 85g ist, ist gleich $p = 1-0.067 = 0.933$ bzw. 93.3%.\n\nAuch folgende Frage können wir stellen: Wie wahrscheinlich ist es, dass Ein Apfel 110g oder mehr wiegt? Also $P(X \\ge 110) = P(Z \\ge \\frac{110-100}{10}) = P(Z \\ge 1)$. Auch hier gilt: $P(Z \\ge 1) = P(Z > 1)$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Wahrscheinlichkeit für Z > 1](02_prop_distributions_files/figure-html/fig-plot-ge-z-1.png){#fig-plot-ge-z fig-align='center' width=672}\n:::\n:::\n\n\nDie blaue Fläche in @fig-plot-ge-z entspricht der Wahrscheinlichkeit für $Z\\geq1$. Wiederum hilft uns die z-Werte-Tabelle oder die Funktion `pnorm()` in `R`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8413447\n```\n\n\n:::\n:::\n\n\nAber dieses Ergebnis kann nicht richtig sein! Die Wahrscheinlichkeit muss kleiner als 50% sein, da ja nicht die ganze Fläche rechts vom Mittelwert blau eingefärbt ist. Der \"Fehler\" kommt daher, dass die Funktion `pnorm()` stets die Fläche unterhalb des angegebenen $z$-Werts, also die Fläche links vom $z$-Wert, berechnet. Daher müssen wir in diesem Fall eine kleine Anpassung vornehmen und wir ziehen den P-Wert einfach von 1 ab:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n1 - pnorm(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1586553\n```\n\n\n:::\n:::\n\n\nUnsere Berechnungen haben ergeben, dass die Wahrscheinlichkeit, einen Apfel von 110g oder schwerer zu erhalten bei 15.8% liegt.\n\nZum Schluss noch folgende Übung: Wie gross ist die Wahrscheinlichkeit dafür, dass das Gewicht eines Apfels zwischen 85g und 110g liegt? Auch diese Berechnung ist kein Problem: Zuerst berechnen wir, wie gross die Wahrscheinlichkeit ist, dass ein Apfel maximal 110g schwer ist (siehe a) und ziehen von diesem Wert die Wahrscheinlichkeit ab, dass ein Apfel maximal 85g schwer ist (siehe b).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Wahrscheinlichkeit für a < Z < b](02_prop_distributions_files/figure-html/fig-plot-between-z-1.png){#fig-plot-between-z fig-align='center' width=672}\n:::\n:::\n\n\nDie Berechnung in `R` folgt genau diesem Prinzip:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#  Wahrscheinlichkeit für z < 1\na <- pnorm(1)  \n\n# Wahrscheinlichkeit für z < -1.5\nb <- pnorm(-1.5)  \n\n# Wahrscheinlichkeit für -1.5 <= z < 1\na - b             \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7745375\n```\n\n\n:::\n:::\n\n\nDie Wahrscheinlichkeit, dass ein Apfel zwischen 85g und 110g wiegt beträgt 77.5% ($p = 0.775$).\n\n## Prüfung auf Normalverteilung\n\nÜblicherweise ist die Verteilung der Daten in der Population unbekannt. Daher müssen wir anhand von Stichprobendaten abschätzen, ob eine Normalverteilung zu Grunde liegt. Dazu existieren mehrere Verfahren:\n\n-   Visuelle Verfahren zur Prüfung auf Normalverteilung\n    -   Histogramm\n    -   Boxplot\n    -   QQ-Plot\n-   Mathematische Verfahren\n    -   Vergleich von Mittelwert und Median\n    -   Speziell dafür konzipierte statistische Verfahren\n\nWir bevorzugen visuelle Verfahren.\n\n### QQ-Plot {.unnumbered}\n\nDer **QQ-Plot** (Quantile-Quantile-Plot) ist ein wichtiges visuelles Hilfsmittel um zwei Wahrscheinlichkeitsverteilungen miteinander zu vergleichen. Wenn diese beiden Verteilungen identisch sind, liegen im QQ-Plot alle Punkte auf einer (diagonalen) Linie.\n\nIm QQ-Plot für Normalverteilung werden auf der x-Achse die Quantile einer Normalverteilung (theoretisch erwartete Werte) eingetragen und auf der y-Achse die Quantile der beobachteten Daten (Stichprobendaten).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Histogramm, Boxplot und QQ-Plot für eine Normalverteilung.](02_prop_distributions_files/figure-html/fig-plot-norm-test-1.png){#fig-plot-norm-test fig-align='center' width=672}\n:::\n:::\n\n\nWeichen die Daten nicht/nur wenig von einer Normalverteilung ab, dann...\n\n-   ... hat das Histogramm annähernd die Form einer symmetrischen Glockenkurve.\n-   ... ist der Boxplot symmetrisch, Median und Mittelwert (roter Punkt) sind annähernd identisch.\n-   ... liegen die Punkte im QQ-Plot annähernd auf einer diagnonalen Geraden.\n\nSomit besteht wenig Evidenz, dass die Daten nicht normalverteilt sind.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Histogramm Boxplot und QQ-Plot für eine linksschiefe Verteilung.](02_prop_distributions_files/figure-html/fig-plot-leftskewed-1.png){#fig-plot-leftskewed fig-align='center' width=672}\n:::\n:::\n\n\nBeispiel für eine linksschiefe Verteilung (@fig-plot-leftskewed):\n\n-   Im Histogramm sind die Daten linksschief verteilt.\n-   Der Boxplot ist asymmetrisch, der Mittelwert (roter Punkt) ist kleiner als der Median.\n-   Der QQ-Plot weist eine deutliche, nach oben konvexe Krümmung auf.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Histogramm, Boxplot und QQ-Plot für eine rechtsschiefe Verteilung.](02_prop_distributions_files/figure-html/fig-plot-rightskewed-1.png){#fig-plot-rightskewed fig-align='center' width=672}\n:::\n:::\n\n\nBeispiel für eine rechtsschiefe Verteilung (@fig-plot-rightskewed):\n\n-   Im Histogramm sind die Daten rechtsschief verteilt.\n-   Der Boxplot ist asymmetrisch, der Mittelwert (roter Punkt) ist grösser als der Median.\n-   Der QQ-Plot weist eine deutliche, nach unten konvexe Krümmung auf.\n\nDie Interpretation von QQ-Plots für kleine Stichproben ist schwierig und nicht immer ganz eindeutig möglich.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![QQ-Plots für 10 Stichproben (n = 28) aus einer perfekten Normalverteilung](02_prop_distributions_files/figure-html/fig-plot-qq-n-small-1.png){#fig-plot-qq-n-small fig-align='center' width=672}\n:::\n:::\n\n\nIn der @fig-plot-qq-n-small wurden zehn Stichproben im Umfang von $n$ = 28 aus einer perfekt normalverteilten Population gezogen. Die Grafiken 3, 6 und 8 könnten auch zur Einschätzung führen, dass die Daten nicht normal verteilt sind. Mit anderen Worten: solche Abweichung sind unter einer Normalverteilung zu erwarten.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Reale Daten zur Körpergrösse](02_prop_distributions_files/figure-html/fig-plot-qq-real-1.png){#fig-plot-qq-real fig-align='center' width=672}\n:::\n:::\n\n\nDiese @fig-plot-qq-real zeigt reale Daten zur Körpergrösse aus einer Stichprobe $n$ = 50 Personen. Obwohl wir theoretisch wissen, dass Körpergrösse eine normalverteilte Variable ist, würden wir aus den Stichprobendaten vermutlich einen anderen Schluss ziehen.\n\nIn gewissen Disziplinen sind statistische Tests zur Normalitätsprüfung populär. Diese Tests sind Hypothesentests (siehe @sec-grundlagen-der-inferenzstatistik) auf Normalverteilung. Die Nullhypothese dieser Tests ist, dass sich die Stichprobenverteilung und eine Normalverteilung nicht unterscheiden.\n\n-   Wenn der P-Wert des Tests gleich oder kleiner als 0.05 ist, dann wird die Normalitätshypothese durch den Test (z.B. den Shapiro-Test) abgelehnt. Das heisst, dass die Daten mit mindestens 95%iger Sicherheit nicht der Normalverteilung entsprechen.\n-   Ist der P-Wert des Tests grösser als 0.05 ist der Test \"bestanden\" und es besteht nicht genug Evidenz für eine signifikante Abweichung von der Normalverteilung.\n\nWie oben schon erwähnt, raten wir von solchen Tests zur Prüfung auf Normalverteilung ab. Die Normalverteilung ist ein Konstrukt, das in seiner mathematisch reinen Form in der Natur nicht vorkommt. Keine Variable ist exakt normalverteilt. Es ist daher sinnlos zu fragen \"Sind meine Daten normalverteilt?\", weil die Antwort immer \"NEIN\" ist. Als Modell leistet die Normalverteilung jedoch gute Dienste und die bessere Fragestellung lautet \"Habe ich Hinweise, die dagegen sprechen, dass meine Daten annähernd normalverteilt sind?\" bzw. \"Liegt Evidenz dafür vor, dass ich nicht von normalverteilten Daten ausgehen kann?\".\n\n## Die $t$-Verteilung\n\nDie $t$-Verteilung wird hier eingeführt, weil Statistikprogramme wie `R` bei Test- und Schätzverfahren häufig nicht die $z$-, sondern die $t$-Verteilung verwenden – unabhängig vom Stichprobenumfang. Der Grund dafür ist, dass die $t$-Verteilung die Unsicherheit bei der Schätzung der Standardabweichung berücksichtigt und dadurch präzisere Ergebnisse liefert. Die $t$-Verteilung ist eine Variante der Normalverteilung, die in der Statistik eine zentrale Rolle spielt.\n[William S. Gosset, Pseudonym: Student](https://higherlogicdownload.s3.amazonaws.com/AMSTAT/1484431b-3202-461e-b7e6-ebce10ca8bcd/UploadedImages/Classroom_Activities/HS_7__t-ditribution_and_GOSSET.pdf) zeigte, dass die standardisierte Schätzfunktion des Stichprobenmittelwerts bei normalverteilten Daten nicht mehr normalverteilt, sondern exakt $t$-verteilt ist, wenn die zur Standardisierung benötigte Varianz nicht bekannt, sondern aus der Stichprobe geschätzt wird – was in der Praxis fast immer der Fall ist.Die $t$-Verteilung erlaubt daher – insbesondere bei kleinen Stichproben – eine korrekte Berechnung der Verteilung der Differenz zwischen dem Stichprobenmittelwert und dem wahren Mittelwert der Grundgesamtheit.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![t-Verteilung für df = 3, 10, 30 und 50; Normalverteilung](02_prop_distributions_files/figure-html/fig-plot-t-distr-1.png){#fig-plot-t-distr fig-align='center' width=480}\n:::\n:::\n\n\nWas muss ich zur t-Verteilung wissen?\n\n-   Für die praktische Arbeit gilt, dass die $t$-Verteilung als Anpassung der Normalverteilung für kleine Stichprobenumfänge aufgefasst werden kann. Ab einem Stichprobenumfang von $n$ \\> 30 entspricht sie annähernd der Normalverteilung (diese Grenze ist bei den Statistikern umstritten, für uns ist sie jedoch als Faustregel gültig). Der $t$-Wert, den Statistikprogramme berechnen, wird gleich wie ein $z$-Wert interpretiert.\n-   Die Form der $t$-Verteilung ist abhängig vom Stichprobenumfang $n$. Dieser wird in Freiheitsgraden (degrees of freedom, $df$ angegeben). Wie Sie die Anzahl Freiheitsgrade berechnen, erfahren Sie in den entsprechenden Kapiteln). Im einfachsten Fall ist $df = n - 1$. Je grösser die Anzahl Freiheitsgrade $df$ ist, desto mehr nähert sich die $t$-Verteilung der Normalverteilung an.\n-   Wie bei der Normalverteilung können auch Flächen unter der $t$-Verteilung bestimmt werden. Dafür existieren ebenfalls Tabellen, einfacher und genauer geht es mit `R`.\n-   Um $P(T_{df} \\le t)$ zu berechnen, verwenden Sie, analog zur Funktion `pnorm()`, die Funktion `pt()`, wobei Sie zusätzlich die Anzahl Freiheitsgrade angeben.\n\n**Beispiele zur Berechnung von Wahrscheinlichkeiten anhand der** $t$**-Verteilung:**\n\n$P(T_{19} \\le -1.5)$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npt(-1.5, 19)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07502427\n```\n\n\n:::\n:::\n\n\n$P(T_{9} \\ge 2)$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n1-pt(2, 9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03827641\n```\n\n\n:::\n:::\n\n\n$P(-2 \\le T_{14} \\le 2)$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na <- pt(2, 14)\nb <- pt(-2, 14)\na-b\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.934712\n```\n\n\n:::\n:::\n\n\nWenn Sie die gleichen Wahrscheinlichkeiten unter der Normalverteilung berechnen werden Sie feststellen, dass diese leicht verschieden sind.\n\n## Anhang: hilfreiche `R` Codes für die Binomial- und Normalverteilung\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Wahrscheinlichkeiten anhand einer Normalverteilung berechnen\nmu <- 170 # angenommener Mittelwert der Körpergrösse\nsigma <- 12 # angenommene Standardabweichung der Körpergrösse\n\n# Was ist der z-Wert, wenn eine Person 165 gross ist?\nx <- 165\nz <- (x-mu)/sigma # z-Transformation\nz\n\n# Die Wahrscheinlichkeit, dass jemand gleich gross oder kleiner ist als x\npnorm(z)\n\n# Die Wahrscheinlichkeit, dass jemand gleich gross oder grösser ist als x\n1-pnorm(z) # pnorm berechnet die Fläche links von x\n\n# Wie gross muss jemand sein, um bei den grössten 10% zu sein?\n# Hier muss anhand der Wahrscheinlichkeit der z-Wert gefunden werden\np <- 0.1\nz <- qnorm(1-p) # wir suchen den z-Wert, welcher zu 10%, bzw. 90%\nx <- z * sigma + mu # Umformung der z-Transformation, um den gesuchten Wert zu finden.\nx\n\n# Wie gross ist die Wahrscheinlichkeit, dass jemand zwischen 160 und 175 gross ist?\nx1 <- 160\nz1 <- (x1-mu)/sigma\np1 <- pnorm(z1) # Fläche unterhlab von 160cm\np1\n\nx2 <- 175\nz2 <- (x2-mu)/sigma\np2 <- 1-pnorm(z2) # Fläche oberhalb von 175cm\np2\n\n1 - (p1+p2) # Wir addieren die beiden Randflächen und ziehen sie von der totalen Fläche (1) ab\n\n# Die norm()-Funktionen\npnorm(1.96) # Das p steht für probability. Es wird die Fläche, also die Wahrscheinlichkeit für einen z-Wert kleiner oder gleich gross 1.96 berechnet.\nqnorm(0.975) # Das q steht für quantile. Es wird der z-Wert für das entsprechende Quantil berechnet.\nrnorm(100, 10, 2) # Dar r steht für random. Aus einer Normalverteilung mit mu = 10 und sigma = 2 werden zufällig 100 Werte gezogen.\n\n## QQ-Plot um zu überprüfen, ob die Daten aus einer normalverteilten Population stammen\nx <- rnorm(100, 10, 2)\nqqnorm(x); qqline(x)\n\n# t-Verteilung\nt <- z # der t-Wert wird gleich berechnet wie der z-Wert\ndf <- 19 # Die 20 ist ein willkürliches Beispiel. In einfachen Situationen ist df = n-1\npt(t, df) # P(T <= t) mit df = 19\n1-pt(t, df) # P(T >= t) mit df = 19\nqt(0.975, df) # Das q steht für quantile. Es wird der t-Wert für das entsprechende Quantil berechnet.\n\n# Binomialverteilung\n## Die Funktionen pbinom() und dbinom() brauchen die Argumente x, n und p:\npbinom(5, 10, 0.5) # Wahrscheinlichkeit für MAXIMAL 5 Erfolge bei 10 Versuchen und einer Erfolgswahrscheinlichkeit von 50%\ndbinom(5, 10, 0.5) # Wahrscheinlichkeit für GENAU 5 Erfolge bei 10 Versuchen und einer Erfolgswahrscheinlichkeit von 50%\n```\n:::\n\n",
    "supporting": [
      "02_prop_distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}