project:
  type: website

website:
  title: "Angewande Statistik Workshops"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "BSc"
        contents:
          - text: Intro Jamovi
            href: bsc/Intro-Jamovi.qmd
          - text: Deskriptive Statistik
            href: bsc/WS1-Deskriptive-Statistik.qmd
          - text: Verteilungen von Wahrscheinlichkeiten
            href: bsc/WS2-Verteilungen-Wahrscheinlichkeit.qmd
          - text: Grundlagen Inferenzstatistik
            href: bsc/WS3-Grundlagen-Inferenz.qmd
          - text: Vergleich von Mittelwerten
            href: bsc/WS4-Vergleich-Mittelwerte.qmd
          - text: Korrelation und Regression
            href: bsc/WS5-Korrelation-Regression.qmd
          - text: Inferenz Kategoriell
            href: bsc/WS6-Inferenz-Kategoriell.qmd
          - text: Workshop Overall
            href: bsc/Exercises-Overall.qmd
      - section: "MSc"
        contents:
          - text: Deskriptive Statistik
            href: msc/ex11-deskriptive-statistik.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    toc: true
    toc_float: true # for easier navigation
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    highlight: monochrome
    code_folding: hide # enables you to include R code but have it hidden by default. Users can choose to show hidden R code either individually or document wide (e.g exercies solutions).
    css: styles.css

bibliography: [../bibliography.bib]

# filters:
#   - auto-dark # see https://github.com/gadenbuie/quarto-auto-dark

execute:
  echo: true
  warning: false
  error: false
  message: false
  freeze: true  # never re-execute computational content during project render
